import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {server,Client,initialize} from './helpers';
import {analyzeMetrics} from '../packages/domain/src/metrics';
import {normalizeMetric} from '../packages/domain/src/imports';
let env:Awaited<ReturnType<typeof server>>,c:Client,me:any,account:any,p:any,p2:any;
const start='2026-09-01T00:00:00.000Z',end='2026-10-01T00:00:00.000Z';
const input=(pid:string|null,key:string,value:string|null='12',extra:any={})=>({target:{account_id:account.id,publication_id:pid},metric_key:key,definition_version:'1',aggregation_kind:key==='followers'?'snapshot':'interval',value,unit:['followers','attributed_follows'].includes(key)?'人':'次',observed_at:end,window_start:start,window_end:end,traffic_type:'organic',is_approximate:false,source_definition:'合成S8后台定义',time_precision:'day',missing_reason:value===null?'未提供':null,...extra});
async function commit(m:any){const batch=await c.call('/imports','POST',{account_id:account.id,file_ids:[],source_type:'manual',manual_rows:[m]});assert.equal(batch.status,202);const rows=(await c.call('/imports/'+batch.data.id+'/rows')).data.items;assert.equal(rows[0].status,'valid');const r=await c.call('/imports/'+batch.data.id+'/confirm','POST',{row_ids:[rows[0].id],conflict_resolutions:[],reason:'合成验收确认',expected_version:batch.data.version});assert.equal(r.status,200);return (await env.db.query('SELECT o.* FROM metric_observations o JOIN metric_evidence e ON e.observation_id=o.id WHERE e.row_id=$1',[rows[0].id])).rows[0];}
before(async()=>{env=await server();c=new Client(env.url);me=await initialize(c);account=(await c.call('/accounts','POST',{name:'合成S8账号',platform:'xiaohongshu',platform_user_id:'s8-controlled'})).data;for(const [id,media,date] of [['s8-graphic','graphic',start],['s8-video','video','2026-08-01T00:00:00.000Z']]){const r=await c.call('/publications','POST',{account_id:account.id,platform_note_id:id,url:'https://www.xiaohongshu.com/explore/'+id,title:'合成S8'+media,media_type:media,published_at:date,traffic_type:'organic'});assert.equal(r.status,201);if(media==='graphic')p=r.data;else p2=r.data;}});
after(async()=>await env.close());
test('看板真空态、未知账号/笔记/跨账号/越权与非法筛选拒绝',async()=>{const empty=await c.call('/metrics/analysis?account_id='+account.id);assert.equal(empty.status,200);assert.deepEqual(empty.data.groups,[]);assert.equal(empty.data.observations_count,0);assert.match(empty.data.missing_reason,/不生成趋势/);for(const q of ['account_id='+randomUUID(),'account_id='+account.id+'&publication_id='+randomUUID()])assert.equal((await c.call('/metrics/analysis?'+q)).status,404);for(const q of ['start='+start,'start='+end+'&end='+start,'campaign=true','media_type=invalid'])assert.equal((await c.call('/metrics/analysis?account_id='+account.id+'&'+q)).status,422);await env.db.query("UPDATE memberships SET roles=ARRAY['viewer'] WHERE id=$1",[me.membership.id]);await env.db.query('DELETE FROM account_memberships WHERE account_id=$1',[account.id]);assert.equal((await c.call('/metrics/analysis?account_id='+account.id)).status,404);await env.db.query("UPDATE memberships SET roles=ARRAY['admin'] WHERE id=$1",[me.membership.id]);});
test('分析完整口径分组，形式/流量/窗口正确，期末快照不进列表却参与计算',async()=>{await commit(input(null,'followers','600',{observed_at:start}));await commit(input(null,'followers','631'));await commit(input(p.id,'reads','3000'));await commit(input(p.id,'attributed_follows','12'));await commit(input(p2.id,'reads','8000'));await commit(input(p.id,'reads','100',{traffic_type:'paid'}));await commit(input(p.id,'reads','100',{source_definition:'另一合成平台定义'}));const q=new URLSearchParams({account_id:account.id,start,end});const list=(await c.call('/metrics?'+q)).data.items;assert.equal(list.filter((o:any)=>o.metric.metric_key==='followers').length,1);const calculated=await c.call('/metrics/calculations?'+q);assert.equal(calculated.status,200,JSON.stringify(calculated.error));assert.equal(calculated.data.items.find((x:any)=>x.metric_key==='net_followers').value,'31.000000');const analysis=(await c.call('/metrics/analysis?account_id='+account.id)).data;const followers=analysis.groups.find((g:any)=>g.metric_key==='followers');assert.equal(followers.trend_available,true);assert.deepEqual(followers.points.map((x:any)=>x.value),['600','631']);const reads=analysis.groups.find((g:any)=>g.metric_key==='reads'&&g.traffic_type==='organic'&&g.source_definition==='合成S8后台定义');assert.equal(reads.points.length,2);assert.match(reads.comparison_note,/发布后时长不同/);const filtered=(await c.call('/metrics/analysis?'+q+'&media_type=graphic&traffic_type=organic')).data;assert.ok(filtered.groups.every((g:any)=>g.traffic_type==='organic'&&g.points.every((x:any)=>x.media_type==='graphic')));assert.equal(filtered.groups.length,3);const pending=await c.call('/imports','POST',{account_id:account.id,file_ids:[],source_type:'manual',manual_rows:[input(p.id,'likes','99')]});assert.equal(pending.status,202);assert.ok(!(await c.call('/metrics/analysis?account_id='+account.id)).data.groups.some((g:any)=>g.metric_key==='likes'));});
test('缺失/约数/单快照/混合流量与统计类型保持分离，不填趋势',()=>{const points=[{id:randomUUID(),metric:normalizeMetric(input(null,'followers','1.2 万'))}];const one=analyzeMetrics(points).groups[0]!;assert.equal(one.trend_available,false);assert.equal(one.points[0]!.is_approximate,true);const more=analyzeMetrics([...points,{id:randomUUID(),metric:normalizeMetric(input(null,'followers',null,{traffic_type:'mixed'}))}]);assert.equal(more.groups.length,2);assert.equal(more.groups[1]!.points[0]!.value,null);const bad=analyzeMetrics([{id:randomUUID(),metric:normalizeMetric(input(p.id,'reads')),analysis_warning:'窗口早于发布时间',published_at:end}]);assert.match(bad.groups[0]!.comparison_note,/矛盾/);});
test('发布时间复核恢复同数据重算必须新ID且旧计算仍stale',async()=>{const q=new URLSearchParams({account_id:account.id,publication_id:p.id,start,end});const get=async()=>(await c.call('/metrics/calculations?'+q)).data.items.find((x:any)=>x.metric_key==='follows_per_1000_reads'&&x.source_definition==='合成S8后台定义'&&x.traffic_type==='organic');const old=await get();assert.equal(old.value,'4.000000');let r=await c.call('/publications/'+p.id,'PATCH',{published_at:'2026-09-02T00:00:00.000Z',reason:'时间核验',expected_version:1});assert.equal(r.status,200);r=await c.call('/publications/'+p.id,'PATCH',{published_at:start,reason:'恢复已核验时间',expected_version:2});assert.equal(r.status,200);const fresh=await get();assert.equal(fresh.value,old.value);assert.notEqual(fresh.id,old.id);assert.equal((await c.call('/calculations/'+old.id)).data.calculation.validity,'stale');assert.equal((await get()).id,fresh.id);});
