import {test} from 'node:test';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {Client,server,initialize} from './helpers';
import {png,uploadBytes} from './s2-helpers';
import {Storage} from '../packages/domain/src/storage';
import {Jobs} from '../packages/domain/src/jobs';
import {mediaHandler} from '../packages/domain/src/media';
test('PNG真实解析、透明预览、资产检索/文件夹/收藏、并发版本、确认/停用与历史双向引用',async()=>{
 const store=new Storage();await store.init();const s=await server();
 try{const c=new Client(s.url),me=await initialize(c);const f=await uploadBytes(c,s.url,png());const jobs=new Jobs(s.db,{'media.preview':mediaHandler(s.db,store)});await jobs.dispatch();const j=await jobs.claim('media');assert.ok(j);await jobs.process(j);const processed=(await s.db.query('SELECT * FROM file_objects WHERE id=$1',[f.id])).rows[0];assert.equal(processed.preview_status,'ready');assert.equal(processed.metadata.has_alpha,true);assert.equal(processed.metadata.width,2);assert.notEqual(processed.preview_file_id,f.id);
 const realBytes=readFileSync('docs/yoyo-workbench-v1.0/references/brand/page-17.png');const real=await uploadBytes(c,s.url,realBytes,'品牌参考-中文.png');await jobs.dispatch();const realJob=await jobs.claim('media');assert.ok(realJob);await jobs.process(realJob);const realFile=(await s.db.query('SELECT * FROM file_objects WHERE id=$1',[real.id])).rows[0];assert.equal(realFile.preview_status,'ready');const download=await c.call(`/files/${real.id}/download`);const downloaded=Buffer.from(await (await fetch(download.data.url)).arrayBuffer());assert.deepEqual(downloaded,realBytes);writeFileSync('docs/evidence/s2/real-png.json',JSON.stringify({checked_at:new Date().toISOString(),kind:'provided_reference_png_original_in_isolated_test',sha256:real.sha256,size_bytes:real.size_bytes,width:realFile.metadata.width,height:realFile.metadata.height,has_alpha:realFile.metadata.has_alpha,preview_ready:true,original_bytes_identical:true,synthetic_transparency_fixture_passed:true,production_usage_not_confirmed:true},null,2)+'\n');
 const folder=(await c.call('/folders','POST',{name:'PNG系列'})).data;const child=(await c.call('/folders','POST',{name:'子文件夹',parent_id:folder.id})).data;assert.equal((await c.call('/folders/'+folder.id,'PATCH',{parent_id:child.id,expected_version:folder.version})).status,422);
 let asset=(await c.call('/assets','POST',{name:'透明YOYO',category:'2d',source_file_id:f.id,ip_identity:'YOYO',owner_id:me.membership.id,source:'合成测试素材，无生产授权',folder_id:folder.id,tags:['透明']})).data;assert.ok(asset.id);
 assert.equal((await c.call('/assets?q=YOYO&tag=透明&folder_id='+folder.id)).data.items.length,1);assert.equal((await c.call(`/assets/${asset.id}/favorite`,'PUT')).status,200);assert.equal((await c.call('/assets?favorite=true')).data.items.length,1);
 const race=await Promise.all([c.call('/assets/'+asset.id,'PATCH',{name:'A',expected_version:1}),c.call('/assets/'+asset.id,'PATCH',{name:'B',expected_version:1})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);asset=(await c.call('/assets/'+asset.id)).data;
 asset=(await c.call(`/assets/${asset.id}/confirm`,'POST',{usage_scope:'仅测试，不允许公开发布',checklist:['测试依据'],expected_version:asset.version})).data;assert.equal(asset.business_status,'usable');const bound=asset.current_version_id;
 const ac=(await c.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'s2-ref-test',name:'引用测试'})).data;
 const content=(await s.db.query('INSERT INTO contents(workspace_id,account_id,created_by,title) VALUES($1,$2,$3,$4) RETURNING id',[me.workspace.id,ac.id,me.membership.id,'合成引用内容'])).rows[0];const rev=(await s.db.query('INSERT INTO content_revisions(workspace_id,content_id,created_by,revision_no) VALUES($1,$2,$3,1) RETURNING *',[me.workspace.id,content.id,me.membership.id])).rows[0];
 const usage=await c.call('/asset-usages','POST',{asset_version_id:bound,revision_id:rev.id,role:'cover',expected_version:1});assert.equal(usage.status,201);assert.equal((await c.call(`/assets/${asset.id}/usages`)).data.items[0].asset_version_id,bound);assert.equal((await c.call(`/content-revisions/${rev.id}/assets`)).data.items[0].asset_version_id,bound);
 await assert.rejects(s.db.query("UPDATE asset_versions SET usage_scope='changed' WHERE id=$1",[bound]));await assert.rejects(s.db.query('DELETE FROM asset_usages WHERE id=$1',[usage.data.id]));
 const newer=await c.call(`/assets/${asset.id}/versions`,'POST',{source_file_id:f.id,usage_scope:'新范围待确认',dependencies:[bound],base_version:asset.version});assert.equal(newer.status,201);asset=(await c.call('/assets/'+asset.id)).data;assert.equal(asset.business_status,'pending_confirmation');assert.equal((await c.call(`/assets/${asset.id}/usages`)).data.items[0].asset_version_id,bound);
 assert.equal((await c.call('/asset-relations','POST',{from_version_id:bound,to_version_id:newer.data.id,relation_type:'source_of'})).status,201);assert.equal((await c.call('/assets/'+asset.id)).data.relations.length,1);
 asset=(await c.call(`/assets/${asset.id}/retire`,'POST',{reason:'测试停用',expected_version:asset.version})).data;assert.equal((await c.call('/asset-usages','POST',{asset_version_id:bound,revision_id:rev.id,role:'page',expected_version:2})).status,422);assert.equal((await c.call(`/content-revisions/${rev.id}/assets`)).data.items[0].business_status,'retired');
 await s.db.query("UPDATE memberships SET roles=ARRAY['viewer'] WHERE id=$1",[me.membership.id]);assert.equal((await c.call(`/files/${f.id}/preview`)).status,200);assert.equal((await c.call(`/files/${f.id}/download`)).status,403);assert.equal((await c.call(`/assets/${asset.id}/confirm`,'POST',{usage_scope:'x',checklist:['x'],expected_version:asset.version})).status,403);
 }finally{await s.close();store.destroy();}
});
