import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Client,initialize,server} from './helpers';
import {Jobs} from '../packages/domain/src/jobs';
import {AITasks} from '../packages/domain/src/ai-tasks';
import {AIGateway,AIConfig} from '../packages/domain/src/ai-gateway';
import {saveTopics} from '../packages/domain/src/topics';
import {scoreCriteria} from '../packages/domain/src/ai-workflows';
import {lockPaths,preserveLocks} from '../packages/domain/src/briefs';
let env:Awaited<ReturnType<typeof server>>,client:Client,me:any,account:any;
before(async()=>{env=await server();client=new Client(env.url);me=await initialize(client);account=(await client.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'controlled-brief',name:'合成制作单测试'})).data;});after(()=>env.close());
const config:AIConfig={provider:'deepseek',base_url:'https://api.deepseek.com',model:'controlled',api_key:'controlled-not-real-key',enabled:true,allowed_data_types:'any_user_authorized',budget:{mode:'unlimited_user_authorized',per_task:null,daily:null},authorization_date:'2026-10-08',timeout_seconds:2,max_output_tokens:1000};
async function draft(kind='graphic',extra:any={}){
 const snapshot={account:{id:account.id,name:account.name,version:account.version},workspace_version:me.workspace.version,rule_set:null,rules:[],sources:[],assets:[]};const request=(await env.db.query("INSERT INTO ai_requests(workspace_id,account_id,created_by,kind,input_version,snapshot,state) VALUES($1,$2,$3,'topics',$4,$5,'succeeded') RETURNING *",[me.workspace.id,account.id,me.membership.id,randomUUID(),JSON.stringify(snapshot)])).rows[0];
 const candidate={title:'合成确认标题',audience:'已确认人群',need:'合成需要',scene:'测试',column:'观察',emotion:'好奇',media_type:kind,follow_reason:'已确认关注理由',evidence_refs:[],original_angle:'已确认目标',score_breakdown:scoreCriteria.map(criterion=>({criterion,score:4,reason:'合成'})),required_asset_ids:[],estimated_hours:null,expires_at:null,assumptions:['明确合成']};await env.db.transaction(tx=>saveTopics(tx,request,{schema_version:'ai-v1',input_version:request.input_version,summary:'',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate]}}));
 const topic=(await env.db.query('SELECT id FROM topics WHERE generation_request_id=$1',[request.id])).rows[0];const accepted=await client.call('/topics/'+topic.id+'/accept','POST',{media_type:kind,expected_version:1});assert.equal(accepted.status,201);const c=await client.call('/contents/'+accepted.data.content_id);
 if(Object.keys(extra).length){const payload={...c.data.current_revision.payload,...extra};await env.db.query('UPDATE content_revisions SET payload=$2 WHERE id=$1',[c.data.current_revision.id,JSON.stringify(payload)]);await env.db.query("UPDATE jobs SET state='cancelled',cancel_requested=true WHERE id=$1",[accepted.data.brief_job_id]);}
 return (await client.call('/contents/'+accepted.data.content_id)).data;
}
function output(input:any,kind:string){return {schema_version:input.schema_version,input_version:input.input_version,summary:'合成生成结果',evidence_refs:[],assumptions:['合成测试'],missing_inputs:['缺实际素材'],warnings:[],task_payload:kind==='graphic'?{goal:'模型试图改变目标',audience:'模型试图改变人群',pages:[{position:1,visual_instruction:'可执行画面',page_copy:'可执行页文案',asset_version_ids:[]}],title_options:['模型标题'],body:'模型正文',interaction_question:'你的观察是什么',delivery_spec:'合成规格',fact_check_items:[]}:{target_duration_ms:15000,aspect_ratio:'9:16',shots:[{position:1,start_ms:0,end_ms:15000,action:'合成主镜头',subtitle:'合成字幕',voiceover_optional:null,sound_note:'不适用，无配音',asset_version_ids:[]}],cover_options:['合成封面'],title_options:['视频模型标题'],body:'视频正文',delivery_spec:'9:16'}};}
async function runBrief(kind:string,change?:()=>Promise<void>,assetVersionId?:string){const jobs=new Jobs(env.db,{'ai.generate':new AITasks(env.db,()=>new AIGateway(env.db,config,async messages=>{const input=JSON.parse(messages[1]!.content);await change?.();const result=output(input,kind);if(assetVersionId&&kind==='graphic')(result.task_payload as any).pages[0].asset_version_ids=[assetVersionId];return {content:JSON.stringify(result),usage:{input_tokens:10,output_tokens:20,total_tokens:30}};})).handler});await jobs.dispatch();const job=(await jobs.claim('general'))!;assert.ok(job);await jobs.process(job);return job;}
test('生成候选不覆盖当前草稿，已确认目标/人群保留；并发应用同一建议仅一版本',async()=>{
 const c=await draft();await runBrief('graphic');const pending=(await client.call('/contents/'+c.id)).data;assert.equal(pending.current_revision_id,c.current_revision_id);const result=pending.revisions.find((r:any)=>r.origin==='ai_candidate');assert.ok(result);assert.equal(result.frozen,true);assert.equal(result.payload.brief.goal,'已确认目标');assert.equal(result.payload.brief.audience,'已确认人群');
 const responses=await Promise.all([client.call('/contents/'+c.id+'/apply-generated','POST',{result_revision_id:result.id,expected_version:1}),client.call('/contents/'+c.id+'/apply-generated','POST',{result_revision_id:result.id,expected_version:1})]);assert.ok(responses.every(r=>r.status===200));assert.equal(responses[0]!.data.revision_id,responses[1]!.data.revision_id);assert.equal((await env.db.query("SELECT count(*)::int n FROM content_revisions WHERE source_revision_id=$1 AND origin='applied_ai'",[result.id])).rows[0].n,1);await assert.rejects(env.db.query("UPDATE content_revisions SET payload='{}' WHERE id=$1",[result.id]));await assert.rejects(env.db.query('UPDATE content_revisions SET version=version+1 WHERE id=$1',[result.id]));
});
test('人工锁定标题/正文优先，生成回填不得修改；危险/缺失路径拒绝',async()=>{
 const c=await draft('graphic',{title:'人工标题',body:'人工正文',locked_fields:['title','body']});
 const accepted=await client.call('/contents/'+c.id+'/generate-brief','POST',{base_revision_id:c.current_revision_id,preserve_fields:['title','body']});assert.equal(accepted.status,202);await runBrief('graphic');const result=(await client.call('/contents/'+c.id)).data.revisions.find((r:any)=>r.origin==='ai_candidate');assert.equal(result.payload.title,'人工标题');assert.equal(result.payload.body,'人工正文');
 assert.throws(()=>lockPaths(['/__proto__/polluted'],c.current_revision.payload));assert.throws(()=>lockPaths(['/brief/missing'],c.current_revision.payload));assert.throws(()=>preserveLocks({pages:[]},{pages:[{page_copy:'人工'}]},['/pages/0/page_copy']));
});
test('人工修改后拒绝迟到生成；已产生候选在应用前过期也拒绝',async()=>{
 const c=await draft();await runBrief('graphic',async()=>{await env.db.query('UPDATE contents SET version=version+1 WHERE id=$1',[c.id]);});const latest=(await client.call('/contents/'+c.id)).data;assert.equal(latest.revisions.filter((r:any)=>r.origin==='ai_candidate').length,0);assert.equal(latest.generation_requests[0].error_code,'STALE_INPUT');
 const second=await draft();await runBrief('graphic');const before=(await client.call('/contents/'+second.id)).data,result=before.revisions.find((r:any)=>r.origin==='ai_candidate');await env.db.query('UPDATE contents SET version=version+1 WHERE id=$1',[second.id]);assert.equal((await client.call('/contents/'+second.id+'/apply-generated','POST',{result_revision_id:result.id,expected_version:2})).error.code,'BASE_REVISION_STALE');
});
test('连续视频分镜、无配音说明与时长保留；跨内容候选不能应用',async()=>{
 const video=await draft('video');await runBrief('video');const result=(await client.call('/contents/'+video.id)).data.revisions.find((r:any)=>r.origin==='ai_candidate');assert.equal(result.payload.shots[0].voiceover,null);assert.equal(result.payload.shots[0].end_ms,15000);const other=await draft();assert.equal((await client.call('/contents/'+other.id+'/apply-generated','POST',{result_revision_id:result.id,expected_version:1})).status,404);await env.db.query("UPDATE jobs SET state='cancelled',cancel_requested=true WHERE state='queued'");
});
test('真实上传PNG版本引用随应用事务落库，停用素材后不得采用已生成候选',async()=>{
 const {png,uploadBytes}=await import('./s2-helpers');const {Storage}=await import('../packages/domain/src/storage');const {mediaHandler}=await import('../packages/domain/src/media');const store=new Storage();await store.init();
 try{const file=await uploadBytes(client,env.url,png(),'制作单素材.png');const mediaJobs=new Jobs(env.db,{'media.preview':mediaHandler(env.db,store)});await mediaJobs.dispatch();const media=(await mediaJobs.claim('media'))!;assert.ok(media);await mediaJobs.process(media);assert.equal((await env.db.query('SELECT preview_status FROM file_objects WHERE id=$1',[file.id])).rows[0].preview_status,'ready');
 const created=await client.call('/assets','POST',{owner_id:me.membership.id,name:'明确合成PNG素材',category:'2d',source_file_id:file.id,ip_identity:'YOYO',source:'合成测试文件，不用于公开发布'});assert.equal(created.status,201);let asset=created.data;asset=(await client.call('/assets/'+asset.id+'/confirm','POST',{expected_version:asset.version,usage_scope:'仅测试',checklist:['测试'] })).data;const version=asset.current_version_id;
 const content=await draft('graphic',{body:'人工基线'});await client.call('/contents/'+content.id+'/generate-brief','POST',{base_revision_id:content.current_revision_id,preserve_fields:[]});await runBrief('graphic',undefined,version);const candidate=(await client.call('/contents/'+content.id)).data.revisions.find((r:any)=>r.origin==='ai_candidate');assert.ok(candidate);assert.equal((await client.call('/contents/'+content.id+'/apply-generated','POST',{result_revision_id:candidate.id,expected_version:1})).status,200);assert.equal((await client.call('/assets/'+asset.id+'/usages')).data.items.length,1);
 const next=await draft('graphic',{body:'另一基线'});await client.call('/contents/'+next.id+'/generate-brief','POST',{base_revision_id:next.current_revision_id,preserve_fields:[]});await runBrief('graphic',undefined,version);const blocked=(await client.call('/contents/'+next.id)).data.revisions.find((r:any)=>r.origin==='ai_candidate');await client.call('/assets/'+asset.id+'/retire','POST',{expected_version:asset.version,reason:'受控停用'});assert.equal((await client.call('/contents/'+next.id+'/apply-generated','POST',{result_revision_id:blocked.id,expected_version:1})).error.code,'ASSET_UNUSABLE');assert.equal((await client.call('/contents/'+next.id)).data.current_revision_id,next.current_revision_id);
 }finally{store.destroy();}
});
