import {test} from 'node:test';
import {GetObjectCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Client,server,initialize} from './helpers';
import {Storage} from '../packages/domain/src/storage';
import {Jobs} from '../packages/domain/src/jobs';
import {fileValidationHandler} from '../packages/domain/src/media';
import {uploadBytes,png,hash} from './file-helpers';
async function setup(){const env=await server(),c=new Client(env.url),me=await initialize(c),account=(await c.call('/accounts','POST',{name:'明确合成导入账号',platform:'xiaohongshu',platform_user_id:'file-test'})).data,store=new Storage();await store.init();return {env,c,me,account,store};}
async function validate(s:Awaited<ReturnType<typeof setup>>){const jobs=new Jobs(s.env.db,{'file.validate':fileValidationHandler(s.env.db,s.store)});await jobs.dispatch();let j;while((j=await jobs.claim('media')))await jobs.process(j);}
test('导入PNG/CSV/XLSX通过真实隔离解析，哈希原件/私有签名与表格禁预览保留',async()=>{const s=await setup();try{const f=await uploadBytes(s.c,s.env.url,s.account.id,png());assert.equal((await s.c.call('/files/'+f.id+'/download')).status,409);await validate(s);const d=await s.c.call('/files/'+f.id+'/download');assert.equal(d.status,200);assert.equal(hash(Buffer.from(await(await fetch(d.data.url)).arrayBuffer())),f.sha256);const unsigned=new URL(d.data.url);unsigned.search='';assert.equal((await fetch(unsigned)).status,403);const tampered=new URL(d.data.url);tampered.searchParams.set('X-Amz-Signature','0'.repeat(64));assert.equal((await fetch(tampered)).status,403);const key=(await s.env.db.query('SELECT object_key FROM file_objects WHERE id=$1',[f.id])).rows[0].object_key;const expired=await getSignedUrl(s.store.publicClient,new GetObjectCommand({Bucket:s.store.bucket,Key:key}),{expiresIn:1,signingDate:new Date(Date.now()-5000)});assert.equal((await fetch(expired)).status,403);assert.equal((await s.c.call('/files/'+f.id+'/preview')).status,200);
 for(const [name,mime,bytes] of [['合成表.csv','text/csv',Buffer.from('metric_key,value\nread_count,100\n')],['合成表.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',readFileSync('tests/fixtures/import-valid.xlsx')]] as const){const table=await uploadBytes(s.c,s.env.url,s.account.id,bytes,name,'import_table',mime);await validate(s);assert.equal((await s.c.call('/files/'+table.id+'/download')).status,200);assert.equal((await s.c.call('/files/'+table.id+'/preview')).status,409);}
 }finally{await s.env.close();s.store.destroy();}});
test('账号/目的隔离、角色矩阵、旧用途和旧文件ID拒绝，hash不跨账号复用',async()=>{const s=await setup();try{const f=await uploadBytes(s.c,s.env.url,s.account.id,png());await validate(s);const other=(await s.c.call('/accounts','POST',{name:'其他授权账号',platform:'xiaohongshu',platform_user_id:'other'})).data;const second=await uploadBytes(s.c,s.env.url,other.id,png());assert.notEqual(second.id,f.id);for(const purpose of ['asset','guideline','publish_image','campaign_evidence'])assert.equal((await s.c.call('/uploads','POST',{account_id:s.account.id,name:'x.png',size_bytes:10,mime_hint:'image/png',purpose})).status,422);assert.equal((await s.c.call('/uploads','POST',{name:'x.png',size_bytes:10,mime_hint:'image/png',purpose:'import_screenshot'})).status,422);
 for(const role of ['viewer','editor']){await s.env.db.query('UPDATE memberships SET roles=$2 WHERE id=$1',[s.me.membership.id,[role]]);assert.equal((await s.c.call('/files/'+f.id+'/download')).status,403);assert.equal((await s.c.call('/files/'+f.id+'/preview')).status,200);assert.equal((await s.c.call('/uploads','POST',{})).status,403);}
 await s.env.db.query("UPDATE memberships SET roles=ARRAY['operator'] WHERE id=$1",[s.me.membership.id]);await s.env.db.query('DELETE FROM account_memberships WHERE membership_id=$1 AND account_id=$2',[s.me.membership.id,s.account.id]);assert.equal((await s.c.call('/files/'+f.id+'/preview')).status,404);assert.equal((await s.c.call('/files/'+f.id+'/download')).status,404);
 await s.env.db.query("UPDATE memberships SET roles=ARRAY['admin'] WHERE id=$1",[s.me.membership.id]);const foreign=(await s.env.db.query("INSERT INTO workspaces(name) VALUES('跨空间') RETURNING id")).rows[0].id;const {Files}=await import('../apps/api/src/files');const files=new Files(s.env.db);try{await assert.rejects(files.file(s.env.db,{workspaceId:foreign,memberId:s.me.membership.id,userId:s.me.user.id,roles:['admin'],sessionHash:'',requestId:randomUUID()},f.id));}finally{files.storage.destroy();}
 }finally{await s.env.close();s.store.destroy();}});
test('恶意PNG/公式CSV/宏或公式XLSX隔离，伪装/大小/MIME失败且不发签名',async()=>{const s=await setup();try{for(const [name,purpose,mime,bytes] of [['伪造.png','import_screenshot','image/png',Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0])],['公式.csv','import_table','text/csv',Buffer.from('name,value\nformula,=WEBSERVICE("https://example.invalid")\n')],['公式.xlsx','import_table','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',readFileSync('tests/fixtures/import-formula.xlsx')],['宏.xlsx','import_table','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',readFileSync('tests/fixtures/import-macro.xlsx')]] as const){const f=await uploadBytes(s.c,s.env.url,s.account.id,bytes,name,purpose,mime);await validate(s);assert.equal((await s.env.db.query('SELECT file_status FROM file_objects WHERE id=$1',[f.id])).rows[0].file_status,'quarantined');assert.equal((await s.c.call('/files/'+f.id+'/download')).status,409);}
 for(const body of [{name:'bad.svg',mime_hint:'image/svg+xml',size_bytes:1},{name:'big.png',mime_hint:'image/png',size_bytes:20971521},{name:'fake.png',mime_hint:'application/pdf',size_bytes:1}])assert.equal((await s.c.call('/uploads','POST',{account_id:s.account.id,purpose:'import_screenshot',...body})).status,422);
 }finally{await s.env.close();s.store.destroy();}});
test('续传分片/登录恢复/幂等/校验/取消/过期保留，未完成文件不能下载',async()=>{const s=await setup();try{const bytes=Buffer.from('synthetic,csv\nvalue,1\n'),u=(await s.c.call('/uploads','POST',{account_id:s.account.id,name:'续传.csv',size_bytes:bytes.length,mime_hint:'text/csv',purpose:'import_table',sha256:hash(bytes)})).data,p=(await s.c.call('/uploads/'+u.id+'/parts','POST',{part_number:1,checksum:hash(bytes)})).data;await s.c.login('admin@example.test');const headers={'Content-Type':'application/octet-stream',Cookie:s.c.cookie,Origin:'http://localhost:3000','X-CSRF-Token':s.c.csrf};assert.equal((await fetch(s.env.url+p.upload_url,{method:'PUT',headers,body:Buffer.from('bad')})).status,422);const put=await fetch(s.env.url+p.upload_url,{method:'PUT',headers,body:bytes});assert.equal(put.status,200);const part=(await put.json()).data;assert.deepEqual((await(await fetch(s.env.url+p.upload_url,{method:'PUT',headers,body:bytes})).json()).data,part);assert.equal((await s.c.call('/uploads/'+u.id)).data.completed_parts.length,1);assert.equal((await s.c.call('/uploads/'+u.id+'/parts','POST',{part_number:1,checksum:hash(Buffer.from('bad'))})).status,409);assert.equal((await s.c.call('/uploads/'+u.id+'/complete','POST',{parts_manifest:[]})).status,422);const done=await s.c.call('/uploads/'+u.id+'/complete','POST',{parts_manifest:[part]});assert.equal(done.status,200);assert.equal((await s.c.call('/uploads/'+u.id+'/complete','POST',{parts_manifest:[part]})).data.id,done.data.id);
 const bad=(await s.c.call('/uploads','POST',{account_id:s.account.id,name:'原件哈希错误.csv',size_bytes:bytes.length,mime_hint:'text/csv',purpose:'import_table',sha256:hash(Buffer.from('wrong-original'))})).data;const target=(await s.c.call('/uploads/'+bad.id+'/parts','POST',{part_number:1,checksum:hash(bytes)})).data;const written=await fetch(s.env.url+target.upload_url,{method:'PUT',headers,body:bytes});const badPart=(await written.json()).data;assert.equal((await s.c.call('/uploads/'+bad.id+'/complete','POST',{parts_manifest:[badPart]})).error.code,'FILE_CHECKSUM_INVALID');assert.equal((await s.c.call('/uploads/'+bad.id+'/abort','POST',{reason:'清理测试错误原件'})).status,200);
 const expired=(await s.c.call('/uploads','POST',{account_id:s.account.id,name:'过期.csv',size_bytes:1,mime_hint:'text/csv',purpose:'import_table'})).data;await s.env.db.query("UPDATE upload_sessions SET expires_at=now()-interval '1 second' WHERE id=$1",[expired.id]);const {Files}=await import('../apps/api/src/files');const files=new Files(s.env.db);try{await files.expire();assert.equal((await s.c.call('/uploads/'+expired.id)).data.status,'expired');}finally{files.storage.destroy();}
 const aborted=(await s.c.call('/uploads','POST',{account_id:s.account.id,name:'取消.csv',size_bytes:1,mime_hint:'text/csv',purpose:'import_table'})).data;assert.equal((await s.c.call('/uploads/'+aborted.id+'/abort','POST',{reason:'取消测试'})).data.status,'aborted');
 }finally{await s.env.close();s.store.destroy();}});
test('两分片CSV续传与同目的去重、撤销权限阻止解析提交',async()=>{
 const s=await setup();try{
 const bytes=Buffer.from('text,value\n'+('x'.repeat(200)+',1\n').repeat(45000));const f=await uploadBytes(s.c,s.env.url,s.account.id,bytes,'多分片.csv','import_table','text/csv');
 const duplicate=await uploadBytes(s.c,s.env.url,s.account.id,bytes,'再次上传.csv','import_table','text/csv');assert.equal(duplicate.id,f.id);assert.equal((await s.env.db.query('SELECT parts FROM upload_sessions ORDER BY created_at LIMIT 1')).rows[0].parts['2'].etag.length>0,true);await validate(s);assert.equal((await s.c.call('/files/'+f.id+'/download')).status,200);
 const image=await uploadBytes(s.c,s.env.url,s.account.id,png(),'权限竞争.png');const handler=fileValidationHandler(s.env.db,s.store);const jobs=new Jobs(s.env.db,{'file.validate':async(j,signal)=>{const result=await handler(j,signal);await s.env.db.query("UPDATE memberships SET roles=ARRAY['viewer'] WHERE id=$1",[s.me.membership.id]);return result;}});await jobs.dispatch();await jobs.process((await jobs.claim('media'))!);assert.equal((await s.env.db.query("SELECT error_code FROM jobs WHERE input->>'file_id'=$1",[image.id])).rows[0].error_code,'FILE_SCOPE_CHANGED');assert.equal((await s.env.db.query('SELECT file_status FROM file_objects WHERE id=$1',[image.id])).rows[0].file_status,'uploading');assert.equal((await s.c.call('/files/'+image.id+'/preview')).status,409);
 }finally{await s.env.close();s.store.destroy();}
});
