import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {computeMetrics,roundRatio} from '../packages/domain/src/metrics';
import {normalizeMetric} from '../packages/domain/src/imports';
const account=randomUUID(),p=randomUUID(),p2=randomUUID(),start='2026-09-01T00:00:00.000Z',end='2026-10-01T00:00:00.000Z';
function observation(key:string,value:string|null,pid:string|null=p,extra:Record<string,any>={}){return {id:randomUUID(),metric:normalizeMetric({target:{account_id:account,publication_id:pid},metric_key:key,definition_version:'1',aggregation_kind:key==='followers'?'snapshot':'interval',value,unit:['followers','attributed_follows','new_followers','unfollows'].includes(key)?'人':key==='average_watch_seconds'?'秒':key==='completion_rate'?'%':'次',window_start:start,window_end:end,observed_at:end,traffic_type:'organic',is_approximate:false,source_definition:'合成平台相同口径v1',time_precision:'day',missing_reason:value===null?'后台未提供':null,...extra})};}
const results=(obs:any[])=>computeMetrics(obs,start,end),find=(r:any[],key:string,pid:string|null=p)=>r.find(r=>r.metric_key===key&&r.publication_id===pid);
test('12金标准：600→631净增31，631单快照缺期初，不反推新增关注',()=>{const a=observation('followers','600',null,{observed_at:start}),b=observation('followers','631',null);const r=results([a,b]);assert.equal(find(r,'net_followers',null).value,'31');assert.deepEqual(find(r,'net_followers',null).input_observation_ids,[a.id,b.id].sort());assert.ok(!r.some(r=>r.metric_key==='new_followers'));const missing=find(results([b]),'net_followers',null);assert.equal(missing.value,null);assert.match(missing.missing_reason,/缺期初/);assert.equal(find(results([a,observation('followers','590',null)]),'net_followers',null).value,'-10');});
test('12金标准：12/3000*1000=4，零分母与缺失分开；组合字段不拆，互动次数率可>100%',()=>{const a=observation('attributed_follows','12'),b=observation('reads','3000');assert.equal(find(results([a,b]),'follows_per_1000_reads').value,'4.00');const zero=find(results([a,observation('reads','0')]),'follows_per_1000_reads');assert.equal(zero.value,null);assert.equal(zero.missing_reason,'零分母');const missing=find(results([a]),'follows_per_1000_reads');assert.equal(missing.value,null);assert.match(missing.missing_reason,/数据缺失/);assert.match(find(results([a,observation('reads',null)]),'follows_per_1000_reads').missing_reason,/后台未提供/);assert.equal(find(results([observation('likes_saves_combined','1579')]),'interaction_count_rate').value,null);const high=results([observation('reads','10'),...['likes','saves','comments','shares'].map(k=>observation(k,'10'))]);assert.equal(find(high,'interaction_count_rate').value,'400.00');});
test('12金标准：累计100→150区间增量50不求和；回落100→90待核实',()=>{const first=observation('likes','100',p,{aggregation_kind:'cumulative',observed_at:start}),last=observation('likes','150',p,{aggregation_kind:'cumulative',observed_at:end});assert.equal(find(results([first,last]),'likes_interval_delta').value,'50');const decline=find(results([first,{...last,metric:{...last.metric,value:'90'}}]),'likes_interval_delta');assert.equal(decline.value,null);assert.match(decline.missing_reason,/回落/);});
test('12金标准：观看10秒×100与20秒×300加权17.5；缺权重不能平均；零权重为空',()=>{const a=observation('average_watch_seconds','10'),b=observation('average_watch_seconds','20',p2),w1=observation('watch_count','100'),w2=observation('watch_count','300',p2);assert.equal(find(results([a,b,w1,w2]),'weighted_average_watch_seconds',null).value,'17.50');assert.equal(find(results([a,b,w1]),'weighted_average_watch_seconds',null).value,null);assert.equal(find(results([a,observation('watch_count','0')]),'weighted_average_watch_seconds',null).missing_reason,'零分母');});
test('12金标准：约数保留，日期不同流量/平台口径/精度不混算；边界缺失或重复不可比较',()=>{const a=observation('reads','1.2 万'),b=observation('attributed_follows','12');assert.equal(a.metric.value,'12000');assert.equal(a.metric.is_approximate,true);assert.equal(find(results([a,b]),'follows_per_1000_reads').is_approximate,true);for(const extra of [{traffic_type:'mixed'},{source_definition:'另一平台定义'},{time_precision:'minute'}]){const separated=results([a,{...b,metric:{...b.metric,...extra}}]);assert.ok(separated.filter(r=>r.metric_key==='follows_per_1000_reads').every(r=>r.value===null));}const partial={...a,metric:{...a.metric,window_end:'2026-09-30T00:00:00.000Z'}};assert.equal(find(results([partial,b]),'follows_per_1000_reads').value,null);assert.match(find(results([a,a,b]),'follows_per_1000_reads').missing_reason,/多个可用值/);});
test('精确十进制内部不提前舍入，half-up正负边界',()=>{assert.equal(roundRatio(1n,3n),'0.33');assert.equal(roundRatio(1n,8n),'0.13');assert.equal(roundRatio(-1n,8n),'-0.13');assert.equal(roundRatio(123456789012345678901n,1000000n,2),'123456789012345.68');assert.throws(()=>roundRatio(1n,0n));assert.equal(observation('reads','999999999999999999').metric.value,'999999999999999999');assert.throws(()=>observation('reads','1000000000000000000'),/值超限/);const overflow=find(results([observation('reads','1'),...['likes','saves','comments','shares'].map(k=>observation(k,'999999999999999999'))]),'interaction_count_rate');assert.equal(overflow.value,null);assert.match(overflow.missing_reason,/超出存储范围/);});
