import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {server,Client,initialize,adminInput} from './helpers';
import {AIGateway} from '../packages/domain/src/ai-gateway';
import {ReportTasks} from '../packages/domain/src/reports';
import {Jobs} from '../packages/domain/src/jobs';
import {reportTestConfig,reportTestResponse} from './report-fixtures';
let env:Awaited<ReturnType<typeof server>>,c:Client,me:any,a:any,op:any,v:any,old:string|undefined,dir:string;
before(async()=>{dir=mkdtempSync(tmpdir()+'/yoyo-ops-');writeFileSync(dir+'/config.json',JSON.stringify(reportTestConfig),{mode:0o600});old=process.env.AI_CONFIG_FILE;process.env.AI_CONFIG_FILE=dir+'/config.json';env=await server();c=new Client(env.url);me=await initialize(c);a=(await c.call('/accounts','POST',{name:'合成运行账号',platform:'xiaohongshu',platform_user_id:'ops-synthetic'})).data;op=(await c.call('/members','POST',{email:'s8-op@example.test',roles:['operator']})).data;v=(await c.call('/members','POST',{email:'s8-viewer@example.test',roles:['viewer']})).data;});
after(async()=>{await env.close();if(old===undefined)delete process.env.AI_CONFIG_FILE;else process.env.AI_CONFIG_FILE=old;rmSync(dir,{recursive:true});});
async function setting(settings:any){const current=(await c.call('/settings')).data;return c.call('/settings','PATCH',{category:'ai_budget',settings,expected_version:current.version});}
test('运营角色降级/停用须移交账号/选题/来源，接替人须有能力，审计和通知同事务',async()=>{const second=(await c.call('/members','POST',{email:'second-admin@example.test',roles:['admin']})).data;const source=(await c.call('/source-connections','POST',{name:'移交来源',platform:'weibo',source_type:'weibo_hot',provider:'weibo_web',config:{keywords:['旅行']}})).data;await env.db.query('UPDATE accounts SET owner_id=$1 WHERE id=$2',[op.id,a.id]);await env.db.query('UPDATE source_connections SET owner_id=$1 WHERE id=$2',[op.id,source.id]);assert.equal((await c.call('/members/'+op.id,'PATCH',{roles:['viewer'],expected_version:1})).error.code,'SUCCESSOR_REQUIRED');assert.equal((await c.call('/members/'+op.id,'PATCH',{roles:['viewer'],successor_id:v.id,expected_version:1})).error.code,'SUCCESSOR_INVALID');const done=await c.call('/members/'+op.id,'PATCH',{roles:['viewer'],successor_id:me.membership.id,expected_version:1});assert.equal(done.status,200);assert.equal((await c.call('/accounts/'+a.id)).data.owner_id,me.membership.id);assert.equal((await c.call('/source-connections/'+source.id)).data.owner_id,me.membership.id);const notices=(await c.call('/notifications')).data.items;assert.ok(notices.some((n:any)=>n.task_ref==='account:'+a.id));assert.ok(notices.some((n:any)=>n.task_ref==='source:'+source.id));assert.equal((await c.call('/accounts/'+a.id,'PATCH',{owner_id:v.id,expected_version:(await c.call('/accounts/'+a.id)).data.version})).status,422);await c.call('/members/'+second.id,'PATCH',{active:false,expected_version:1});assert.equal((await c.call('/members/'+me.membership.id,'PATCH',{active:false,expected_version:1,successor_id:v.id})).error.code,'LAST_ADMIN');});
test('有限预算必须有单价币种，工作区配置在AI运行前真实拒绝超额且不触发提供方',async()=>{assert.equal((await setting({budget:{mode:'limited',per_task:1,daily:1}})).status,422);const rate={currency:'CNY',version:'explicit-test-only-not-real-rate',input_per_million:10,output_per_million:10};assert.equal((await setting({budget:{mode:'limited',per_task:0,daily:0},pricing:rate})).status,200);const q=(await c.call('/reports','POST',{account_id:a.id,start:'2026-09-01T00:00:00.000Z',end:'2026-09-08T00:00:00.000Z'})).data;let calls=0;const jobs=new Jobs(env.db,{'report.generate':new ReportTasks(env.db,()=>new AIGateway(env.db,reportTestConfig,async m=>{calls++;return {content:JSON.stringify(reportTestResponse(JSON.parse(m[1]!.content))),usage:{input_tokens:10,output_tokens:20,total_tokens:30}};})).handler});await jobs.dispatch();const job=(await jobs.claim('general'))!;await jobs.process(job);assert.equal(calls,0);assert.equal((await c.call('/reports/'+q.report_id)).data.error_code,'AI_BUDGET_EXCEEDED');const monitor=(await c.call('/monitor')).data;assert.equal(monitor.external_capabilities.ai.budget.daily,0);assert.equal(monitor.external_capabilities.ai.pricing.currency,'CNY');assert.deepEqual(monitor.ai_usage.groups,[]);assert.ok(!JSON.stringify(monitor).includes(reportTestConfig.api_key));assert.equal((await setting({budget:{mode:'unlimited_user_authorized',per_task:null,daily:null}})).status,200);const newer=(await c.call('/reports','POST',{account_id:a.id,start:'2026-09-01T00:00:00.000Z',end:'2026-09-08T00:00:00.000Z'})).data;await jobs.dispatch();await jobs.process((await jobs.claim('general'))!);assert.equal(calls,1);assert.equal((await c.call('/reports/'+newer.report_id)).data.state,'succeeded');const real=(await c.call('/monitor')).data;assert.equal(real.ai_usage.groups[0].total_tokens,'30');assert.equal(real.ai_usage.groups[0].estimated_cost,null);assert.equal(real.ai_usage.groups[0].cost_basis,'unknown');assert.equal(real.import_limits.table_bytes,50*1024*1024);});
test('失败任务管理员重试可运行，通知已读独立、运行入口与审计分页可用；只读不能操作',async()=>{const d=(await c.call('/diagnostics','POST',{pool:'general'})).data;await env.db.query("UPDATE jobs SET state='failed',error_code='TEST_FAILURE',finished_at=now() WHERE id=$1",[d.job_id]);const viewer=new Client(env.url);await viewer.init();await viewer.call('/auth/accept-invite','POST',{invitation_token:v.invitation_token,password:adminInput.password});await viewer.login('s8-viewer@example.test');assert.equal((await viewer.call('/monitor')).status,403);assert.equal((await viewer.call('/jobs/'+d.job_id+'/retry','POST',{reason:'越权'})).status,403);assert.equal((await c.call('/jobs/'+d.job_id+'/retry','POST',{reason:'核对故障后重试'})).status,202);const jobs=new Jobs(env.db);await jobs.dispatch();await jobs.process((await jobs.claim('general'))!);assert.equal((await c.call('/jobs/'+d.job_id)).data.state,'succeeded');const n=(await c.call('/notifications')).data.items.find((n:any)=>n.job_id===d.job_id);assert.ok(n);await c.call('/notifications/'+n.id+'/read','POST');assert.equal((await c.call('/jobs/'+d.job_id)).data.state,'succeeded');const audit=(await c.call('/audit-logs?limit=1')).data;assert.equal(audit.items.length,1);assert.ok(audit.next_cursor);});
