import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
test.describe.configure({mode:'serial'});
test('图文人工新建、逐页保存排序、刷新恢复与历史快照比较',async({page})=>{
 const failures:string[]=[];page.on('pageerror',e=>failures.push(e.message));
 await page.goto('/');const credentials=JSON.parse(readFileSync((process.env.STATE_DIR??'.local/state')+'/instance.json','utf8'));
 await page.getByLabel('实例初始化凭据').fill(credentials.setup_token);await page.getByLabel('工作区名称').fill('S4隔离浏览器验收');await page.getByLabel('你的名字').fill('S4验收者');await page.getByLabel('邮箱').fill('s4-browser@example.test');await page.getByLabel('密码',{exact:false}).fill('Browser-test-password-987');await page.getByRole('button',{name:'创建并进入'}).click();
 await page.getByRole('link',{name:'工作区设置'}).click();await page.getByRole('button',{name:'运营账号',exact:true}).click();await page.getByRole('button',{name:'添加账号',exact:true}).click();await page.getByLabel('平台内部账号 ID').fill('sandbox-s4-browser');await page.getByLabel('名称',{exact:false}).fill('沙盒验收账号');await page.getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('link',{name:'内容工作间'}).click();await page.getByRole('button',{name:'新建图文',exact:true}).click();await page.getByLabel('图文标题').fill('浏览器人工图文');await page.getByRole('button',{name:'创建图文草稿',exact:true}).click();
 await page.getByRole('button',{name:'编辑图文',exact:true}).click();await page.getByLabel('发布正文').fill('人工设计稿正文');await page.getByRole('button',{name:'添加图文页',exact:true}).click();await page.getByLabel('第1页画面').fill('封面');await page.getByLabel('第1页文案').fill('第一页');await page.getByRole('button',{name:'添加图文页',exact:true}).click();await page.getByLabel('第2页文案').fill('第二页');await page.getByRole('button',{name:'第2页上移',exact:true}).click();const handle=page.getByText('拖动第1页排序',{exact:true});await expect(handle).toHaveAttribute('draggable','true');await handle.hover();const box=await handle.boundingBox();await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+12,box!.y+box!.height/2,{steps:4});await page.getByText('拖动第2页排序',{exact:true}).hover();await page.getByText('拖动第2页排序',{exact:true}).hover();await page.mouse.up();await expect(page.getByLabel('第1页文案')).toHaveValue('第一页');await page.getByRole('button',{name:'第2页上移',exact:true}).click();await page.getByRole('button',{name:'保存新快照',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'图文快照已保存'})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'查看制作单与版本'}).click();await page.getByRole('button',{name:'编辑图文',exact:true}).click();await expect(page.getByLabel('发布正文')).toHaveValue('人工设计稿正文');await expect(page.getByLabel('第1页文案')).toHaveValue('第二页');
 mkdirSync('docs/evidence/s4/screenshots',{recursive:true});for(const width of [1440,1280,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/evidence/s4/screenshots/edit-${width}.png`});}
 expect(failures).toEqual([]);
});
test('逐页PNG成品上传预览、素材引用及未保存离开提示',async({page})=>{
 await page.goto('/');await page.getByLabel('邮箱').fill('s4-browser@example.test');await page.getByLabel('密码',{exact:false}).fill('Browser-test-password-987');await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('link',{name:'IP 资产库'}).click();await page.getByText('上传素材 / 新建文件夹',{exact:true}).click();await page.getByLabel('文件（单个最大 2 GiB，最多同时上传两个）').setInputFiles('tests/fixtures/transparent.png');await page.getByLabel('素材来源',{exact:false}).fill('S4合成素材测试');await page.getByRole('button',{name:'开始上传 / 续传'}).click();await expect(page.getByRole('heading',{name:'transparent.png',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'transparent.png',exact:false}).first().click();await page.getByText('上传新版本 / 配套预览',{exact:true}).click();await page.getByLabel('原件',{exact:true}).setInputFiles('tests/fixtures/transparent.png');await page.getByRole('button',{name:'建立新版本',exact:true}).click();await expect(page.getByText('新版本已保存，需重新确认使用范围。')).toBeVisible();await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await page.getByRole('link',{name:'内容工作间'}).click();await page.getByRole('button',{name:'查看制作单与版本'}).click();await page.getByRole('button',{name:'编辑图文',exact:true}).click();await page.getByLabel('第1页文案').fill('未保存草稿');
 page.once('dialog',d=>d.dismiss());await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(1);await expect(page.getByLabel('第1页文案')).toHaveValue('未保存草稿');
 page.once('dialog',d=>d.dismiss());await page.evaluate(()=>{location.hash='home';});await expect(page).toHaveURL(/#contents$/);await expect(page.getByLabel('第1页文案')).toHaveValue('未保存草稿');
 await page.getByLabel('上传第1页PNG成品').setInputFiles('tests/fixtures/transparent.png');await expect(page.getByText('第1页成品原件已上传')).toBeVisible();
 await page.getByRole('button',{name:'第1页添加素材引用'}).click();const picker=page.getByRole('dialog',{name:'选择素材',exact:true});await picker.getByRole('button',{name:'查看历史版本',exact:true}).click();await picker.getByRole('button',{name:'选择历史版本 1',exact:true}).click();await expect(page.getByText('使用范围待确认')).toBeVisible();await page.getByRole('button',{name:'保存新快照',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'图文快照已保存'})).toBeVisible();
 await expect(async()=>{await page.getByRole('button',{name:'刷新成品状态'}).click();await expect(page.getByRole('img',{name:'第1页成品'})).toBeVisible();}).toPass({timeout:20000});
 await expect.poll(()=>page.getByRole('img',{name:'第1页成品'}).evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);
});
test('人工上传成品后显式提交审核并逐项确认批准',async({page})=>{
 await page.goto('/');await page.getByLabel('邮箱').fill('s4-browser@example.test');await page.getByLabel('密码',{exact:false}).fill('Browser-test-password-987');await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('link',{name:'内容工作间'}).click();await page.getByRole('button',{name:'新建图文',exact:true}).click();await page.getByLabel('图文标题').fill('浏览器审核闭环');await page.getByRole('button',{name:'创建图文草稿',exact:true}).click();
 await page.getByRole('button',{name:'编辑图文',exact:true}).click();await page.getByLabel('发布正文').fill('人工核对后的公开正文');await page.getByRole('button',{name:'添加图文页',exact:true}).click();await page.getByLabel('第1页文案').fill('封面');await page.getByLabel('上传第1页PNG成品').setInputFiles('tests/fixtures/transparent.png');await expect(page.getByText('第1页成品原件已上传')).toBeVisible();await page.getByRole('button',{name:'保存新快照',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'图文快照已保存'})).toBeVisible();
 await expect(async()=>{await page.getByRole('button',{name:'刷新成品状态'}).click();await expect(page.getByRole('img',{name:'第1页成品'})).toBeVisible();}).toPass({timeout:20000});
 await page.getByRole('button',{name:'提交内部审核',exact:true}).click();await expect(page.getByRole('heading',{name:'图文制作 · 内部审核中'})).toBeVisible();
 await page.getByLabel('已核对图片原件与页序').check();await page.getByLabel('已核对公开文案与素材许可').check();await page.getByLabel('审核意见').fill('隔离演练显式自审');await page.getByRole('button',{name:'批准此冻结版本',exact:true}).click();await expect(page.getByRole('heading',{name:'图文制作 · 待发布'})).toBeVisible();
 await page.getByRole('button',{name:'生成批准版本发布包',exact:true}).click();await expect(page.getByRole('button',{name:'下载批准版本发布包',exact:true})).toBeEnabled({timeout:20000});
 await page.getByLabel('平台笔记ID').fill('sandbox-browser-s4');await page.getByLabel('实际发布链接').fill('https://www.xiaohongshu.com/explore/sandbox-browser-s4');await page.getByLabel('实际发布时间').fill('2026-10-08T18:00');await page.getByLabel('发布核对说明').fill('隔离沙盒登记演练');
 await page.getByRole('button',{name:'暂存待核对发布信息',exact:true}).click();await expect(page.getByText('发布信息已暂存，尚未登记发布')).toBeVisible();await expect(page.getByRole('heading',{name:'图文制作 · 待发布'})).toBeVisible();
 await page.getByLabel('已人工核对平台账号、笔记ID及批准成品').check();await page.getByRole('button',{name:'登记实际发布',exact:true}).click();await expect(page.getByRole('heading',{name:'图文制作 · 已发布'})).toBeVisible();
});
