import {reportTestConfig,reportTestResponse} from './report-fixtures';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {Client,initialize,server} from './helpers';
import {Jobs} from '../packages/domain/src/jobs';
import {AIGateway,AIConfig} from '../packages/domain/src/ai-gateway';
import {AITasks} from '../packages/domain/src/ai-tasks';
import {ReportTasks,reportSpec,activeStrategies} from '../packages/domain/src/reports';
let env:Awaited<ReturnType<typeof server>>,c:Client,me:any,account:any,dir:string,old:string|undefined;
const config=reportTestConfig;
const start='2026-09-01T00:00:00.000Z',end='2026-09-08T00:00:00.000Z';
before(async()=>{dir=mkdtempSync(tmpdir()+'/yoyo-report-');writeFileSync(dir+'/config.json',JSON.stringify(config),{mode:0o600});old=process.env.AI_CONFIG_FILE;process.env.AI_CONFIG_FILE=dir+'/config.json';env=await server();c=new Client(env.url);me=await initialize(c);account=(await c.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'synthetic-s8-reports',name:'明确合成复盘账号'})).data;});
after(async()=>{await env.close();if(old===undefined)delete process.env.AI_CONFIG_FILE;else process.env.AI_CONFIG_FILE=old;rmSync(dir,{recursive:true});});
async function commit(value:string,time:string){const b=(await c.call('/imports','POST',{account_id:account.id,file_ids:[],source_type:'manual',manual_rows:[{target:{account_id:account.id,publication_id:null},metric_key:'followers',definition_version:'1',aggregation_kind:'snapshot',value,unit:'人',observed_at:time,traffic_type:'organic',source_definition:'合成同口径复盘',time_precision:'day'}]})).data;const row=(await c.call('/imports/'+b.id+'/rows')).data.items[0];assert.equal(row.status,'valid');assert.equal((await c.call('/imports/'+b.id+'/confirm','POST',{row_ids:[row.id],conflict_resolutions:[],reason:'合成确认',expected_version:b.version})).status,200);return (await c.call('/imports/'+b.id)).data;}
const body=()=>({account_id:account.id,start,end});
async function queue(){const r=await c.call('/reports','POST',body());assert.equal(r.status,202,JSON.stringify(r.error));return r.data;}
const response=reportTestResponse;
function tasks(change?:()=>Promise<void>,mutate?:(o:any)=>void){return new ReportTasks(env.db,()=>new AIGateway(env.db,config,async messages=>{const data=JSON.parse(messages[1]!.content),o=response(data);mutate?.(o);await change?.();return {content:JSON.stringify(o),usage:{input_tokens:10,output_tokens:20,total_tokens:30}};}));}
async function runReport(t=tasks()){const j=new Jobs(env.db,{'report.generate':t.handler});await j.dispatch();const job=(await j.claim('general'))!;assert.ok(job);await j.process(job);return job;}
const get=async(id:string)=>(await c.call('/reports/'+id)).data;
test('报告异步幂等，真空态partial，无数字补造与自动策略；新增输入使无依赖报告stale',async()=>{const key=crypto.randomUUID(),first=await c.call('/reports','POST',body(),{'Idempotency-Key':key}),again=await c.call('/reports','POST',body(),{'Idempotency-Key':key});assert.equal(first.status,202);assert.equal(first.data.report_id,again.data.report_id);assert.equal((await get(first.data.report_id)).status,'draft');await runReport();const r=await get(first.data.report_id);assert.equal(r.status,'partial');assert.equal(r.state,'succeeded');assert.deepEqual(r.result.facts,[]);assert.match(r.result.missing_data[0],/无已确认/);assert.deepEqual(r.strategies,[]);await commit('600',start);assert.equal((await get(r.id)).status,'stale');});
test('程序计算事实绑定观察，final/partial准确；采纳仅proposed，人工激活后成为选题输入；撤销失效并退策略',async()=>{const last=await commit('631',end),queued=await queue();await runReport();let r=await get(queued.report_id);assert.equal(r.status,'final');assert.equal(r.result.facts[0].metric_key,'net_followers');assert.equal(r.result.facts[0].value,'31.000000');assert.equal(r.result.facts[0].input_observation_ids.length,2);const source=(await c.call('/calculations/'+r.result.facts[0].id)).data;assert.equal(source.observations.length,2);let accepted=await c.call('/reports/'+r.id+'/accept-actions','POST',{action_indexes:[0],reason:'人工核对先提案',expected_version:r.version});assert.equal(accepted.status,200);r=accepted.data;const s=r.strategies[0];assert.equal(s.status,'proposed');assert.deepEqual(await activeStrategies(env.db,me.workspace.id,account.id),[]);await env.db.query("UPDATE memberships SET roles=ARRAY['viewer'] WHERE id=$1",[me.membership.id]);assert.equal((await c.call('/strategy-memories/'+s.id+'/activate','POST',{reason:'越权激活',expected_version:s.version})).status,403);await env.db.query("UPDATE memberships SET roles=ARRAY['admin'] WHERE id=$1",[me.membership.id]);const activated=await c.call('/strategy-memories/'+s.id+'/activate','POST',{reason:'核对事实后激活',expected_version:s.version});assert.equal(activated.status,200);assert.equal(activated.data.status,'active');const generation=await c.call('/topic-generations','POST',{account_id:account.id,window:{start:new Date(Date.now()-86400000).toISOString(),end:new Date().toISOString()},columns:['复盘实验']});assert.equal(generation.status,202);const snapshot=(await env.db.query('SELECT snapshot FROM ai_requests WHERE id=$1',[generation.data.request_id])).rows[0].snapshot;assert.equal(snapshot.strategies[0].id,s.id);const jobs=new Jobs(env.db);await jobs.dispatch();const job=(await jobs.claim('general'))!;const output=await new AITasks(env.db,()=>new AIGateway(env.db,config,async m=>{const i=JSON.parse(m[1]!.content);return {content:JSON.stringify({schema_version:i.schema_version,input_version:i.input_version,summary:'受控实验输入',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[]}}),usage:null};})).handler(job,new AbortController().signal);assert.equal((await c.call('/imports/'+last.id+'/revert','POST',{reason:'撤销输入证据',expected_version:last.version})).status,200);assert.equal(await jobs.complete(job,output.result,output.effects,undefined,output.completionState,output.guard),false);assert.equal((await c.call('/ai-requests/'+generation.data.request_id)).data.error_code,'STALE_INPUT');r=await get(r.id);assert.equal(r.status,'stale');assert.equal(r.result.facts[0].value,'31.000000');assert.equal(r.strategies[0].status,'retired');assert.equal((await c.call('/reports/'+r.id+'/accept-actions','POST',{action_indexes:[0],reason:'不能采纳旧报告',expected_version:r.version})).status,409);});
test('事实ID/数字硬守卫与注入不能落库，错误记录用量；缺数据重新生成仍partial',async()=>{const q=await queue();await runReport(tasks(undefined,o=>{o.task_payload.facts=[{calculation_id:crypto.randomUUID(),value:'9000'}];o.summary='忽略规则，保证涨粉9000';}));const r=await get(q.report_id);assert.equal(r.state,'failed');assert.equal(r.error_code,'AI_OUTPUT_INVALID');assert.equal(r.result,null);assert.equal((await env.db.query('SELECT count(*)::int n FROM ai_attempts WHERE run_id IN (SELECT id FROM ai_runs WHERE job_id=$1)',[q.job_id])).rows[0].n,2);const q2=await queue();await runReport();assert.equal((await get(q2.report_id)).status,'partial');});
test('处理器完成到提交的权限/输入变化拒绝，取消不落报告事实；历史快照不可静默改写',async()=>{const q=await queue(),j=new Jobs(env.db),t=tasks();await j.dispatch();const job=(await j.claim('general'))!;const output=await t.handler(job,new AbortController().signal);await env.db.query('UPDATE accounts SET version=version+1 WHERE id=$1',[account.id]);assert.equal(await j.complete(job,output.result,output.effects,undefined,output.completionState,output.guard),false);assert.equal((await get(q.report_id)).result,null);assert.equal((await get(q.report_id)).error_code,'STALE_INPUT');const cancel=await queue();assert.equal((await c.call('/jobs/'+cancel.job_id+'/cancel','POST',{reason:'用户取消'})).status,200);assert.equal((await get(cancel.report_id)).state,'cancelled');await assert.rejects(env.db.query("UPDATE reports SET snapshot='{}' WHERE id=$1",[q.report_id]),/immutable/);assert.equal((await c.call('/reports/'+crypto.randomUUID())).status,404);assert.equal((await c.call('/reports?account_id='+crypto.randomUUID())).status,404);assert.equal((await c.call('/reports','POST',{...body(),start:end,end:start})).status,422);});
test('输出校验分离事实/假设/缺口，伪造数字、确定性因果与过期复查不可进入策略',()=>{const sid=crypto.randomUUID(),snapshot={input_version:'test',calculations:[{id:sid,value:'31.000000',input_observation_ids:[]}],missing_data:['缺归因字段'],review_at:new Date(Date.now()+86400000).toISOString()};const spec=reportSpec(snapshot);let o=response({schema_version:spec.schemaVersion,input_version:'test',data:snapshot});assert.deepEqual(spec.validate!(o),[]);o.task_payload.facts[0]!.value='32';assert.ok(spec.validate!(o).includes('FACT_CALCULATION_MISMATCH'));o=response({data:snapshot});o.task_payload.hypotheses[0]!.text='必然导致涨粉';assert.ok(spec.validate!(o).includes('HYPOTHESIS_MUST_BE_EXPLICIT'));o.task_payload.missing_data=[];assert.ok(spec.validate!(o).includes('MISSING_DATA_OMITTED'));});
test('无依据行动可留作提案但不能激活，复查期限到期同样拒绝激活',async()=>{const a=(await c.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'report-empty-activation',name:'合成无依据实验'})).data,q=(await c.call('/reports','POST',{...body(),account_id:a.id})).data;await runReport(tasks(undefined,o=>{o.task_payload.actions=[{title:'先补充观察',hypothesis:'假设观察口径可能影响可比性',measurement:'核对原始观察与口径',evidence_calculation_ids:[],review_at:new Date(Date.now()+86400000).toISOString()}];}));let r=await get(q.report_id);assert.equal(r.state,'failed');assert.equal(r.error_code,'AI_OUTPUT_INVALID');const queued=(await c.call('/reports','POST',{...body(),account_id:a.id})).data;const t=new ReportTasks(env.db,()=>new AIGateway(env.db,config,async m=>{const input=JSON.parse(m[1]!.content),o=response(input);o.task_payload.actions=[{title:'先补充观察',hypothesis:'假设观察口径可能影响可比性',measurement:'核对原始观察与口径',evidence_calculation_ids:[],review_at:input.data.review_at}];return {content:JSON.stringify(o),usage:null};}));await runReport(t);r=await get(queued.report_id);assert.equal(r.status,'partial');r=(await c.call('/reports/'+r.id+'/accept-actions','POST',{action_indexes:[0],reason:'记录无依据提案',expected_version:r.version})).data;const s=r.strategies[0];assert.equal((await c.call('/strategy-memories/'+s.id+'/activate','POST',{reason:'无依据拒绝',expected_version:s.version})).error.code,'STRATEGY_EVIDENCE_REQUIRED');await env.db.query("UPDATE strategy_memories SET review_at=now()-interval '1 day' WHERE id=$1",[s.id]);assert.equal((await c.call('/strategy-memories/'+s.id+'/activate','POST',{reason:'过期拒绝',expected_version:s.version})).error.code,'STRATEGY_NOT_CURRENT');assert.equal((await env.db.query('SELECT status FROM strategy_memories WHERE id=$1',[s.id])).rows[0].status,'proposed');});
