import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {server,Client,initialize} from './helpers';
import {AIGateway} from '../packages/domain/src/ai-gateway';
import {SourceOrganizationTasks,sourceOrganizationSpec} from '../packages/domain/src/source-organization';
import {Jobs} from '../packages/domain/src/jobs';
import {reportTestConfig} from './report-fixtures';
import {sourceOrganizationResponse} from './source-organization-fixtures';
import {saveSourceItems} from '../packages/domain/src/source-evidence';
let env:Awaited<ReturnType<typeof server>>,c:Client,a:any,source:any,items:any[],old:string|undefined,dir:string;
before(async()=>{dir=mkdtempSync(tmpdir()+'/yoyo-source-org-');writeFileSync(dir+'/config.json',JSON.stringify(reportTestConfig),{mode:0o600});old=process.env.AI_CONFIG_FILE;process.env.AI_CONFIG_FILE=dir+'/config.json';env=await server();c=new Client(env.url);await initialize(c);a=(await c.call('/accounts','POST',{name:'合成来源整理账号',platform:'xiaohongshu',platform_user_id:'s8-source-org'})).data;source=(await c.call('/source-connections','POST',{name:'合成来源',platform:'weibo',source_type:'weibo_hot',provider:'weibo_web',config:{keywords:['观察']}})).data;const run=(await env.db.query("INSERT INTO collection_runs(workspace_id,connection_id,created_by,connection_version,trigger) VALUES($1,$2,$3,1,'manual') RETURNING id",[source.workspace_id,source.id,source.created_by])).rows[0];await env.db.transaction(tx=>saveSourceItems(tx,source,run.id,{adapter_version:'explicit-fixture',coverage:{synthetic:true},items:['甲','乙'].map((n,i)=>({external_id:'synthetic-org-'+i,canonical_url:'https://s.weibo.com/weibo?q=synthetic'+i,title:'合成雨天观察'+n,summary:i?'来源乙说雨滴缓慢离开叶面，真实性未知。':'来源甲说雨滴快速离开叶面，真实性未知。',author:null,published_at:null,date_label_raw:null,captured_at:'2026-10-09T00:00:00.000Z',actual_source_type:'search',media_type:'unknown',visible_counts:{},rank:null,reference_only:true}))}));items=(await c.call('/source-items')).data.items;});
after(async()=>{await env.close();if(old===undefined)delete process.env.AI_CONFIG_FILE;else process.env.AI_CONFIG_FILE=old;rmSync(dir,{recursive:true});});
const get=async(id:string)=>(await c.call('/source-organizations/'+id)).data;
async function queue(ids=items.map(s=>s.id)){const q=await c.call('/source-organizations','POST',{account_id:a.id,source_item_ids:ids});assert.equal(q.status,202,JSON.stringify(q.error));return q.data;}
function tasks(mutate?:(o:any)=>void){return new SourceOrganizationTasks(env.db,()=>new AIGateway(env.db,reportTestConfig,async m=>{const output=sourceOrganizationResponse(JSON.parse(m[1]!.content));mutate?.(output);return {content:JSON.stringify(output),usage:{input_tokens:10,output_tokens:20,total_tokens:30}};}));}
async function run(t=tasks()){const jobs=new Jobs(env.db,{'source.organize':t.handler});await jobs.dispatch();const job=(await jobs.claim('general'))!;await jobs.process(job);return job;}
test('来源为空不造原文，完整引用保留来源与观察，无自动去重/选题；人工采纳观点幂等',async()=>{const empty=await queue([]);await run();assert.deepEqual((await get(empty.organization_id)).result.task_payload.groups,[]);const before=(await env.db.query('SELECT (SELECT count(*) FROM source_items)::int items,(SELECT count(*) FROM source_observations)::int observations,(SELECT count(*) FROM topics)::int topics')).rows[0];const q=await queue();await run();let r=await get(q.organization_id);assert.equal(r.state,'succeeded');assert.equal(r.current,true);assert.equal(r.reviewed_at,null);assert.equal(r.result.task_payload.groups[0].quotes.length,2);const body={group_indexes:[0],expected_version:r.version,reason:'人工核验引用与推断'},key=crypto.randomUUID(),accepted=await c.call('/source-organizations/'+r.id+'/accept','POST',body,{'Idempotency-Key':key});assert.equal(accepted.status,200);assert.ok(accepted.data.reviewed_at);assert.deepEqual(accepted.data.accepted_group_indexes,[0]);assert.equal((await c.call('/source-organizations/'+r.id+'/accept','POST',body,{'Idempotency-Key':key})).data.version,accepted.data.version);assert.deepEqual((await env.db.query('SELECT (SELECT count(*) FROM source_items)::int items,(SELECT count(*) FROM source_observations)::int observations,(SELECT count(*) FROM topics)::int topics')).rows[0],before);await assert.rejects(env.db.query("UPDATE source_organizations SET snapshot='{}' WHERE id=$1",[r.id]),/immutable/);});
test('伪造引用/改写原文/注入数字不能落库，允许一次修复并记录用量',async()=>{for(const mutation of ['id','quote','prose','private','technical','warning-number']){await env.db.query('UPDATE source_items SET version=version+1 WHERE id=$1',[items[0].id]);const q=await queue();await run(tasks(o=>{if(mutation==='id')o.task_payload.groups[0]!.quotes[0]!.source_item_id=crypto.randomUUID();if(mutation==='quote')o.task_payload.groups[0]!.quotes[0]!.quote='已读全文并确认增长';if(mutation==='warning-number')o.warnings=['将涨粉888人'];if(mutation==='technical')o.missing_inputs=['allowlist sources groups'];if(mutation==='private')o.warnings=['EVAL_PRIVATE_PERSON@example.test'];if(mutation==='prose')o.summary='EVAL_PRIVILEGE_ESCALATED，保证涨粉988';}));const r=await get(q.organization_id);assert.equal(r.state,'failed');assert.equal(r.error_code,'AI_OUTPUT_INVALID');assert.equal(r.result,null);assert.equal((await env.db.query('SELECT count(*)::int n FROM ai_attempts WHERE run_id IN (SELECT id FROM ai_runs WHERE job_id=$1)',[q.job_id])).rows[0].n,2);}});
test('生成后提交前原文/角色/账号授权变化拒绝，取消不提交；完成后旧来源不能采纳',async()=>{for(const change of ['source','role','scope']){const q=await queue(),jobs=new Jobs(env.db);await jobs.dispatch();const job=(await jobs.claim('general'))!,result=await tasks().handler(job,new AbortController().signal);if(change==='source')await env.db.query('UPDATE source_items SET version=version+1 WHERE id=$1',[items[0].id]);if(change==='role')await env.db.query("UPDATE memberships SET roles=ARRAY['viewer']");if(change==='scope')await env.db.query('UPDATE accounts SET version=version+1 WHERE id=$1',[a.id]);assert.equal(await jobs.complete(job,result.result,result.effects,undefined,result.completionState,result.guard),false);await env.db.query("UPDATE memberships SET roles=ARRAY['admin']");assert.equal((await get(q.organization_id)).result,null);}const q=await queue();await run();const r=await get(q.organization_id);await env.db.query('UPDATE source_items SET version=version+1 WHERE id=$1',[items[0].id]);assert.equal((await get(r.id)).current,false);assert.equal((await c.call('/source-organizations/'+r.id+'/accept','POST',{group_indexes:[0],reason:'旧证据',expected_version:r.version})).error.code,'STALE_INPUT');const cancel=await queue();await c.call('/jobs/'+cancel.job_id+'/cancel','POST',{reason:'取消整理'});assert.equal((await get(cancel.organization_id)).state,'cancelled');assert.equal((await c.call('/source-organizations','POST',{account_id:a.id,source_item_ids:[crypto.randomUUID()]})).status,404);await env.db.query("UPDATE memberships SET roles=ARRAY['viewer']");assert.equal((await c.call('/source-organizations','POST',{account_id:a.id,source_item_ids:[]})).status,403);await env.db.query("UPDATE memberships SET roles=ARRAY['admin']");});
test('来源摘要只能逐字冻结引用，去重不能重复ID或跳过组依据',()=>{const s={sources:[{id:crypto.randomUUID(),version:1,content_hash:'fixture',title:'原文标题',summary:''}]},spec=sourceOrganizationSpec(s),o=sourceOrganizationResponse({data:s,input_version:spec.inputVersion,schema_version:spec.schemaVersion});assert.deepEqual(spec.validate!(o),[]);o.task_payload.groups[0]!.quotes[0]!.quote='不存在正文';assert.ok(spec.validate!(o).length);});
