import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Client,initialize,server} from './helpers';
import {saveTopics} from '../packages/domain/src/topics';
import {topicCandidateSchema,scoreCriteria} from '../packages/domain/src/ai-workflows';
import {Topics} from '../apps/api/src/topics';
import {sha,canonical,Actor} from '../packages/domain/src/protocol';
let env:Awaited<ReturnType<typeof server>>,client:Client,me:any,account:any,actor:Actor;
before(async()=>{env=await server();client=new Client(env.url);me=await initialize(client);account=(await client.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'controlled',name:'受控测试'})).data;actor={userId:me.user.id,memberId:me.membership.id,workspaceId:me.workspace.id,roles:['admin'],sessionHash:'',requestId:randomUUID()};});after(()=>env.close());
function candidate(extra:any={}){return topicCandidateSchema.parse({title:'明确合成：雨天观察',audience:'年轻人',need:'轻松',scene:'日常',column:'观察',emotion:'好奇',media_type:'graphic',follow_reason:'下次观察',evidence_refs:[],original_angle:'原创小发现',score_breakdown:scoreCriteria.map(criterion=>({criterion,score:4,reason:'合成测试评分'})),estimated_hours:null,expires_at:null,assumptions:['明确合成测试'],...extra});}
async function seed(c=candidate()){
 const snapshot={scope_version:'v1.2',account:{id:account.id,name:account.name,version:account.version},workspace_version:1,sources:[],warnings:[],columns:['观察'],capacity_hours:4};
 const r=(await env.db.query("INSERT INTO ai_requests(workspace_id,account_id,created_by,kind,input_version,snapshot,state) VALUES($1,$2,$3,'topics',$4,$5,'succeeded') RETURNING *",[actor.workspaceId,account.id,actor.memberId,sha(canonical(snapshot)),JSON.stringify(snapshot)])).rows[0];const output={schema_version:'ai-v1.2',input_version:r.input_version,summary:'合成',evidence_refs:[],assumptions:[],missing_inputs:['制作工时待估'],warnings:['受控夹具'],task_payload:{candidates:[c]}};await env.db.transaction(tx=>saveTopics(tx,r,output));return (await env.db.query('SELECT * FROM topics WHERE generation_request_id=$1',[r.id])).rows[0];
}
test('六项权重由服务端计分，保留缺项与生成批次，重复保存不新增',async()=>{
 const t=await seed();assert.equal(Number(t.score),80);const list=(await client.call('/topics?account_id='+account.id)).data;assert.ok(list.items.some((i:any)=>i.id===t.id));assert.equal(t.missing_inputs[0],'制作工时待估');assert.equal((await client.call('/topics/'+t.id)).data.decisions.length,0);
 const request=(await env.db.query('SELECT * FROM ai_requests WHERE id=$1',[t.generation_request_id])).rows[0];await env.db.transaction(tx=>saveTopics(tx,request,{schema_version:'ai-v1.2',input_version:request.input_version,summary:'',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate()]}}));assert.equal((await env.db.query('SELECT count(*)::int n FROM topics WHERE generation_request_id=$1',[request.id])).rows[0].n,1);
});
test('不同请求键并发采纳只保存一个决策，重复采纳返回原结果且没有Job/生产关系',async()=>{
 const t=await seed(),before=(await env.db.query('SELECT count(*)::int n FROM jobs')).rows[0].n,b={expected_version:1};const r=await Promise.all([client.call('/topics/'+t.id+'/accept','POST',b),client.call('/topics/'+t.id+'/accept','POST',b)]);assert.ok(r.every(x=>x.status===200));assert.deepEqual(r[0]!.data,r[1]!.data);assert.equal(r[0]!.data.topic_id,t.id);assert.equal((await env.db.query("SELECT count(*)::int n FROM topic_decisions WHERE topic_id=$1 AND decision='accepted'",[t.id])).rows[0].n,1);assert.equal((await env.db.query('SELECT count(*)::int n FROM jobs')).rows[0].n,before);assert.equal((await env.db.query('SELECT accepted_owner_id FROM topics WHERE id=$1',[t.id])).rows[0].accepted_owner_id,actor.memberId);assert.equal('content_id' in r[0]!.data,false);
 assert.equal((await client.call('/topics/'+t.id+'/accept','POST',{...b,media_type:'video'})).status,422);
});
test('拒绝原因不可丢失；与采纳竞争只有一条最终决策，过期不得采纳',async()=>{
 const t=await seed();const results=await Promise.all([client.call('/topics/'+t.id+'/accept','POST',{expected_version:1}),client.call('/topics/'+t.id+'/reject','POST',{reason:'不适合当前产能',expected_version:1})]);assert.equal(results.filter(r=>r.status<300).length,1);const detail=(await client.call('/topics/'+t.id)).data;assert.equal(detail.decisions.length,1);assert.ok(detail.decisions[0].reason);
 const expired=await seed(candidate({expires_at:new Date(Date.now()-1000).toISOString()}));assert.equal((await client.call('/topics/'+expired.id+'/accept','POST',{expected_version:1})).error.code,'TOPIC_EXPIRED');assert.equal((await client.call('/topics?status=expired')).data.items.some((i:any)=>i.id===expired.id),true);
});
test('显式变体保留父题/理由/证据并独立采纳；越权负责人和空间拒绝',async()=>{
 const t=await seed();await env.db.query("UPDATE topics SET candidate=jsonb_set(candidate,'{estimated_hours}','2') WHERE id=$1",[t.id]);const variants=await Promise.all([client.call('/topics/'+t.id+'/variants','POST',{goal:'明确换一个角度',media_type:'video'}),client.call('/topics/'+t.id+'/variants','POST',{goal:'另一个图文角度',media_type:'graphic'})]);assert.ok(variants.every(v=>v.status===201));assert.notEqual(variants[0]!.data.id,variants[1]!.data.id);assert.equal(variants[0]!.data.parent_topic_id,t.id);assert.ok(variants.every(v=>v.data.candidate.estimated_hours===null));
 assert.equal((await client.call('/topics/'+t.id+'/accept','POST',{owner_id:randomUUID(),expected_version:1})).error.code,'OWNER_INVALID');await assert.rejects(new Topics(env.db).scope(env.db,{...actor,workspaceId:randomUUID()},t.id),(e:any)=>e.code==='NOT_FOUND');
});
test('事实缺观察/伪造来源使整个候选事务回滚，不用高分掩盖错误',async()=>{
 const t=await seed(),request=(await env.db.query('SELECT * FROM ai_requests WHERE id=$1',[t.generation_request_id])).rows[0];request.id=randomUUID();await env.db.query('INSERT INTO ai_requests(id,workspace_id,account_id,created_by,kind,input_version,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7)',[request.id,actor.workspaceId,account.id,actor.memberId,'topics',request.input_version,JSON.stringify(request.snapshot)]);
 await assert.rejects(env.db.transaction(tx=>saveTopics(tx,request,{schema_version:'ai-v1.2',input_version:request.input_version,summary:'',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate(),candidate({evidence_refs:[{source_item_id:randomUUID(),claim:'伪造事实',evidence_kind:'fact'}]})]}})));
 assert.equal((await env.db.query('SELECT count(*)::int n FROM topics WHERE generation_request_id=$1',[request.id])).rows[0].n,0);
});
test('编辑只能采纳本人的任务；缺拒绝理由与陈旧版本不能改变选题',async()=>{
 const t=await seed(),topics=new Topics(env.db),editor={...actor,roles:['editor'] as Actor['roles']};await assert.rejects(env.db.transaction(tx=>topics.accept(tx,editor,t.id,{owner_id:randomUUID(),expected_version:1})),(e:any)=>e.code==='OWNER_FORBIDDEN');assert.equal((await client.call('/topics/'+t.id+'/reject','POST',{reason:'',expected_version:1})).status,422);assert.equal((await client.call('/topics/'+t.id+'/reject','POST',{reason:'不合适',expected_version:99})).error.code,'VERSION_CONFLICT');
});
test('证据显示采纳建议生成时的不可变观察，不随着来源更新改写标题；观察必须匹配来源',async()=>{
 const {saveSourceItems}=await import('../packages/domain/src/source-evidence');const connection=(await client.call('/source-connections','POST',{platform:'weibo',source_type:'weibo_hot',provider:'weibo_web',name:'合成证据连接'})).data;
 async function observe(title:string,external_id='fixed-source'){const run=(await env.db.query("INSERT INTO collection_runs(workspace_id,connection_id,created_by,connection_version,trigger,state) VALUES($1,$2,$3,1,'manual','succeeded') RETURNING id",[actor.workspaceId,connection.id,actor.memberId])).rows[0];await env.db.transaction(tx=>saveSourceItems(tx,connection,run.id,{items:[{external_id,canonical_url:'https://s.weibo.com/weibo?q=controlled',title,summary:'明确合成测试',author:null,published_at:null,date_label_raw:null,captured_at:new Date().toISOString(),actual_source_type:'official_rank',media_type:'unknown',visible_counts:{},rank:1,reference_only:true}],coverage:{test_only:true},adapter_version:'controlled'}));return (await env.db.query('SELECT i.id,o.id observation_id,o.captured_at FROM source_items i JOIN source_observations o ON o.source_item_id=i.id WHERE o.run_id=$1',[run.id])).rows[0];}
 const original=await observe('原始合成标题'),base=await seed(),generation=(await env.db.query('SELECT * FROM ai_requests WHERE id=$1',[base.generation_request_id])).rows[0];generation.id=randomUUID();generation.snapshot.sources=[{...original,title:'原始合成标题',summary:'明确合成测试',pipeline_type:'weibo_hot'}];await env.db.query("INSERT INTO ai_requests(id,workspace_id,account_id,created_by,kind,input_version,snapshot) VALUES($1,$2,$3,$4,'topics',$5,$6)",[generation.id,actor.workspaceId,account.id,actor.memberId,generation.input_version,JSON.stringify(generation.snapshot)]);
 const falseProof={schema_version:'ai-v1.2',input_version:generation.input_version,summary:'',evidence_refs:[original.id],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate({evidence_refs:[{source_item_id:original.id,claim:'白名单来源证明任务标题正确',evidence_kind:'fact'}]})]}};await assert.rejects(env.db.transaction(tx=>saveTopics(tx,generation,falseProof)));assert.equal((await env.db.query('SELECT count(*)::int n FROM topics WHERE generation_request_id=$1',[generation.id])).rows[0].n,0);
 await env.db.transaction(tx=>saveTopics(tx,generation,{schema_version:'ai-v1.2',input_version:generation.input_version,summary:'',evidence_refs:[original.id],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate({evidence_refs:[{source_item_id:original.id,claim:'原始合成标题',evidence_kind:'fact'}]})]}}));const topic=(await env.db.query('SELECT id,expires_at FROM topics WHERE generation_request_id=$1',[generation.id])).rows[0];assert.equal(new Date(topic.expires_at).getTime(),new Date(original.captured_at).getTime()+86400000);await observe('后来更新的标题');assert.equal((await client.call('/topics/'+topic.id)).data.evidence[0].title,'原始合成标题');
 const other=await observe('不同线索','other-source');await assert.rejects(env.db.query("INSERT INTO topic_evidence(workspace_id,topic_id,source_item_id,observation_id,claim,evidence_kind) VALUES($1,$2,$3,$4,'错配','fact')",[actor.workspaceId,topic.id,original.id,other.observation_id]));
});
test('常青原创不能把来源窗口结束填成到期；明确来源的时效由服务端保留',async()=>{
 const {topicSpec}=await import('../packages/domain/src/ai-workflows');const spec=topicSpec({input:{window:{end:new Date().toISOString()}},inputVersion:'controlled',inputRefs:[],sourceIds:[],});
 const base={schema_version:'ai-v1.2',input_version:'controlled',summary:'',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate({expires_at:new Date().toISOString()})]}};assert.ok(spec.validate!(base).includes('candidates/0:EVERGREEN_MUST_NOT_EXPIRE'));assert.deepEqual(spec.validate!({...base,task_payload:{candidates:[candidate()]}}),[]);
});
test('停用选题负责人必须移交，历史决策不改写，新负责人有授权和待办；编辑不能驳回他人题',async()=>{
 const t=await seed(),c=await client.call('/members','POST',{email:'handoff@example.test',roles:['editor']}),member=c.data.id;

 await client.call('/topics/'+t.id+'/accept','POST',{expected_version:1,owner_id:member});
 assert.equal((await client.call('/members/'+member,'PATCH',{active:false,expected_version:1})).error.code,'SUCCESSOR_REQUIRED');
 const transferred=await client.call('/members/'+member,'PATCH',{active:false,expected_version:1,successor_id:actor.memberId});assert.equal(transferred.status,200);
 const detail=(await client.call('/topics/'+t.id)).data;assert.equal(detail.accepted_owner_id,actor.memberId);assert.equal(detail.decisions[0].owner_id,member);assert.equal((await env.db.query("SELECT count(*)::int n FROM notifications WHERE event_key LIKE 'topic.owner:%' AND recipient_id=$1",[actor.memberId])).rows[0].n,1);
 const other=await seed();const editor={...actor,memberId:member,roles:['editor'] as Actor['roles']};await assert.rejects(env.db.transaction(tx=>new Topics(env.db).reject(tx,editor,other.id,{reason:'不允许跨负责人处理',expected_version:1})),(e:any)=>e.code==='OWNER_FORBIDDEN');
});
