import {z} from 'zod';
import {Database,Tx} from '../../db/src/db';
import {Actor,AppError,parse,uuid,version,text,canonical,sha} from './protocol';
import {JobHandler} from './jobs';
export const metricDefinitions=[
 ['followers','粉丝总数','人','account',['snapshot']],['new_followers','新增关注','人','account',['interval']],['unfollows','取关','人','account',['interval']],
 ['impressions','曝光','次','both',['cumulative','interval']],['reads','阅读','次','publication',['cumulative','interval']],['plays','播放','次','publication',['cumulative','interval']],
 ['likes','点赞','次','publication',['cumulative','interval']],['saves','收藏','次','publication',['cumulative','interval']],['comments','评论','次','publication',['cumulative','interval']],['shares','分享','次','publication',['cumulative','interval']],
 ['attributed_follows','笔记归因新增关注','人','publication',['cumulative','interval']],['likes_saves_combined','获赞与收藏（组合）','次','both',['snapshot','cumulative','interval']],
 ['completion_rate','完播率','%','publication',['interval']],['average_watch_seconds','平均观看时长','秒','publication',['interval']],['watch_count','对应观看次数','次','publication',['interval']]
].map(([key,label,unit,scope,kinds])=>({key:key as string,label:label as string,unit:unit as string,scope:scope as string,kinds:kinds as string[],definition_version:'1',source_definition_required:true}));
export const derivedDefinitions=[
 ['net_followers','净增粉','人','account'],['follows_per_1000_reads','千次阅读关注','人/千次','publication'],['interaction_count_rate','互动次数率','%','publication'],['weighted_average_watch_seconds','加权平均观看时长','秒','account'],
 ...metricDefinitions.filter(d=>['impressions','reads','plays','likes','saves','comments','shares','attributed_follows'].includes(d.key)).map(d=>[d.key+'_interval_delta',d.label+'（区间增量）',d.unit,d.scope])
].map(([key,label,unit,scope])=>({key:key!,label:label!,unit:unit!,scope:scope!,kinds:['derived'],definition_version:'1',source_definition_required:true}));
export const templateFields={account_id:'授权账号UUID，必须与所选账号一致',platform_note_id:'平台笔记ID；账号指标留空，未匹配先人工登记',metric_key:'指标字典key，不拆组合字段',value:'原值；可空但必须说明缺失；1.2 万保留近似标记',unit:'人 / 次 / % / 秒，按字典',window_start:'区间开始，包含；带时区ISO8601',window_end:'区间结束，不包含；带时区ISO8601',observed_at:'快照/累计观察时间，带时区；不捏造秒',traffic_type:'organic自然 / paid付费 / mixed混合 / unknown未知',source_note:'来源说明，不能充当平台定义',definition_version:'指标定义版本，当前1',aggregation_kind:'snapshot快照 / cumulative累计 / interval区间',source_definition:'平台实际指标口径；不同定义分组',missing_reason:'value为空时必填，缺失不填零',time_precision:'day日期 / minute分钟 / second秒；按实际来源',is_example:'true为永久不可入账示例；实际行填false'};
const optionalTime=z.iso.datetime({offset:true}).nullable();
export const metricSchema=z.object({target:z.object({account_id:uuid,publication_id:uuid.nullable().optional()}).strict(),metric_key:text(100),definition_version:text(50),aggregation_kind:z.enum(['snapshot','cumulative','interval']),value:z.string().nullable(),unit:text(20),missing_reason:z.string().nullable().optional(),window_start:optionalTime.optional(),window_end:optionalTime.optional(),observed_at:optionalTime.optional(),traffic_type:z.enum(['organic','paid','mixed','unknown']),is_approximate:z.boolean().default(false),source_definition:text(1000),time_precision:z.enum(['day','minute','second']),source_note:z.string().max(2000).default('')}).strict();
export type Metric=z.infer<typeof metricSchema>;
export function decimal(value:string){const raw=value.trim();const m=raw.match(/^(-?\d+(?:\.\d{1,6})?)\s*(万)?$/);if(!m)throw new AppError(422,'METRIC_VALUE_INVALID','值必须是十进制数或明确的万单位约数');let n=BigInt(m[1]!.replace('.',''));const scale=(m[1]!.split('.')[1]??'').length;if(m[2])n*=10000n;const factor=10n**BigInt(scale);const sign=n<0n?'-':'';n=n<0n?-n:n;const fraction=(n%factor).toString().padStart(scale,'0').replace(/0+$/,'');return {value:sign+(n/factor).toString()+(fraction?'.'+fraction:''),approximate:!!m[2]};}
export function normalizeMetric(input:unknown):Metric{const m=parse(metricSchema,input),d=metricDefinitions.find(d=>d.key===m.metric_key);if(!d||d.definition_version!==m.definition_version||d.unit!==m.unit||!d.kinds.includes(m.aggregation_kind))throw new AppError(422,'METRIC_DEFINITION_INVALID','指标、单位、版本或统计类型不符合字典');if(d.scope==='account'&&m.target.publication_id||d.scope==='publication'&&!m.target.publication_id)throw new AppError(422,'METRIC_SCOPE_INVALID','指标主体与字典不一致');
 if(m.value===null){if(!m.missing_reason?.trim())throw new AppError(422,'METRIC_MISSING_REASON','缺失值必须填写原因');}else{const n=decimal(m.value);if(n.value.startsWith('-'))throw new AppError(422,'METRIC_VALUE_INVALID','原始计数不可为负');if(n.value.split('.')[0]!.length>18||(['人','次'].includes(m.unit)&&n.value.includes('.'))||m.unit==='%'&&Number(n.value)>100)throw new AppError(422,'METRIC_VALUE_INVALID','值超限或计数不是整数');m.value=n.value;m.is_approximate||=n.approximate;m.missing_reason=null;}
 if(m.aggregation_kind==='interval'){if(!m.window_start||!m.window_end||Date.parse(m.window_start)>=Date.parse(m.window_end))throw new AppError(422,'METRIC_WINDOW_INVALID','区间开始必须早于结束');m.observed_at=null;}else{if(!m.observed_at)throw new AppError(422,'METRIC_TIME_REQUIRED','快照/累计需要实际观察时间');m.window_start=null;m.window_end=null;}
 for(const key of ['window_start','window_end','observed_at'] as const){if(m[key]){const date=new Date(m[key]!);if(date.getTime()>Date.now())throw new AppError(422,'METRIC_TIME_INVALID','实际数据时间不能在未来');if(m.time_precision!=='second'&&(date.getUTCSeconds()||date.getUTCMilliseconds()))throw new AppError(422,'METRIC_PRECISION_INVALID','时间精度与输入不符');m[key]=date.toISOString();}}
 return m;
}
export function logicalKey(workspace:string,m:Metric){return sha(canonical([workspace,m.target.account_id,m.target.publication_id??null,m.metric_key,m.definition_version,m.aggregation_kind,m.traffic_type,m.source_definition,m.time_precision,m.window_start??null,m.window_end??null,m.observed_at??null]));}
export function sameValue(a:Metric,b:Metric){return canonical([a.value,a.missing_reason??null,a.is_approximate])===canonical([b.value,b.missing_reason??null,b.is_approximate]);}
export async function batchScope(q:Pick<Database,'query'>|Tx,a:Actor,id:string,lock=false){const r=await q.query(`SELECT b.* FROM import_batches b WHERE b.workspace_id=$1 AND b.id=$2 AND ($3::boolean OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.account_id=b.account_id AND am.membership_id=$4)) ${lock?'FOR UPDATE OF b':''}`,[a.workspaceId,parse(uuid,id),a.roles.includes('admin'),a.memberId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','批次不存在或不可见');return r.rows[0];}
export async function rowMetric(tx:Tx,b:any,raw:any){if(raw.target){const {is_example,...input}=raw;const m=normalizeMetric(input);if(m.target.account_id!==b.account_id)throw new AppError(422,'DATA_SCOPE_MISMATCH','行账号与批次不一致');if(m.target.publication_id){const p=await tx.query('SELECT published_at,media_type FROM publications WHERE id=$1 AND account_id=$2 AND workspace_id=$3',[m.target.publication_id,b.account_id,b.workspace_id]);if(!p.rowCount)throw new AppError(422,'DATA_SCOPE_MISMATCH','笔记不属于批次账号');if(['plays','completion_rate','average_watch_seconds','watch_count'].includes(m.metric_key)&&p.rows[0].media_type!=='video')throw new AppError(422,'METRIC_MEDIA_INVALID','视频指标只能匹配已登记视频');if(Date.parse(m.window_start??m.observed_at!)<new Date(p.rows[0].published_at).getTime())throw new AppError(422,'METRIC_WINDOW_INVALID','笔记数据不能早于发布时间');}return m;}
 if(raw.account_id!==b.account_id)throw new AppError(422,'DATA_SCOPE_MISMATCH','表格账号与批次不一致');let pid=null;if(raw.platform_note_id){pid=(await tx.query('SELECT id FROM publications WHERE workspace_id=$1 AND account_id=$2 AND platform_note_id=$3',[b.workspace_id,b.account_id,raw.platform_note_id])).rows[0]?.id;if(!pid)throw new AppError(422,'PUBLICATION_UNMATCHED','未匹配笔记，请先人工登记');}
 return rowMetric(tx,b,{target:{account_id:b.account_id,publication_id:pid},metric_key:raw.metric_key,definition_version:raw.definition_version??'1',aggregation_kind:raw.aggregation_kind,value:raw.value===''?null:raw.value,unit:raw.unit,missing_reason:raw.missing_reason||null,window_start:raw.window_start||null,window_end:raw.window_end||null,observed_at:raw.observed_at||null,traffic_type:raw.traffic_type,source_definition:raw.source_definition,time_precision:raw.time_precision,source_note:raw.source_note??''});
}
export async function addRows(tx:Tx,b:any,inputs:{raw:any;file_id?:string}[]){for(const [i,input] of inputs.entries()){const example=input.raw.is_example===true||input.raw.is_example==='true';let metric=null,error=null,status='excluded';if(!example){try{metric=await rowMetric(tx,b,input.raw);status='valid';}catch(e){if(!(e instanceof AppError))throw e;error=e.message;status=e.code==='PUBLICATION_UNMATCHED'?'unmatched':'excluded';}}await tx.query('INSERT INTO import_rows(workspace_id,batch_id,row_number,file_id,raw,metric,error,status,is_example) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[b.workspace_id,b.id,i+1,input.file_id??null,JSON.stringify(input.raw),metric?JSON.stringify(metric):null,error,status,example]);}}
export function importParseHandler(db:Database):JobHandler{return async j=>({result:{batch_id:j.input.batch_id},guard:async tx=>{const m=await tx.query("SELECT m.id FROM memberships m WHERE m.id=$1 AND m.workspace_id=$2 AND m.active AND (m.roles && ARRAY['admin','operator']::text[]) AND ('admin'=ANY(m.roles) OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.membership_id=m.id AND am.account_id=$3)) FOR SHARE OF m",[j.created_by,j.workspace_id,j.account_id]);return m.rowCount?null:'IMPORT_SCOPE_CHANGED';},effects:async tx=>{const b=(await tx.query('SELECT * FROM import_batches WHERE id=$1 FOR UPDATE',[j.input.batch_id])).rows[0];if(!b||!['uploaded','parsing'].includes(b.status))throw new Error('IMPORT_CHANGED');const rows:{raw:any;file_id:string}[]=[];for(const fid of b.input_file_ids){const f=(await tx.query("SELECT metadata FROM file_objects WHERE id=$1 AND workspace_id=$2 AND account_id=$3 AND purpose='import_table' AND file_status='ready' AND metadata->>'table_parser_version'='table-v1'",[fid,b.workspace_id,b.account_id])).rows[0];if(!f)throw new Error('IMPORT_FILE_NOT_READY');const [header,...data]=f.metadata.table as string[][];if(!header||new Set(header).size!==header.length)throw new Error('IMPORT_HEADER_INVALID');for(const cells of data){if(!cells.some(Boolean))continue;const raw:Record<string,string>={};for(const [i,col] of header.entries())raw[b.mapping[col]??col]=cells[i]??'';rows.push({raw,file_id:fid});}}if(!rows.length||rows.length>5000)throw new Error('IMPORT_ROW_LIMIT');await addRows(tx,b,rows);await tx.query("UPDATE import_batches SET status='needs_confirmation',version=version+1,updated_at=now() WHERE id=$1",[b.id]);}});}
