import React,{useState,useEffect} from 'react';
import {api} from './api';
import {uploadFile} from './assets';
import {AssetPicker} from './asset-picker';
import {ErrorState} from './components';
import type {SessionData} from '../../../packages/contracts/src/types';
export const contentStatuses:Record<string,string>={draft:'草稿',in_production:'制作中',in_review:'内部审核中',ready_to_publish:'待发布',published:'已发布',cancelled:'已取消'};
export function GraphicEditor({content,me,onSaved,onDirty}:{content:any;me:SessionData;onSaved:()=>Promise<void>;onDirty:(dirty:boolean)=>void}){
 const [editing,setEditing]=useState(false),[payload,setPayload]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState<Error|null>(null),[notice,setNotice]=useState(''),[history,setHistory]=useState<any>(null),[picker,setPicker]=useState<number|null>(null),[references,setReferences]=useState<Record<string,any>>({}),[previews,setPreviews]=useState<Record<string,string>>({});
 const production=me.permissions.includes('content.production'),copy=me.permissions.includes('content.copy');
 const editable=['draft','in_production'].includes(content.business_status);
 useEffect(()=>{setEditing(false);setPayload(null);},[content.current_revision_id]);
 const dirty=editing&&JSON.stringify(payload)!==JSON.stringify(content.current_revision.payload);
 useEffect(()=>{onDirty(dirty);const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return ()=>{window.removeEventListener('beforeunload',warn);onDirty(false);};},[dirty]);
 async function refreshFiles(){try{await onSaved();const out:Record<string,string>={};for(const f of content.deliverables??[]){try{out[f.id]=(await api('/files/'+f.id+'/preview')).url;}catch{}}setPreviews(out);}catch(e){setError(e as Error);}}
 async function upload(index:number,file:File){setBusy(true);setError(null);try{const f=await uploadFile(file,me,new AbortController().signal,()=>{});pageChange(index,{publish_file_id:f.id});setNotice(`第${index+1}页成品原件已上传`);}catch(e){setError(e as Error);}finally{setBusy(false);}}
 function change(values:any){setPayload((old:any)=>({...old,...values}));}
 function pageChange(index:number,values:any){change({pages:payload.pages.map((p:any,i:number)=>i===index?{...p,...values}:p)});}
 function reorder(from:number,to:number){const pages=[...payload.pages],p=pages.splice(from,1)[0];pages.splice(to,0,p);change({pages:pages.map((p:any,i:number)=>({...p,position:i+1}))});}
 async function save(){setBusy(true);setError(null);try{await api('/contents/'+content.id+'/revisions',{method:'POST',body:{base_revision_id:content.current_revision_id,expected_version:content.version,title:payload.title,body:payload.body??'',tags:payload.tags??[],brief:payload.brief??{},pages:payload.pages??[]}});await onSaved();setNotice('图文快照已保存');}catch(e){setError(e as Error);}finally{setBusy(false);}}
 async function restore(source:string){setBusy(true);setError(null);try{await api('/contents/'+content.id+'/restore',{method:'POST',body:{source_revision_id:source,base_revision_id:content.current_revision_id,expected_version:content.version}});await onSaved();setHistory(null);setNotice('历史内容已恢复为新快照');}catch(e){setError(e as Error);}finally{setBusy(false);}}
 return <section className="panel"><h3>图文制作 · {contentStatuses[content.business_status]}</h3><ErrorState error={error}/>{notice&&<p role="status">{notice}</p>}{copy&&editable&&!editing&&<button onClick={()=>{setEditing(true);setPayload(structuredClone(content.current_revision.payload));}}>编辑图文</button>}
 {editing&&payload&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><label className="field">图文标题<input value={payload.title} maxLength={200} required onChange={e=>change({title:e.target.value})}/></label><label className="field">发布正文<textarea value={payload.body??''} maxLength={10000} onChange={e=>change({body:e.target.value})}/></label><label className="field">标签（逗号分隔）<input value={(payload.tags??[]).join(',')} onChange={e=>change({tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/></label>
 {production&&<><label className="field">制作目标<input value={payload.brief?.goal??''} onChange={e=>change({brief:{...payload.brief,goal:e.target.value}})}/></label><label className="field">目标人群<input value={payload.brief?.audience??''} onChange={e=>change({brief:{...payload.brief,audience:e.target.value}})}/></label></>}
 {(payload.pages??[]).map((p:any,i:number)=><fieldset key={i} onDragStart={e=>{e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move';}} onDragOver={e=>{if(production)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(!production||busy)return;const raw=e.dataTransfer.getData('text/plain'),from=Number(raw);if(/^\d+$/.test(raw)&&from<payload.pages.length&&from!==i)reorder(from,i);}}><legend>第{i+1}页{!i?' · 封面':''}</legend>{production&&<span draggable={!busy}>拖动第{i+1}页排序</span>}<label className="field">第{i+1}页画面<textarea value={p.visual_instruction} disabled={!production} onChange={e=>pageChange(i,{visual_instruction:e.target.value})}/></label><label className="field">第{i+1}页文案<textarea value={p.page_copy} disabled={!production} onChange={e=>pageChange(i,{page_copy:e.target.value})}/></label>{production&&<><label className="field">上传第{i+1}页PNG成品<input type="file" accept="image/png,.png" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(i,file);}}/></label><p>{p.publish_file_id?'已有成品原件，保存后查看预览':'成品待上传'}</p><button type="button" aria-label={`第${i+1}页添加素材引用`} onClick={()=>setPicker(i)}>添加素材引用</button>{(p.asset_version_ids??[]).map((v:string)=><div key={v}><p>{references[v]?.name??'素材版本'}{references[v]?.version_no?' · 版本 '+references[v].version_no:''} · {references[v]?.business_status==='pending_confirmation'?'使用范围待确认':v}</p><button type="button" onClick={()=>pageChange(i,{asset_version_ids:p.asset_version_ids.filter((id:string)=>id!==v)})}>移除素材引用</button></div>)}<button type="button" aria-label={`第${i+1}页上移`} disabled={!i} onClick={()=>reorder(i,i-1)}>上移</button><button type="button" aria-label={`第${i+1}页下移`} disabled={i===payload.pages.length-1} onClick={()=>reorder(i,i+1)}>下移</button><button type="button" onClick={()=>change({pages:payload.pages.filter((_:any,n:number)=>n!==i).map((p:any,n:number)=>({...p,position:n+1}))})}>移除此页</button></>}</fieldset>)}
 {production&&<button type="button" disabled={(payload.pages?.length??0)>=30} onClick={()=>change({pages:[...(payload.pages??[]),{position:(payload.pages?.length??0)+1,visual_instruction:'',page_copy:'',asset_version_ids:[],publish_file_id:null}]})}>添加图文页</button>}<button className="primary">保存新快照</button><button type="button" onClick={()=>{if(!dirty||window.confirm('放弃未保存修改？'))setEditing(false);}}>关闭编辑</button></fieldset></form>}
 {picker!==null&&<AssetPicker onClose={()=>setPicker(null)} onSelect={selection=>{setReferences(old=>({...old,[selection.asset_version_id]:selection}));pageChange(picker,{asset_version_ids:[...new Set([...(payload.pages[picker].asset_version_ids??[]),selection.asset_version_id])]});setPicker(null);}}/>}
 <button type="button" disabled={busy} onClick={()=>void refreshFiles()}>刷新成品状态</button>{(content.deliverables??[]).map((f:any)=><div key={f.position}><p>第{f.position}页 · {f.original_name} · {f.preview_status==='ready'?'预览就绪':'预览待处理或失败'}</p>{previews[f.id]&&<img className="asset-preview" src={previews[f.id]} alt={`第${f.position}页成品`}/>}</div>)}
 <h4>草稿历史与比较</h4>{content.revisions.filter((r:any)=>r.origin!=='ai_candidate').map((r:any)=><button key={r.id} onClick={()=>setHistory(r)}>查看快照 {r.revision_no}{r.id===content.current_revision_id?'（当前）':''}</button>)}{history&&<div><p>快照{history.revision_no} · {history.frozen?'已冻结':'当前草稿'}</p><p>标题：{history.payload.title}</p><p>正文：{history.payload.body}</p><p>页数：{history.payload.pages?.length??0}；当前{content.current_revision.payload.pages?.length??0}页</p>{production&&editable&&history.id!==content.current_revision_id&&<button disabled={busy} onClick={()=>void restore(history.id)}>恢复此快照为新版本</button>}</div>}
 </section>;
}
