import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,ApiError} from './api';
import {Field,Empty,Loading,ErrorState,Drawer,JobStatus} from './components';
import './style.css';
import type {SessionData} from '../../../packages/contracts/src/types';
type Me=SessionData;
const navigation=[['home','工作台','◫'],['topics','选题策划','✧'],['contents','内容工作间','▤'],['calendar','排期日历','▦'],['reports','数据复盘','↗'],['assets','IP 资产库','◇']];
const roleNames:Record<string,string>={admin:'管理员',editor:'编辑/制作',reviewer:'内部审核',operator:'运营',viewer:'只读'};
function App(){
  const [me,setMe]=useState<Me|null>(null),[initialized,setInitialized]=useState<boolean|null>(null),[error,setError]=useState<Error|null>(null),[loading,setLoading]=useState(true);
  const refresh=async()=>{setLoading(true);setError(null);try{const s=await api('/setup/status');setInitialized(s.initialized);if(s.initialized){try{setMe(await api('/me'));}catch(e){if(!(e instanceof ApiError&&e.status===401))throw e;setMe(null);}}}catch(e){setError(e as Error);}finally{setLoading(false);}};
  useEffect(()=>{void refresh();const expire=()=>{setMe(null);setError(new Error('登录已过期，请重新登录。未提交的内容不会自动保存。'));};window.addEventListener('session-expired',expire);return ()=>window.removeEventListener('session-expired',expire);},[]);
  if(loading)return <main className="auth"><Loading/></main>;
  if(initialized===null)return <main className="auth"><ErrorState error={error} retry={()=>void refresh()}/></main>;
  if(!me)return <Auth initialized={initialized} error={error} onDone={refresh}/>;
  return <Shell me={me} onLogout={()=>setMe(null)}/>;
}
function Auth({initialized,error,onDone}:{initialized:boolean;error:Error|null;onDone:()=>Promise<void>}){
  const [failure,setFailure]=useState(error),[busy,setBusy]=useState(false),[invite,setInvite]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setFailure(null);setBusy(true);const f=new FormData(e.currentTarget),values=Object.fromEntries(f.entries());try{
    if(!initialized){await api('/setup',{method:'POST',body:values});await api('/auth/login',{method:'POST',body:{email:values.email,password:values.password}});}
    else if(invite){await api('/auth/accept-invite',{method:'POST',body:values});setInvite(false);}
    else await api('/auth/login',{method:'POST',body:values});
    await onDone();
  }catch(e){setFailure(e as Error);}finally{setBusy(false);}}
  return <main className="auth"><div className="auth-brand"><span className="logo">Y</span><strong>YOYO 运营工作台</strong></div><section className="auth-card"><p className="eyebrow">把创意变成持续的作品</p><h1>{!initialized?'创建你的工作台':invite?'接受成员邀请':'欢迎回来'}</h1><p className="muted">{!initialized?'首次设置将创建管理员和独立工作区。初始化凭据由实例持有者提供。':'使用内部账号登录，平台账号在后续来源设置中连接。'}</p><ErrorState error={failure}/><form onSubmit={submit}>
    {!initialized&&<><Field label="实例初始化凭据" name="setup_token" type="password"/><Field label="工作区名称" name="workspace_name"/><Field label="你的名字" name="display_name"/></>}
    {invite?<Field label="邀请凭据" name="invitation_token" type="password"/>:<Field label="邮箱" name="email" type="email"/>}
    <Field label="密码" name="password" type="password" minLength={!initialized||invite?12:1}/>{(!initialized||invite)&&<small className="muted">至少12个字符。请勿使用社交平台密码。</small>}
    <button className="primary full" disabled={busy}>{busy?'正在提交…':!initialized?'创建并进入':invite?'设置密码':'登录'}</button>
  </form>{initialized&&<button className="text-button" onClick={()=>{setInvite(!invite);setFailure(null);}}>{invite?'返回登录':'我有成员邀请'}</button>}</section><p className="auth-note">S1 基础系统 · 外部来源与 AI 默认未启用</p></main>;
}
function Shell({me,onLogout}:{me:Me;onLogout:()=>void}){
  const [route,setRoute]=useState(location.hash.slice(1)||'home'),[drawer,setDrawer]=useState<'notifications'|'account'|null>(null),[error,setError]=useState<Error|null>(null);
  useEffect(()=>{const change=()=>setRoute(location.hash.slice(1)||'home');window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  const title=navigation.find(n=>n[0]===route)?.[1]??'工作区设置';
  return <div className="layout"><a className="skip" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>跳到主要内容</a><aside className="sidebar"><a href="#home" className="brand"><span className="logo">Y</span><span>YOYO<small>运营工作台</small></span></a><div className="workspace-label">{me.workspace.name}</div><nav aria-label="主导航">{navigation.map(([key,label,icon])=><a key={key} href={'#'+key} aria-current={key===route?'page':undefined}><span aria-hidden="true">{icon}</span>{label}</a>)}</nav><div className="sidebar-bottom"><a href="#settings" aria-current={route==='settings'?'page':undefined}>⚙ 工作区设置</a><p>创意有序，协作可追溯</p></div></aside><div className="body"><header><div className="breadcrumb">工作区 / <strong>{title}</strong></div><div className="header-actions"><button onClick={()=>setDrawer('notifications')}>通知</button><button onClick={()=>setDrawer('account')}>{me.user.display_name}</button></div></header><main id="main-content" tabIndex={-1}><ErrorState error={error}/>{route==='home'?<Home me={me}/>:route==='settings'?<Settings me={me}/>:<ModulePlaceholder route={route} title={title}/>}</main><footer>YOYO · {me.workspace.timezone} · S1 基础系统</footer></div>{drawer==='notifications'&&<Drawer title="我的通知" onClose={()=>setDrawer(null)}><Notifications/></Drawer>}{drawer==='account'&&<Drawer title="账号与权限" onClose={()=>setDrawer(null)}><p>{me.user.display_name}</p><p className="muted">{me.user.email}</p><p>{me.membership.roles.map(r=>roleNames[r]).join(' / ')}</p><h3>当前能力</h3><p className="muted">权限由服务端验证，成员角色变更即时生效。</p><button onClick={async()=>{try{await api('/auth/logout',{method:'POST'});onLogout();}catch(e){setError(e as Error);}}}>退出登录</button></Drawer>}</div>;
}
function ModulePlaceholder({route,title}:{route:string;title:string}){const description:Record<string,string>={topics:'来源采集和 AI 推荐将在 S3 接入。当前尚未连接真实来源。',contents:'图文与视频制作、内部审核和发布归档将在 S4/S5 开放。',calendar:'月、周、列表视图及活动提醒将在 S6 开放。',reports:'数据导入、可信指标与复盘将在 S7/S8 开放。',assets:'私有文件上传、媒体预览和资产版本管理将在 S2 开放。'};return <><div className="page-heading"><div><p className="eyebrow">YOYO 工作区</p><h1>{title}</h1></div><span className="badge">待接入</span></div><Empty title="这个模块正在准备中">{description[route]??'请通过导航进入工作区。'}</Empty></>;}
function Home({me}:{me:Me}){return <><div className="page-heading"><div><p className="eyebrow">今天，从一件重要的事开始</p><h1>{me.user.display_name}，欢迎回来</h1><p className="muted">基础环境已就绪，业务模块将按阶段接入。</p></div><a className="button" href="#settings">管理工作区</a></div><div className="stats"><article><span>优先任务</span><strong>0</strong><small>暂无业务任务</small></article><article><span>真实数据</span><strong>—</strong><small>尚未导入，不推算指标</small></article><article><span>来源与 AI</span><strong>未启用</strong><small>配置授权和预算后接入</small></article></div><section className="panel"><div className="panel-heading"><h2>接下来的工作</h2><span className="badge">基础系统</span></div><Empty title="工作区已准备好">先配置账号和成员，再逐步接入资产、来源及制作流程。这里将展示最多三件优先任务。</Empty></section><div className="info-strip"><span aria-hidden="true">ⓘ</span><p>关闭网页后，后台任务仍可运行；本地电脑休眠或服务停止时暂停，恢复后的处理遵循任务租约。</p></div></>;}
function Settings({me}:{me:Me}){
  const [tab,setTab]=useState('workspace');const tabs=[['workspace','工作区'],['accounts','运营账号'],['members','成员'],['jobs','后台任务'],['monitor','运行状态'],['audit','审计记录']];
  return <><div className="page-heading"><div><p className="eyebrow">协作与运行</p><h1>工作区设置</h1></div></div><nav className="tabs" aria-label="设置分类">{tabs.filter(([k])=>me.permissions.includes('admin')||['workspace','accounts','jobs'].includes(k!)).map(([k,t])=><button key={k} aria-current={tab===k?'page':undefined} onClick={()=>setTab(k!)}>{t}</button>)}</nav>{tab==='workspace'?<WorkspaceSettings editable={me.permissions.includes('admin')}/>:tab==='accounts'?<Accounts editable={me.permissions.includes('account.edit')} admin={me.permissions.includes('admin')}/>:tab==='members'?<Members/>:tab==='jobs'?<JobList admin={me.permissions.includes('admin')}/>:<DataList path={tab==='monitor'?'/monitor':'/audit-logs'} title={tab==='monitor'?'运行状态':'审计记录'}/>}</>;
}
function useData(path:string){const [data,setData]=useState<any>(null),[error,setError]=useState<Error|null>(null),[loading,setLoading]=useState(true);async function refresh(){setLoading(true);setError(null);try{setData(await api(path));}catch(e){setError(e as Error);}finally{setLoading(false);}}useEffect(()=>{void refresh();},[path]);return {data,error,loading,refresh};}
function WorkspaceSettings({editable}:{editable:boolean}){
  const {data,error,loading,refresh}=useData('/settings');const [failure,setFailure]=useState<Error|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  if(loading)return <Loading/>;if(error)return <ErrorState error={error} retry={()=>void refresh()}/>;
  return <section className="panel narrow"><h2>工作区信息</h2><ErrorState error={failure}/>{notice&&<p role="status">{notice}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setFailure(null);const f=new FormData(e.currentTarget);try{await api('/settings',{method:'PATCH',body:{category:'workspace',settings:{name:f.get('name'),timezone:f.get('timezone')},expected_version:data.version}});setNotice('已保存');await refresh();}catch(e){setFailure(e as Error);}finally{setBusy(false);}}}><fieldset disabled={!editable||busy}><Field label="名称" name="name" defaultValue={data.name}/><Field label="时区" name="timezone" defaultValue={data.timezone}/>{editable&&<button className="primary" disabled={busy}>保存设置</button>}</fieldset></form>{!editable&&<p className="muted">当前角色可查看设置，修改由管理员操作。</p>}</section>;
}
function Accounts({editable,admin}:{editable:boolean;admin:boolean}){
  const {data,error,loading,refresh}=useData('/accounts');const [selected,setSelected]=useState<any>(null),[creating,setCreating]=useState(false),[failure,setFailure]=useState<Error|null>(null),[busy,setBusy]=useState(false);
  return <section className="panel"><div className="panel-heading"><h2>运营账号</h2>{admin&&<button className="primary" onClick={()=>{setCreating(true);setFailure(null);}}>添加账号</button>}</div><ErrorState error={error} retry={()=>void refresh()}/>{loading?<Loading/>:data?.items.length?<div className="table-wrap"><table><thead><tr><th>账号</th><th>平台</th><th>时区</th><th>操作</th></tr></thead><tbody>{data.items.map((a:any)=><tr key={a.id}><td>{a.name}</td><td>{a.platform}</td><td>{a.timezone}</td><td><button onClick={()=>{setSelected(a);setFailure(null);}}>查看{editable?' / 编辑':''}</button></td></tr>)}</tbody></table></div>:<Empty title="还没有运营账号">添加真实平台账号标识，不会自动登录平台或开启采集。</Empty>}{(selected||creating)&&<Drawer title={creating?'添加运营账号':'账号详情'} onClose={()=>{setSelected(null);setCreating(false);}}><ErrorState error={failure}/><form onSubmit={async e=>{e.preventDefault();setBusy(true);setFailure(null);const f=new FormData(e.currentTarget);try{const body=creating?{name:f.get('name'),platform:f.get('platform'),platform_user_id:f.get('platform_user_id'),timezone:f.get('timezone')}:{name:f.get('name'),timezone:f.get('timezone'),expected_version:selected.version};await api(creating?'/accounts':'/accounts/'+selected.id,{method:creating?'POST':'PATCH',body});setCreating(false);setSelected(null);await refresh();}catch(e){setFailure(e as Error);}finally{setBusy(false);}}}><fieldset disabled={!editable||busy}>{creating&&<><label className="field">平台<select name="platform"><option value="xiaohongshu">小红书</option><option value="weibo">微博</option></select></label><Field label="平台内部账号 ID" name="platform_user_id"/></>}<Field label="名称" name="name" defaultValue={selected?.name}/><Field label="时区" name="timezone" defaultValue={selected?.timezone??'Asia/Shanghai'}/>{editable&&<button className="primary">{busy?'保存中…':'保存'}</button>}</fieldset></form></Drawer>}</section>;
}
function Members(){
  const {data,error,loading,refresh}=useData('/members');const [invite,setInvite]=useState(false),[token,setToken]=useState(''),[failure,setFailure]=useState<Error|null>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null);
  return <section className="panel"><div className="panel-heading"><h2>成员与组合角色</h2><button className="primary" onClick={()=>{setInvite(true);setToken('');setFailure(null);}}>邀请成员</button></div><ErrorState error={error}/>{loading?<Loading/>:<div className="table-wrap"><table><thead><tr><th>成员</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{data?.items.map((m:any)=><tr key={m.id}><td>{m.display_name}<small>{m.email}</small></td><td>{m.roles.map((r:string)=>roleNames[r]).join(' / ')}</td><td>{m.active?'有效':'已停用'}</td><td><button onClick={()=>{setSelected(m);setFailure(null);}}>修改权限</button></td></tr>)}</tbody></table></div>}{(invite||selected)&&<Drawer title={invite?'邀请成员':'修改成员权限'} onClose={()=>{setInvite(false);setSelected(null);setToken('');}}><ErrorState error={failure}/>{token?<><p>邀请已创建，有效期24小时。将凭据通过你认可的渠道交给该成员。</p><textarea readOnly aria-label="邀请凭据" value={token}/></>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setFailure(null);const f=new FormData(e.currentTarget);try{if(invite){const r=await api('/members',{method:'POST',body:{email:f.get('email'),display_name:f.get('display_name'),roles:f.getAll('roles')}});setToken(r.invitation_token);}else{await api('/members/'+selected.id,{method:'PATCH',body:{roles:f.getAll('roles'),active:f.get('active')==='on',expected_version:selected.version,...(f.get('successor_id')?{successor_id:f.get('successor_id')}:{})}});setSelected(null);}await refresh();}catch(e){setFailure(e as Error);}finally{setBusy(false);}}}><fieldset disabled={busy}>{invite&&<><Field label="邮箱" name="email" type="email"/><Field label="显示名称" name="display_name"/></>}<fieldset className="role-options"><legend>角色（可多选）</legend>{Object.entries(roleNames).map(([r,t])=><label key={r}><input name="roles" type="checkbox" value={r} defaultChecked={selected?.roles.includes(r)??r==='viewer'}/>{t}</label>)}</fieldset>{selected&&<><label className="checkbox"><input name="active" type="checkbox" defaultChecked={selected.active}/>成员有效</label><label className="field">停用时的账号接替人<select name="successor_id"><option value="">无接替人</option>{data?.items.filter((m:any)=>m.active&&m.id!==selected.id).map((m:any)=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label></>}<button className="primary">{busy?'提交中…':invite?'创建邀请':'保存权限'}</button></fieldset></form>}</Drawer>}</section>;
}
function Notifications(){const {data,error,loading,refresh}=useData('/notifications');return <><ErrorState error={error} retry={()=>void refresh()}/>{loading?<Loading/>:data?.items.length?<ul className="notification-list">{data.items.map((n:any)=><li key={n.id}><h3>{n.title}</h3><p>{new Date(n.created_at).toLocaleString('zh-CN')}</p><span>{n.superseded_at?'已失效':n.read_at?'已读':'未读'}</span>{!n.read_at&&<button onClick={async()=>{await api('/notifications/'+n.id+'/read',{method:'POST'});await refresh();}}>标为已读</button>}</li>)}</ul>:<Empty title="暂无通知">任务结果与需要处理的事项会出现在这里。</Empty>}</>;}
function JobList({admin}:{admin:boolean}){
  const {data,error,loading,refresh}=useData('/jobs');const [failure,setFailure]=useState<Error|null>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null);
  async function act(fn:()=>Promise<unknown>){setFailure(null);setBusy(true);try{await fn();await refresh();}catch(e){setFailure(e as Error);}finally{setBusy(false);}}
  return <section className="panel"><div className="panel-heading"><h2>后台任务</h2><div className="actions"><button disabled={busy} onClick={()=>void refresh()}>刷新</button>{admin&&<button className="primary" disabled={busy} onClick={()=>void act(()=>api('/diagnostics',{method:'POST',body:{pool:'general'}}))}>运行检查</button>}{admin&&<button disabled={busy} onClick={()=>void act(()=>api('/diagnostics',{method:'POST',body:{pool:'reminder'}}))}>提醒通道检查</button>}</div></div><ErrorState error={failure??error}/>{loading?<Loading/>:data?.items.length?<div className="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>执行池</th><th>尝试</th><th>操作</th></tr></thead><tbody>{data.items.map((j:any)=><tr key={j.id}><td>{j.type}</td><td><JobStatus state={j.state}/></td><td>{j.pool}</td><td>{j.attempts}</td><td><button onClick={()=>setSelected(j)}>详情</button>{['queued','running'].includes(j.state)&&<button disabled={busy} onClick={()=>void act(()=>api('/jobs/'+j.id+'/cancel',{method:'POST',body:{reason:'用户取消'}}))}>取消</button>}{admin&&j.state==='failed'&&<button disabled={busy} onClick={()=>void act(()=>api('/jobs/'+j.id+'/retry',{method:'POST',body:{reason:'管理员重试'}}))}>重试</button>}</td></tr>)}</tbody></table></div>:<Empty title="暂无后台任务">运行检查可验证持久任务链路。任务状态由服务端返回。</Empty>}{selected&&<Drawer title="任务详情" onClose={()=>setSelected(null)}><JobStatus state={selected.state}/><dl><dt>任务编号</dt><dd>{selected.id}</dd><dt>错误代码</dt><dd>{selected.error_code??'无'}</dd><dt>请求编号</dt><dd>{selected.request_id}</dd></dl><p className="muted">失败不会覆盖业务输入；输入版本过期的结果会被拒绝。</p></Drawer>}</section>;
}
function DataList({path,title}:{path:string;title:string}){const {data,error,loading,refresh}=useData(path);return <section className="panel"><div className="panel-heading"><h2>{title}</h2><button onClick={()=>void refresh()}>刷新</button></div><ErrorState error={error}/>{loading?<Loading/>:path==='/monitor'?<><h3>进程健康</h3><div className="table-wrap"><table><thead><tr><th>进程</th><th>执行池</th><th>健康</th></tr></thead><tbody>{data?.processes.map((p:any)=><tr key={p.name}><td>{p.name}</td><td>{p.pool}</td><td>{p.healthy?'正常':'未响应'}</td></tr>)}</tbody></table></div><p>待分发事件：{data?.outbox_pending??0}</p><h3>任务分布</h3>{data?.jobs.map((j:any)=><p key={j.pool+j.state}>{j.pool} · <JobStatus state={j.state}/> · {j.count}项</p>)}<p className="muted">AI/OCR 未启用，来源待验证。</p></>:data?.items.length?<div className="table-wrap"><table><thead><tr><th>时间</th><th>动作</th><th>对象</th><th>请求编号</th></tr></thead><tbody>{data.items.map((a:any)=><tr key={a.id}><td>{new Date(a.occurred_at).toLocaleString('zh-CN')}</td><td>{a.action}</td><td>{a.object_type}</td><td className="mono">{a.request_id}</td></tr>)}</tbody></table></div>:<Empty title="暂无记录">关键写操作以追加方式记录，凭据不会进入审计内容。</Empty>}</section>;}
createRoot(document.getElementById('root')!).render(<App/>);
