import React,{useState,useEffect} from 'react';
import {api} from './api';
import {ErrorState} from './components';
import type {SessionData} from '../../../packages/contracts/src/types';
export function ProductionActions({content,me,onSaved,canAct}:{content:any;me:SessionData;onSaved:()=>Promise<void>;canAct:()=>boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState<Error|null>(null),[checked,setChecked]=useState<string[]>([]),[comment,setComment]=useState(''),[exported,setExported]=useState<any>(null),[notice,setNotice]=useState(''),[publication,setPublication]=useState({platform_note_id:'',url:'',published_at:'',traffic_type:'unknown',is_campaign:false,verification_note:'',confirmed:false});
 const production=me.permissions.includes('content.production'),reviewer=me.permissions.includes('review'),pending=content.reviews.find((r:any)=>r.status==='pending');
 useEffect(()=>{if(!exported?.id||['ready','failed','cancelled'].includes(exported.state))return;const timer=setInterval(()=>{void api('/export-packages/'+exported.id).then(setExported).catch(e=>setError(e as Error));},1000);return ()=>clearInterval(timer);},[exported?.id,exported?.state]);
 async function exportPackage(){setBusy(true);setError(null);try{setExported(await api('/contents/'+content.id+'/export-package',{method:'POST',body:{approved_revision_id:content.approved_revision_id}}));}catch(e){setError(e as Error);}finally{setBusy(false);}}
 async function download(){setError(null);try{const r=await api('/export-packages/'+exported.id+'/download');const link=document.createElement('a');link.href=r.url;link.click();}catch(e){setError(e as Error);}}
 async function record(draft:boolean){if(!canAct()){setError(new Error('请先保存或放弃未保存的图文修改'));return;}setBusy(true);setError(null);try{const fields={platform_note_id:publication.platform_note_id,url:publication.url,...(publication.published_at?{published_at:new Date(publication.published_at).toISOString()}:{}),traffic_type:publication.traffic_type,is_campaign:publication.is_campaign};
 if(draft){await api('/publication-drafts',{method:'POST',body:{content_id:content.id,revision_id:content.approved_revision_id,partial_fields:fields,verification_note:publication.verification_note}});setNotice('发布信息已暂存，尚未登记发布');}else{await api('/publications',{method:'POST',body:{content_id:content.id,account_id:content.account_id,approved_revision_id:content.approved_revision_id,...fields}});setNotice('实际发布已登记');await onSaved();}}catch(e){setError(e as Error);}finally{setBusy(false);}}
 async function act(path:string,body:any){if(!canAct()){setError(new Error('请先保存或放弃未保存的图文修改'));return;}setBusy(true);setError(null);try{await api(path,{method:'POST',body});await onSaved();setComment('');setChecked([]);}catch(e){setError(e as Error);}finally{setBusy(false);}}
 return <section className="panel"><h3>内部审核</h3><ErrorState error={error}/>{notice&&<p role="status">{notice}</p>}{production&&['draft','in_production'].includes(content.business_status)&&<button disabled={busy} onClick={()=>void act('/contents/'+content.id+'/submit-review',{revision_id:content.current_revision_id,expected_version:content.version})}>提交内部审核</button>}
 {pending&&<><p>待审快照 {content.current_revision.revision_no} · 哈希 {pending.payload_hash}</p><p>请核对当前冻结版本。批准后更换文案或图片会重新进入制作。</p><label className="field">审核意见<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={10000}/></label>{reviewer&&<><fieldset disabled={busy}>{['已核对图片原件与页序','已核对公开文案与素材许可'].map(label=><label key={label}><input type="checkbox" checked={checked.includes(label)} onChange={e=>setChecked(old=>e.target.checked?[...old,label]:old.filter(v=>v!==label))}/>{label}</label>)}</fieldset><button disabled={busy||checked.length!==2} onClick={()=>void act('/reviews/'+pending.id+'/decide',{decision:'approve',checklist:checked,comment,revision_id:pending.revision_id,expected_version:pending.version})}>批准此冻结版本</button><button disabled={busy||!comment.trim()} onClick={()=>void act('/reviews/'+pending.id+'/decide',{decision:'reject',checklist:['人工退回'],comment,revision_id:pending.revision_id,expected_version:pending.version})}>退回修改</button></>}{production&&(me.membership.roles.includes('admin')||pending.requester_id===me.membership.id)&&<button disabled={busy||!comment.trim()} onClick={()=>void act('/reviews/'+pending.id+'/withdraw',{reason:comment,expected_version:pending.version})}>撤回审核</button>}</>}
 {content.reviews.filter((r:any)=>r.status!=='pending').map((r:any)=><details key={r.id}><summary>{({approved:'已批准',rejected:'已退回',withdrawn:'已撤回',stale:'已失效'} as Record<string,string>)[r.status]} · {new Date(r.decided_at).toLocaleString('zh-CN')}</summary><p>版本 {r.revision_id} · 哈希 {r.payload_hash}</p><p>{r.comment}</p><p>{r.checklist.join('；')}</p></details>)}
 {content.business_status==='ready_to_publish'&&<><h3>发布包与实际发布</h3><p>批准快照 {content.current_revision.revision_no}。请在平台人工发布后核对登记。</p>{me.permissions.includes('download.original')&&<><button disabled={busy} onClick={()=>void exportPackage()}>生成批准版本发布包</button>{exported&&<><p role="status">发布包：{({queued:'排队中',running:'生成中',ready:'已完成',failed:'生成失败',cancelled:'已取消'} as Record<string,string>)[exported.state]??'排队中'} {exported.error_code??''}</p><button disabled={exported.state!=='ready'} onClick={()=>void download()}>下载批准版本发布包</button></>}</>}
 {me.permissions.includes('operate')&&<form onSubmit={e=>{e.preventDefault();void record(false);}}><fieldset disabled={busy}><label className="field">平台笔记ID<input value={publication.platform_note_id} maxLength={200} required onChange={e=>setPublication({...publication,platform_note_id:e.target.value})}/></label><label className="field">实际发布链接<input type="url" required value={publication.url} onChange={e=>setPublication({...publication,url:e.target.value})}/></label><label className="field">实际发布时间<input type="datetime-local" required value={publication.published_at} onChange={e=>setPublication({...publication,published_at:e.target.value})}/></label><label>流量类型<select value={publication.traffic_type} onChange={e=>setPublication({...publication,traffic_type:e.target.value})}><option value="unknown">未知</option><option value="organic">自然</option><option value="paid">投放</option><option value="mixed">混合</option></select></label><label><input type="checkbox" checked={publication.is_campaign} onChange={e=>setPublication({...publication,is_campaign:e.target.checked})}/>活动内容</label><label className="field">发布核对说明<textarea value={publication.verification_note} maxLength={10000} onChange={e=>setPublication({...publication,verification_note:e.target.value})}/></label><button type="button" disabled={!publication.verification_note.trim()} onClick={()=>void record(true)}>暂存待核对发布信息</button><label><input type="checkbox" checked={publication.confirmed} onChange={e=>setPublication({...publication,confirmed:e.target.checked})}/>已人工核对平台账号、笔记ID及批准成品</label><button disabled={!publication.confirmed}>登记实际发布</button></fieldset></form>}</>}
 </section>;
}
