import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
const project='yoyo-s2-smoke',origin='http://localhost:3012';let cookie='',csrf='';
const state=JSON.parse(execFileSync('docker',['compose','-p',project,'exec','-T','api','node','-e',"process.stdout.write(require('fs').readFileSync('/state/instance.json','utf8'))"],{encoding:'utf8'}));
async function call(path,method='GET',body){const r=await fetch(origin+'/api/v1'+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,...(method==='GET'?{}:{Origin:origin,'X-CSRF-Token':csrf,'Idempotency-Key':randomUUID()})},...(method==='GET'?{}:{body:JSON.stringify(body??{})})});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];const j=await r.json();if(j.data?.csrf_token)csrf=j.data.csrf_token;if(!r.ok)throw new Error(`${method} ${path} ${r.status} ${j.error?.code}`);return j.data;}
await call('/auth/csrf');const setup=await call('/setup/status');if(!setup.initialized)await call('/setup','POST',{setup_token:state.setup_token,email:'compose-s2@example.test',password:'Compose-S2-only-test-987',display_name:'Compose验收',workspace_name:'专用S2验收'});
await call('/auth/login','POST',{email:'compose-s2@example.test',password:'Compose-S2-only-test-987'});const me=await call('/me');
async function upload(path,name,purpose,mime){const b=readFileSync(path),sha256=createHash('sha256').update(b).digest('hex');const u=await call('/uploads','POST',{name,purpose,size_bytes:b.length,mime_hint:mime,sha256});const parts=[];
 for(let n=1;n<=Math.ceil(b.length/u.part_size);n++){const chunk=b.subarray((n-1)*u.part_size,n*u.part_size),checksum=createHash('sha256').update(chunk).digest('hex');const p=await call(`/uploads/${u.id}/parts`,'POST',{part_number:n,checksum});const r=await fetch(origin+p.upload_url,{method:'PUT',headers:{Cookie:cookie,Origin:origin,'X-CSRF-Token':csrf,'Content-Type':'application/octet-stream'},body:chunk});assert.equal(r.status,200);parts.push((await r.json()).data);}
 return await call(`/uploads/${u.id}/complete`,'POST',{parts_manifest:parts});}
const png=await upload('tests/fixtures/transparent.png','Compose透明.png','asset','image/png');const asset=await call('/assets','POST',{name:'Compose透明.png',category:'2d',ip_identity:'验收',owner_id:me.membership.id,source:'合成测试，非生产授权',source_file_id:png.id});
const pdf=await upload('tests/fixtures/guideline.pdf','Compose规范.pdf','guideline','application/pdf');let ready=false;
for(let n=0;n<60;n++){const a=await call('/assets/'+asset.id),f=await call('/guideline-files/'+pdf.id);if(a.versions[0].file.preview_status==='ready'&&f.preview_status==='ready'){assert.equal(a.versions[0].file.metadata.has_alpha,true);assert.equal(f.metadata.pages,1);ready=true;break;}await new Promise(r=>setTimeout(r,500));}assert.ok(ready,'Default Compose media worker must finish both jobs');
const preview=await call('/files/'+png.id+'/preview'),image=await fetch(preview.url);assert.equal(image.status,200);await image.arrayBuffer();const download=await call('/files/'+png.id+'/download'),raw=await fetch(download.url);assert.equal(createHash('sha256').update(Buffer.from(await raw.arrayBuffer())).digest('hex'),png.sha256);
const rules=await call('/rule-sets','POST',{edition:'Compose合成规范验收',source_file_id:pdf.id,rules:[{category:'color',rule_text:'合成演练',source_page:1,severity:'required',uncertainty_note:'测试'}]});assert.equal((await call('/rule-sets/'+rules.id+'/activate','POST',{checklist:['核对测试页'],expected_version:1})).status,'active');
const internal=JSON.parse(execFileSync('docker',['network','inspect',project+'_media'],{encoding:'utf8'}));assert.equal(internal[0].Internal,true);
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.getByLabel('邮箱').fill('compose-s2@example.test');await page.getByLabel('密码',{exact:false}).fill('Compose-S2-only-test-987');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('link',{name:'IP 资产库'}).click();await page.getByRole('button',{name:'PNG 素材 Compose透明.png',exact:true}).first().click();await page.getByRole('img',{name:'Compose透明.png'}).waitFor();await page.waitForFunction(()=>[...document.images].some(img=>img.alt==='Compose透明.png'&&img.naturalWidth>0));assert.deepEqual(errors,[]);await page.screenshot({path:'docs/evidence/s2/screenshots/compose-real-preview.png'});}finally{await browser.close();}
writeFileSync('docs/evidence/s2/compose-smoke.json',JSON.stringify({checked_at:new Date().toISOString(),profile:project,full_default_compose_ready:true,api_upload_to_real_storage:true,media_worker_generated_png_alpha_and_pdf_pages:true,browser_reachable_preview_and_original_sha256:true,rules_manual_activation:true,media_network_internal:true,default_static_site_csp_allows_only_configured_storage_image_origin:true,chromium_loaded_preview_pixels:true,fixtures:'synthetic PNG and one-page PDF, isolated smoke instance',published:false},null,2)+'\n');
console.log('PASS default Compose: private storage, PNG/PDF media worker, preview/download hash, rule activation, internal media network');
