import {readFileSync,writeFileSync,mkdirSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Database} from '../../packages/db/src/db';
import {migrate} from '../../packages/db/src/migrate';
import {sha,canonical} from '../../packages/domain/src/protocol';
const c=JSON.parse(readFileSync('.local/state/instance.json','utf8'));
const url=(name:string)=>`postgresql://yoyo:${c.database_password}@127.0.0.1:54329/${name}`;
const admin=new Database(url('postgres')),source=new Database(url('yoyo_test'));
async function snapshot(db:Database){const tables=(await db.query("SELECT schemaname,tablename FROM pg_tables WHERE schemaname IN ('public','retired') ORDER BY schemaname,tablename")).rows;const counts:Record<string,number>={};for(const t of tables)counts[t.schemaname+'.'+t.tablename]=(await db.query(`SELECT count(*)::int n FROM ${t.schemaname}.${t.tablename}`)).rows[0].n;const identities=(await db.query('SELECT id,workspace_id,account_id,platform_note_id,url,published_at,recorded_by FROM publications ORDER BY id')).rows;const files=(await db.query('SELECT id,account_id,object_key,sha256 FROM file_objects ORDER BY id')).rows;return {counts,publication_identity_hash:sha(canonical(identities)),file_identity_hash:sha(canonical(files))};}
async function main(){mkdirSync('.local/s7-backups',{recursive:true,mode:0o700});const stamp=Date.now(),before=await snapshot(source),dump=execFileSync('docker',['exec','yoyo-dev-db-1','pg_dump','-U','yoyo','-Fc','yoyo_test'],{maxBuffer:100*1024*1024});writeFileSync(`.local/s7-backups/yoyo_test-${stamp}.dump`,dump,{flag:'wx',mode:0o600});const name=`yoyo_s7_upgrade_${stamp}_test`;await admin.query('CREATE DATABASE '+name);execFileSync('docker',['exec','-i','yoyo-dev-db-1','pg_restore','-U','yoyo','--no-owner','-d',name],{input:dump,maxBuffer:100*1024*1024,stdio:['pipe','pipe','pipe']});const copy=new Database(url(name));try{await migrate(copy);await migrate(copy);const after=await snapshot(copy);for(const [table,count] of Object.entries(before.counts)){if(table==='public.schema_migrations')continue;assert.equal(after.counts[table],count,table);}assert.equal(after.publication_identity_hash,before.publication_identity_hash);assert.equal(after.file_identity_hash,before.file_identity_hash);assert.deepEqual(await snapshot(source),before);for(const file of readdirSync('packages/db/migrations').filter(n=>/^0(0\d|1\d|2[0-6])-/.test(n))){const base=execFileSync('git',['show','57164a2:packages/db/migrations/'+file]);assert.equal(sha(base.toString()),sha(readFileSync('packages/db/migrations/'+file,'utf8')));}const actual=new Database(url('yoyo'));try{assert.equal((await actual.query('SELECT count(*)::int n FROM schema_migrations')).rows[0].n,8);}finally{await actual.close();}const report={date:'2026-10-10',source:'yoyo_test',copy:name,backup_sha256:createHash('sha256').update(dump).digest('hex'),before,after,original_preserved:true,actual_yoyo_migrations:8,historical_001_026_unchanged:true,repeat_upgrade:'passed',result:'passed'};writeFileSync('docs/evidence/s7/migration-verification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({copy:name,result:'passed',source_preserved:true}));}finally{await copy.close();}}
main().catch(e=>{console.error('S7_MIGRATION_FAILED',e.code??e.message);process.exitCode=1;}).finally(async()=>{await source.close();await admin.close();});
