import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync,spawn} from 'node:child_process';
import {Database} from '../../packages/db/src/db';
import {migrate} from '../../packages/db/src/migrate';
import {createHash} from 'node:crypto';
import {canonical,sha} from '../../packages/domain/src/protocol';
import {passwordHash} from '../../apps/api/src/auth';
import assert from 'node:assert/strict';
const config=JSON.parse(readFileSync('.local/state/instance.json','utf8')),name='yoyo_s11_rollback_test';
const backup='.local/s11-backups/yoyo-dev-db-1-yoyo_test.dump',url=`postgresql://yoyo:${config.database_password}@127.0.0.1:54329/${name}`;
function restore(){execFileSync('docker',['exec','yoyo-dev-db-1','dropdb','-U','yoyo','--if-exists',name]);execFileSync('docker',['exec','yoyo-dev-db-1','createdb','-U','yoyo',name]);execFileSync('docker',['exec','-i','yoyo-dev-db-1','pg_restore','-U','yoyo','-d',name,'--no-owner'],{input:readFileSync(backup),stdio:['pipe','pipe','pipe']});}
async function identity(db:Database){return sha(canonical((await db.query('SELECT id,workspace_id,account_id,platform_note_id,url,published_at,recorded_by FROM publications ORDER BY id')).rows));}
async function main(){restore();let db=new Database(url);const before=await identity(db);await migrate(db);assert.equal(await identity(db),before);await db.close();restore();db=new Database(url);assert.equal(await identity(db),before);assert.equal((await db.query('SELECT count(*)::int n FROM schema_migrations')).rows[0].n,24);assert.equal((await db.query('SELECT count(*)::int n FROM publications')).rows[0].n,5);
 const workspace=(await db.query('SELECT id FROM workspaces LIMIT 1')).rows[0].id;const user=(await db.query("INSERT INTO users(email,display_name,password_hash) VALUES('rollback-proof@example.invalid','明确合成回滚验证',$1) RETURNING id",[await passwordHash('Synthetic-rollback-password-987')])).rows[0].id;await db.query("INSERT INTO memberships(workspace_id,user_id,roles) VALUES($1,$2,ARRAY['admin'])",[workspace,user]);
 const app=spawn('pnpm',['exec','tsx','--tsconfig','.local/s11-rollback-app/tsconfig.json','.local/s11-rollback-app/apps/api/src/main.ts'],{stdio:['ignore','ignore','pipe'],env:{...process.env,DATABASE_URL:url,PORT:'59003',APP_ORIGIN:'http://127.0.0.1:59003'}});
 app.stderr?.on('data',b=>process.stderr.write(b));
 try{let ready=false;for(let i=0;i<100;i++){try{ready=(await fetch('http://127.0.0.1:59003/api/v1/health')).ok;}catch{}if(ready)break;await new Promise(r=>setTimeout(r,100));}assert.ok(ready);let cookie='';const call=async(path:string,body?:unknown)=>{const r=await fetch('http://127.0.0.1:59003/api/v1'+path,{method:body?'POST':'GET',headers:{Cookie:cookie,'Content-Type':'application/json',...(body?{Origin:'http://127.0.0.1:59003','X-CSRF-Token':csrf}: {})},...(body?{body:JSON.stringify(body)}:{})});const c=r.headers.get('set-cookie');if(c)cookie=c.split(';')[0]!;assert.ok(r.ok);return (await r.json()).data;};let csrf=(await call('/auth/csrf')).csrf_token;await call('/auth/login',{email:'rollback-proof@example.invalid',password:'Synthetic-rollback-password-987'});const ids=(await db.query('SELECT id FROM publications ORDER BY id')).rows;for(const p of ids){const publication=await call('/publications/'+p.id);assert.ok(publication.content_id&&publication.revision_id&&publication.current_revision);}
 writeFileSync('docs/evidence/s11/rollback-verification.json',JSON.stringify({checked_at:new Date().toISOString(),isolated_database:name,backup_sha256:createHash('sha256').update(readFileSync(backup)).digest('hex'),base_application:'e4bd051',upgrade_migrations:26,restore_migrations:24,publication_identity_hash:before,old_publications_read_by_original_api:5,old_relations_restored:true,production_instances_modified:false,scope:'stopped writes, restored DB backup; original object volumes remain untouched; object restore verified separately'},null,2)+'\n');console.log('ROLLBACK_PASSED');
 }finally{app.kill('SIGTERM');if(app.exitCode===null)await new Promise(r=>app.once('exit',r));await db.close();}}
main().catch(e=>{console.error('ROLLBACK_FAILED',e.stack??e.code??e.message);process.exitCode=1;});
