import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,text,uuid,version,authorize,pagination,page} from '../../../packages/domain/src/protocol';
import {audit,Commands} from './commands';
import {Files} from './files';
const category=z.enum(['2d','render']);
const fields={name:text(),category,ip_identity:text(),folder_id:uuid.nullable().optional(),tags:z.array(text()).max(100).optional(),owner_id:uuid,source:text(10000),series:z.string().trim().max(200).optional()};
export class Assets {
 constructor(readonly db:Database,readonly files:Files){}
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,assetId:string,lock=false){const r=await q.query(`SELECT * FROM assets WHERE id=$1 AND workspace_id=$2 ${lock?'FOR UPDATE':''}`,[parse(uuid,assetId),a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','资产不存在或不可见');return r.rows[0];}
 checkVersion(row:Record<string,any>,v:number){if(row.version!==v)throw new AppError(409,'VERSION_CONFLICT','对象已被其他人修改',{version:row.version});}
 async references(tx:Tx,a:Actor,b:{owner_id?:string;folder_id?:string|null}){
  if(b.owner_id){const r=await tx.query('SELECT id FROM memberships WHERE workspace_id=$1 AND id=$2 AND active FOR SHARE',[a.workspaceId,b.owner_id]);if(!r.rowCount)throw new AppError(422,'OWNER_INVALID','负责人须为当前工作区有效成员');}
  if(b.folder_id){const r=await tx.query('SELECT id FROM folders WHERE workspace_id=$1 AND id=$2 FOR SHARE',[a.workspaceId,b.folder_id]);if(!r.rowCount)throw new AppError(422,'FOLDER_INVALID','文件夹不存在或不可见');}
 }
 async ready(tx:Tx,a:Actor,fid:string){const f=await this.files.file(tx,a,fid);if(f.file_status!=='ready')throw new AppError(422,'FILE_NOT_READY','原件尚未就绪');return f;}
 async list(a:Actor,q:Record<string,unknown>){
  const {limit,cursor}=pagination(q);const c=q.category?parse(category,q.category):null;const search=q.q?parse(text(200),q.q):null;const tag=q.tag?parse(text(200),q.tag):null;const folder=q.folder_id?parse(uuid,q.folder_id):null;
  const r=await this.db.query(`SELECT a.*,f.original_name,f.detected_mime,f.preview_status,f.preview_file_id,av.source_file_id,av.usage_scope,EXISTS(SELECT 1 FROM asset_favorites af WHERE af.asset_id=a.id AND af.membership_id=$9) favorite FROM assets a JOIN asset_versions av ON av.id=a.current_version_id JOIN file_objects f ON f.id=av.source_file_id WHERE a.workspace_id=$1 AND ($2::text IS NULL OR a.category=$2) AND ($3::text IS NULL OR strpos(lower(a.name||' '||a.ip_identity||' '||a.series||' '||array_to_string(a.tags,' ')||' '||COALESCE(f.metadata->>'text','')),lower($3))>0) AND ($4::text IS NULL OR $4=ANY(a.tags)) AND ($5::uuid IS NULL OR a.folder_id=$5) AND ($6::timestamptz IS NULL OR (a.created_at,a.id)<($6,$7::uuid)) AND ($8::boolean=false OR EXISTS(SELECT 1 FROM asset_favorites af WHERE af.asset_id=a.id AND af.membership_id=$9)) ORDER BY a.created_at DESC,a.id DESC LIMIT $10`,[a.workspaceId,c,search,tag,folder,cursor?.at??null,cursor?.id??null,q.favorite==='true',a.memberId,limit+1]);return page(r.rows,limit);
 }
 async detail(a:Actor,aid:string){const asset=await this.scope(this.db,a,aid);const r=await this.db.query('SELECT * FROM asset_versions WHERE asset_id=$1 AND workspace_id=$2 ORDER BY version_no DESC',[asset.id,a.workspaceId]);const versions=[];for(const v of r.rows){const file=await this.files.file(this.db,a,v.source_file_id);versions.push({...v,preview_status:file.preview_status,file});}const relations=await this.db.query('SELECT ar.*,fa.name from_name,ta.name to_name,fv.version_no from_version_no,tv.version_no to_version_no FROM asset_relations ar JOIN asset_versions fv ON fv.id=ar.from_version_id JOIN assets fa ON fa.id=fv.asset_id JOIN asset_versions tv ON tv.id=ar.to_version_id JOIN assets ta ON ta.id=tv.asset_id WHERE (fv.asset_id=$1 OR tv.asset_id=$1) AND ar.workspace_id=$2',[aid,a.workspaceId]);return {...asset,versions,relations:relations.rows};}
 async create(tx:Tx,a:Actor,input:unknown){
  const b=parse(z.object({...fields,source_file_id:uuid}).strict(),input);await this.references(tx,a,b);const original=await this.ready(tx,a,b.source_file_id);if(original.detected_mime!=='image/png')throw new AppError(422,'ASSET_FORMAT_INVALID','本版素材须为PNG');
  const r=await tx.query('INSERT INTO assets(workspace_id,created_by,name,category,ip_identity,folder_id,tags,owner_id,source,series) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[a.workspaceId,a.memberId,b.name,b.category,b.ip_identity,b.folder_id??null,b.tags??[],b.owner_id,b.source,b.series??'']);const asset=r.rows[0];
  const v=await tx.query('INSERT INTO asset_versions(workspace_id,created_by,asset_id,version_no,source_file_id) VALUES($1,$2,$3,1,$4) RETURNING id',[a.workspaceId,a.memberId,asset.id,b.source_file_id]);await tx.query('UPDATE assets SET current_version_id=$1 WHERE id=$2',[v.rows[0].id,asset.id]);await audit(tx,a,'asset.create','asset',asset.id);return {status:201,data:{...asset,current_version_id:v.rows[0].id}};
 }
 async patch(tx:Tx,a:Actor,aid:string,input:unknown){
  const b=parse(z.object(fields).partial().extend({expected_version:version}).strict(),input);const asset=await this.scope(tx,a,aid,true);this.checkVersion(asset,b.expected_version);await this.references(tx,a,b);
  const changes=Object.entries(b).filter(([k])=>k!=='expected_version');if(!changes.length)return {status:200,data:asset};const values=changes.map(([,v])=>v);const sets=changes.map(([k],i)=>`${k}=$${i+1}`);values.push(asset.id);const r=await tx.query(`UPDATE assets SET ${sets.join(',')},version=version+1,updated_at=now() WHERE id=$${values.length} RETURNING *`,values);await audit(tx,a,'asset.update','asset',aid,{fields:changes.map(([k])=>k)});return {status:200,data:r.rows[0]};
 }
 async newVersion(tx:Tx,a:Actor,aid:string,input:unknown){
  const b=parse(z.object({source_file_id:uuid,usage_scope:z.string().max(10000),dependencies:z.array(uuid).max(100),preview_file_id:uuid.nullable().optional(),base_version:version,valid_until:z.iso.datetime({offset:true}).nullable().optional(),software:text().optional()}).strict(),input);const asset=await this.scope(tx,a,aid,true);this.checkVersion(asset,b.base_version);const original=await this.ready(tx,a,b.source_file_id);if(original.detected_mime!=='image/png')throw new AppError(422,'ASSET_FORMAT_INVALID','本版素材须为PNG');if(b.preview_file_id){const f=await this.ready(tx,a,b.preview_file_id);if(!['image/png'].includes(f.detected_mime))throw new AppError(422,'PREVIEW_INVALID','配套预览须为可显示媒体');}
  for(const dep of b.dependencies){const v=await tx.query('SELECT id FROM asset_versions WHERE id=$1 AND workspace_id=$2',[dep,a.workspaceId]);if(!v.rowCount)throw new AppError(422,'DEPENDENCY_INVALID','来源版本不存在或不可见');}
  const prev=(await tx.query('SELECT version_no FROM asset_versions WHERE id=$1',[asset.current_version_id])).rows[0];
  const r=await tx.query('INSERT INTO asset_versions(workspace_id,created_by,asset_id,version_no,source_file_id,preview_file_id,parent_version_id,usage_scope,dependencies,valid_until,software) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[a.workspaceId,a.memberId,aid,prev.version_no+1,b.source_file_id,b.preview_file_id??null,asset.current_version_id,b.usage_scope,b.dependencies,b.valid_until??null,b.software??null]);
  await tx.query("UPDATE assets SET current_version_id=$1,business_status='pending_confirmation',retired_reason=NULL,retired_at=NULL,version=version+1,updated_at=now() WHERE id=$2",[r.rows[0].id,aid]);await audit(tx,a,'asset.version','asset',aid,{version_id:r.rows[0].id});return {status:201,data:r.rows[0]};
 }
 async confirmVersion(tx:Tx,a:Actor,vid:string,input:unknown){
  const b=parse(z.object({usage_scope:text(10000),checklist:z.array(text()).min(1),expected_version:version}).strict(),input);const v=(await tx.query('SELECT * FROM asset_versions WHERE id=$1 AND workspace_id=$2',[parse(uuid,vid),a.workspaceId])).rows[0];if(!v)throw new AppError(404,'NOT_FOUND','素材版本不可见');const asset=await this.scope(tx,a,v.asset_id,true);this.checkVersion(v,b.expected_version);if(asset.current_version_id!==vid)throw new AppError(409,'VERSION_CONFLICT','当前素材版本已变化');const result=await this.confirm(tx,a,asset.id,{...b,expected_version:asset.version});const confirmed=(await tx.query('SELECT * FROM asset_versions WHERE id=$1',[result.data.current_version_id])).rows[0];return {status:200,data:confirmed};
 }
 async relations(a:Actor,q:Record<string,unknown>){const {limit,cursor}=pagination(q);const from=q.from_version_id?parse(uuid,q.from_version_id):null,to=q.to_version_id?parse(uuid,q.to_version_id):null;const r=await this.db.query('SELECT * FROM asset_relations WHERE workspace_id=$1 AND ($2::uuid IS NULL OR from_version_id=$2) AND ($3::uuid IS NULL OR to_version_id=$3) AND ($4::timestamptz IS NULL OR (created_at,id)<($4,$5::uuid)) ORDER BY created_at DESC,id DESC LIMIT $6',[a.workspaceId,from,to,cursor?.at??null,cursor?.id??null,limit+1]);return page(r.rows,limit);}
 async confirm(tx:Tx,a:Actor,aid:string,input:unknown){
  const b=parse(z.object({usage_scope:text(10000),checklist:z.array(text()).min(1),expected_version:version}).strict(),input);const asset=await this.scope(tx,a,aid,true);this.checkVersion(asset,b.expected_version);if(asset.business_status==='retired')throw new AppError(409,'ASSET_RETIRED','停用资产须建立新版本后重新确认');
  const prev=(await tx.query('SELECT * FROM asset_versions WHERE id=$1',[asset.current_version_id])).rows[0];const file=await this.ready(tx,a,prev.source_file_id);if(file.preview_status!=='ready')throw new AppError(422,'PREVIEW_NOT_READY','PNG须通过解析并生成预览后确认');
  if(prev.valid_until&&new Date(prev.valid_until).getTime()<=Date.now())throw new AppError(422,'PERMISSION_EXPIRED','素材使用依据已过期');
  const v=await tx.query('INSERT INTO asset_versions(workspace_id,created_by,asset_id,version_no,source_file_id,preview_file_id,parent_version_id,usage_scope,dependencies,valid_until,software,permission_confirmed_by,permission_confirmed_at,checklist) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$2,now(),$12) RETURNING id',[a.workspaceId,a.memberId,aid,prev.version_no+1,prev.source_file_id,prev.preview_file_id,prev.id,b.usage_scope,prev.dependencies,prev.valid_until,prev.software,b.checklist]);
  const r=await tx.query("UPDATE assets SET current_version_id=$1,business_status='usable',version=version+1,updated_at=now() WHERE id=$2 RETURNING *",[v.rows[0].id,aid]);await audit(tx,a,'asset.confirm','asset',aid,{checklist:b.checklist,version_id:v.rows[0].id});return {status:200,data:r.rows[0]};
 }
 async retire(tx:Tx,a:Actor,aid:string,input:unknown){const b=parse(z.object({reason:text(1000),expected_version:version}).strict(),input);const asset=await this.scope(tx,a,aid,true);this.checkVersion(asset,b.expected_version);const r=await tx.query("UPDATE assets SET business_status='retired',retired_reason=$2,retired_at=now(),version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[aid,b.reason]);await audit(tx,a,'asset.retire','asset',aid,{reason:b.reason});return {status:200,data:r.rows[0]};}
 async favorite(tx:Tx,a:Actor,aid:string,remove=false){await this.scope(tx,a,aid);if(remove)await tx.query('DELETE FROM asset_favorites WHERE asset_id=$1 AND membership_id=$2',[aid,a.memberId]);else await tx.query('INSERT INTO asset_favorites(workspace_id,asset_id,membership_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[a.workspaceId,aid,a.memberId]);return {status:200,data:{success:true}};}
 async relate(tx:Tx,a:Actor,input:unknown){const b=parse(z.object({from_version_id:uuid,to_version_id:uuid,relation_type:z.enum(['source_of','render_of','derived_from'])}).strict(),input);if(b.from_version_id===b.to_version_id)throw new AppError(422,'RELATION_INVALID','不能关联同一版本');for(const id of [b.from_version_id,b.to_version_id]){const r=await tx.query('SELECT id FROM asset_versions WHERE id=$1 AND workspace_id=$2',[id,a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','版本不存在或不可见');}const r=await tx.query('INSERT INTO asset_relations(workspace_id,created_by,from_version_id,to_version_id,relation_type) VALUES($1,$2,$3,$4,$5) ON CONFLICT(from_version_id,to_version_id,relation_type) DO UPDATE SET relation_type=EXCLUDED.relation_type RETURNING *',[a.workspaceId,a.memberId,b.from_version_id,b.to_version_id,b.relation_type]);await audit(tx,a,'asset.relate','asset_relation',r.rows[0].id);return {status:201,data:r.rows[0]};}
 async use(tx:Tx,a:Actor,input:unknown){
  const b=parse(z.object({asset_version_id:uuid,revision_id:uuid,role:text(),clip_range:z.object({start_ms:z.number().int().min(0),end_ms:z.number().int().positive()}).strict().optional(),expected_version:version}).strict(),input);
  const v=(await tx.query('SELECT * FROM asset_versions WHERE id=$1 AND workspace_id=$2',[b.asset_version_id,a.workspaceId])).rows[0];if(!v)throw new AppError(404,'NOT_FOUND','资产版本不可见');const asset=await this.scope(tx,a,v.asset_id,true);
  if(asset.business_status==='retired')throw new AppError(422,'ASSET_RETIRED','停用素材不可新增引用');if(v.valid_until&&new Date(v.valid_until).getTime()<=Date.now())throw new AppError(422,'PERMISSION_EXPIRED','素材使用依据已过期');
  const r=await tx.query('SELECT r.*,c.account_id,c.business_status FROM content_revisions r JOIN contents c ON c.id=r.content_id WHERE r.id=$1 AND r.workspace_id=$2 FOR UPDATE OF r',[b.revision_id,a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','内容版本不可见');const revision=r.rows[0];await new Commands(this.db).accountScope(tx,a,revision.account_id);this.checkVersion(revision,b.expected_version);if(revision.frozen||!['draft','in_production'].includes(revision.business_status))throw new AppError(409,'REVISION_FROZEN','冻结内容不能新增引用');
  if(b.clip_range)throw new AppError(422,'CLIP_UNSUPPORTED','首版PNG素材不支持视频片段');

  const snapshot={usage_scope:v.usage_scope,confirmed_by:v.permission_confirmed_by,valid_until:v.valid_until,business_status:asset.business_status};const u=await tx.query('INSERT INTO asset_usages(workspace_id,created_by,asset_version_id,revision_id,usage_role,clip_start_ms,clip_end_ms,permission_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING RETURNING *',[a.workspaceId,a.memberId,v.id,revision.id,b.role,null,null,JSON.stringify(snapshot)]);if(u.rowCount)await tx.query('UPDATE content_revisions SET version=version+1,updated_at=now() WHERE id=$1',[revision.id]);await audit(tx,a,'asset.use','asset',asset.id,{revision_id:revision.id,version_id:v.id});return {status:201,data:u.rows[0]??(await tx.query('SELECT * FROM asset_usages WHERE asset_version_id=$1 AND revision_id=$2 AND usage_role=$3',[v.id,revision.id,b.role])).rows[0]};
 }
 async usages(a:Actor,aid:string){await this.scope(this.db,a,aid);const r=await this.db.query('SELECT u.*,v.version_no,r.content_id,c.title,c.account_id,a.business_status FROM asset_usages u JOIN asset_versions v ON v.id=u.asset_version_id JOIN assets a ON a.id=v.asset_id JOIN content_revisions r ON r.id=u.revision_id JOIN contents c ON c.id=r.content_id WHERE v.asset_id=$1 AND u.workspace_id=$2 AND ($3 OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.account_id=c.account_id AND am.membership_id=$4)) ORDER BY u.created_at DESC',[aid,a.workspaceId,a.roles.includes('admin'),a.memberId]);return {items:r.rows,next_cursor:null};}
 async revisionAssets(a:Actor,rid:string){const r=await this.db.query('SELECT c.account_id FROM content_revisions r JOIN contents c ON c.id=r.content_id WHERE r.id=$1 AND r.workspace_id=$2',[parse(uuid,rid),a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','内容版本不可见');await new Commands(this.db).accountScope(this.db,a,r.rows[0].account_id);return {next_cursor:null,items:(await this.db.query('SELECT u.*,a.name,a.business_status,v.version_no FROM asset_usages u JOIN asset_versions v ON v.id=u.asset_version_id JOIN assets a ON a.id=v.asset_id WHERE u.revision_id=$1 AND u.workspace_id=$2',[rid,a.workspaceId])).rows};}
 async folders(a:Actor){return {next_cursor:null,items:(await this.db.query('SELECT * FROM folders WHERE workspace_id=$1 ORDER BY name,id',[a.workspaceId])).rows};}
 async folder(tx:Tx,a:Actor,fid:string){const r=await tx.query('SELECT * FROM folders WHERE id=$1 AND workspace_id=$2 FOR UPDATE',[parse(uuid,fid),a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','文件夹不可见');return r.rows[0];}
 async saveFolder(tx:Tx,a:Actor,input:unknown,fid?:string){
  const b=parse<any>(fid?z.object({name:text().optional(),parent_id:uuid.nullable().optional(),expected_version:version}).strict():z.object({name:text(),parent_id:uuid.nullable().optional()}).strict(),input);
  await tx.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[a.workspaceId]);if(b.parent_id)await this.folder(tx,a,b.parent_id);
  if(fid){const f=await this.folder(tx,a,fid);this.checkVersion(f,(b as any).expected_version);if(b.parent_id){const loop=await tx.query('WITH RECURSIVE ancestors AS (SELECT id,parent_id FROM folders WHERE id=$1 AND workspace_id=$2 UNION ALL SELECT f.id,f.parent_id FROM folders f JOIN ancestors a ON f.id=a.parent_id) SELECT id FROM ancestors WHERE id=$3',[b.parent_id,a.workspaceId,fid]);if(loop.rowCount)throw new AppError(422,'FOLDER_CYCLE','文件夹关系不能形成循环');}const r=await tx.query('UPDATE folders SET name=COALESCE($1,name),parent_id=CASE WHEN $2 THEN $3 ELSE parent_id END,version=version+1,updated_at=now() WHERE id=$4 RETURNING *',[b.name??null,'parent_id' in b,b.parent_id??null,fid]);await audit(tx,a,'folder.update','folder',fid);return {status:200,data:r.rows[0]};}
  const r=await tx.query('INSERT INTO folders(workspace_id,created_by,name,parent_id) VALUES($1,$2,$3,$4) RETURNING *',[a.workspaceId,a.memberId,b.name,b.parent_id??null]);await audit(tx,a,'folder.create','folder',r.rows[0].id);return {status:201,data:r.rows[0]};
 }
 async ruleSets(a:Actor){return {next_cursor:null,items:(await this.db.query('SELECT * FROM rule_sets WHERE workspace_id=$1 ORDER BY created_at DESC',[a.workspaceId])).rows};}
 async ruleDetail(a:Actor,rid:string){const r=await this.db.query('SELECT * FROM rule_sets WHERE id=$1 AND workspace_id=$2',[parse(uuid,rid),a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','规范不可见');return {...r.rows[0],rules:(await this.db.query('SELECT * FROM brand_rules WHERE rule_set_id=$1 AND workspace_id=$2 ORDER BY source_page,id',[rid,a.workspaceId])).rows};}
 async createRules(tx:Tx,a:Actor,input:unknown){
  const b=parse(z.object({edition:text(),source_file_id:uuid,rules:z.array(z.object({category:z.enum(['color','identity','layout','typography','usage','other']),rule_text:text(10000),source_page:z.number().int().positive(),severity:text(),uncertainty_note:z.string().max(10000).nullable().optional()}).strict()).min(1).max(1000)}).strict(),input);const f=await this.ready(tx,a,b.source_file_id);if(f.detected_mime!=='application/pdf'||!f.metadata.pages)throw new AppError(422,'RULE_SOURCE_INVALID','规范须关联已解析页数的PDF原件');if(b.rules.some(r=>r.source_page>f.metadata.pages))throw new AppError(422,'SOURCE_PAGE_INVALID','规则页码超出PDF范围');
  const r=await tx.query('INSERT INTO rule_sets(workspace_id,created_by,edition,source_file_id) VALUES($1,$2,$3,$4) RETURNING *',[a.workspaceId,a.memberId,b.edition,b.source_file_id]);for(const rule of b.rules)await tx.query('INSERT INTO brand_rules(workspace_id,rule_set_id,category,rule_text,source_page,severity,uncertainty_note) VALUES($1,$2,$3,$4,$5,$6,$7)',[a.workspaceId,r.rows[0].id,rule.category,rule.rule_text,rule.source_page,rule.severity,rule.uncertainty_note??null]);await audit(tx,a,'rules.create','rule_set',r.rows[0].id);return {status:201,data:r.rows[0]};
 }
 async activateRules(tx:Tx,a:Actor,rid:string,input:unknown){
  const b=parse(z.object({checklist:z.array(text()).min(1),expected_version:version}).strict(),input);await tx.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[a.workspaceId]);const r=await tx.query('SELECT * FROM rule_sets WHERE id=$1 AND workspace_id=$2 FOR UPDATE',[parse(uuid,rid),a.workspaceId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','规范不可见');const rule=r.rows[0];this.checkVersion(rule,b.expected_version);if(rule.status!=='draft')throw new AppError(409,'RULE_NOT_DRAFT','仅草稿规范可激活');await this.ready(tx,a,rule.source_file_id);
  await tx.query("UPDATE rule_sets SET status='retired',version=version+1,updated_at=now() WHERE workspace_id=$1 AND status='active'",[a.workspaceId]);const active=await tx.query("UPDATE rule_sets SET status='active',activated_by=$1,activated_at=now(),checklist=$2,version=version+1,updated_at=now() WHERE id=$3 RETURNING *",[a.memberId,b.checklist,rid]);await audit(tx,a,'rules.activate','rule_set',rid,{checklist:b.checklist});return {status:200,data:active.rows[0]};
 }
}
