import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,version,text,id,sha,canonical,pagination,page} from '../../../packages/domain/src/protocol';
import {lockPaths,saveRevisionAssetUsages} from '../../../packages/domain/src/briefs';
import {Commands,audit} from './commands';
export class Contents {
 constructor(readonly db:Database){}
 async scope(query:Pick<Database,'query'>|Tx,a:Actor,contentId:string,lock=false){parse(uuid,contentId);const r=await query.query(`SELECT * FROM contents WHERE workspace_id=$1 AND id=$2 ${lock?'FOR UPDATE':''}`,[a.workspaceId,contentId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','内容不存在或不可见');await new Commands(this.db).accountScope(query,a,r.rows[0].account_id);return r.rows[0];}
 private editable(content:any){if(!['draft','in_production'].includes(content.business_status))throw new AppError(409,'CONTENT_NOT_EDITABLE','当前状态不能生成或应用制作单');}
 async list(a:Actor,q:Record<string,unknown>){const {limit,cursor}=pagination(q),account=q.account_id?parse(uuid,q.account_id):null;if(account)await new Commands(this.db).accountScope(this.db,a,account);const r=await this.db.query(`SELECT c.* FROM contents c WHERE c.workspace_id=$1 AND ($2::boolean OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.account_id=c.account_id AND am.membership_id=$3)) AND ($4::uuid IS NULL OR c.account_id=$4) AND ($5::timestamptz IS NULL OR (c.created_at,c.id)<($5,$6::uuid)) ORDER BY c.created_at DESC,c.id DESC LIMIT $7`,[a.workspaceId,a.roles.includes('admin'),a.memberId,account,cursor?.at??null,cursor?.id??null,limit+1]);return page(r.rows,limit);}
 async detail(a:Actor,contentId:string){const content=await this.scope(this.db,a,contentId),revisions=(await this.db.query('SELECT * FROM content_revisions WHERE content_id=$1 ORDER BY revision_no DESC',[content.id])).rows;return {...content,current_revision:revisions.find(r=>r.id===content.current_revision_id)??null,revisions,generation_requests:(await this.db.query("SELECT id,state,job_id,result_revision_id,error_code,created_at FROM ai_requests WHERE workspace_id=$1 AND snapshot->>'content_id'=$2 ORDER BY created_at DESC LIMIT 50",[a.workspaceId,content.id])).rows};}
 async generate(tx:Tx,a:Actor,contentId:string,input:unknown){
  const b=parse(z.object({base_revision_id:uuid,instruction:z.string().max(10000).optional(),preserve_fields:z.array(text(200)).max(100),target_duration_ms:z.number().int().min(1000).max(600000).optional(),aspect_ratio:z.enum(['9:16','16:9','1:1','3:4']).optional()}).strict(),input),c=await this.scope(tx,a,contentId,true);this.editable(c);if(c.current_revision_id!==b.base_revision_id)throw new AppError(409,'BASE_REVISION_STALE','请从当前草稿重新生成');
  const base=(await tx.query('SELECT * FROM content_revisions WHERE id=$1 AND content_id=$2 FOR SHARE',[b.base_revision_id,c.id])).rows[0];if(!base||base.frozen)throw new AppError(409,'BASE_REVISION_FROZEN','当前版本不可作为可编辑草稿');
  const paths=lockPaths([...b.preserve_fields,...(base.payload.locked_fields??[])],base.payload);
  const topic=(await tx.query('SELECT * FROM topics WHERE id=$1',[c.topic_id])).rows[0];if(!topic)throw new AppError(422,'TOPIC_REQUIRED','生成制作单需要已采纳选题');
  const generation=(await tx.query('SELECT * FROM ai_requests WHERE id=$1',[topic.generation_request_id])).rows[0];
  const rule=(await tx.query("SELECT id,version FROM rule_sets WHERE workspace_id=$1 AND status='active'",[a.workspaceId])).rows[0];const rules=rule?(await tx.query('SELECT id,category,rule_text,source_page,severity FROM brand_rules WHERE rule_set_id=$1',[rule.id])).rows:[];
  const assets=(await tx.query("SELECT av.id asset_version_id,ast.id asset_id,ast.name,ast.category,ast.tags,ast.version asset_version,ast.business_status,av.usage_scope FROM asset_versions av JOIN assets ast ON ast.id=av.asset_id WHERE ast.workspace_id=$1 AND ast.business_status='usable' AND av.permission_confirmed_at IS NOT NULL AND (av.valid_until IS NULL OR av.valid_until>now()) ORDER BY av.created_at DESC LIMIT 100",[a.workspaceId])).rows;
  const account=await new Commands(this.db).accountScope(tx,a,c.account_id),workspace=(await tx.query('SELECT version FROM workspaces WHERE id=$1',[a.workspaceId])).rows[0];
  const snapshot={...generation.snapshot,account:{id:account.id,name:account.name,version:account.version},workspace_version:workspace.version,rule_set:rule??null,rules,assets,topic:topic.candidate,content_id:c.id,content_version:c.version,base_revision_id:base.id,base_revision_version:base.version,base_payload:base.payload,preserve_fields:paths,instruction:b.instruction??'',...(c.media_type==='video'?{target_duration_ms:b.target_duration_ms??base.payload.brief?.target_duration_ms??15000,aspect_ratio:b.aspect_ratio??base.payload.brief?.aspect_ratio??'9:16'}:{})};
  const request=id();await tx.query('INSERT INTO ai_requests(id,workspace_id,account_id,created_by,kind,input_version,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7)',[request,a.workspaceId,c.account_id,a.memberId,c.media_type,sha(canonical(snapshot)),JSON.stringify(snapshot)]);
  await tx.query("INSERT INTO outbox(workspace_id,account_id,event_key,event_type,payload) VALUES($1,$2,$3,'ai.generate',$4)",[a.workspaceId,c.account_id,'ai.request:'+request,JSON.stringify({created_by:a.memberId,pool:'general',request_id:a.requestId,input:{ai_request_id:request}})]);await audit(tx,a,'content.generate_brief','content',c.id,{ai_request_id:request,base_revision_id:base.id,preserve_fields:paths});return {status:202,data:{request_id:request,state:'queued',status_url:'/api/v1/ai-requests/'+request}};
 }
 async apply(tx:Tx,a:Actor,contentId:string,input:unknown){
  const b=parse(z.object({result_revision_id:uuid,expected_version:version}).strict(),input),c=await this.scope(tx,a,contentId,true);this.editable(c);
  const result=(await tx.query("SELECT * FROM content_revisions WHERE workspace_id=$1 AND content_id=$2 AND id=$3 AND origin='ai_candidate' FOR SHARE",[a.workspaceId,c.id,b.result_revision_id])).rows[0];if(!result)throw new AppError(404,'NOT_FOUND','制作单候选不存在或不属于此内容');
  const applied=(await tx.query("SELECT * FROM content_revisions WHERE source_revision_id=$1 AND origin='applied_ai'",[result.id])).rows[0];if(applied){if(c.current_revision_id!==applied.id)throw new AppError(409,'BASE_REVISION_STALE','该建议已在历史版本应用，不能覆盖后续修改');return {status:200,data:{content_id:c.id,revision_id:applied.id,version:c.version,reused:true}};}
  if(c.version!==b.expected_version||c.current_revision_id!==result.base_revision_id)throw new AppError(409,'BASE_REVISION_STALE','内容已经修改，请重新生成或人工合并');
  const request=(await tx.query('SELECT * FROM ai_requests WHERE id=$1',[result.ai_request_id])).rows[0],base=(await tx.query('SELECT * FROM content_revisions WHERE id=$1 FOR SHARE',[result.base_revision_id])).rows[0];
  if(c.version!==request.snapshot.content_version||!base||base.frozen||canonical(base.payload)!==canonical(request.snapshot.base_payload)||base.version!==(request.snapshot.base_revision_version??1))throw new AppError(409,'BASE_REVISION_STALE','基础版本已变更');
  if(result.payload_hash!==sha(canonical(result.payload)))throw new AppError(409,'CANDIDATE_HASH_INVALID','候选完整性校验失败');
  const paths=lockPaths(result.payload.locked_fields??[],base.payload);for(const path of paths){let original:any=base.payload,current:any=result.payload;for(const key of path.slice(1).split('/')){original=original?.[key];current=current?.[key];}if(canonical(original)!==canonical(current))throw new AppError(409,'LOCKED_FIELD_CHANGED','候选修改了人工锁定字段');}
  const revision=id(),next=(await tx.query('SELECT max(revision_no)+1 n FROM content_revisions WHERE content_id=$1',[c.id])).rows[0].n;
  await tx.query("INSERT INTO content_revisions(id,workspace_id,content_id,created_by,revision_no,payload,origin,base_revision_id,source_revision_id,payload_hash) VALUES($1,$2,$3,$4,$5,$6,'applied_ai',$7,$8,$9)",[revision,a.workspaceId,c.id,a.memberId,next,JSON.stringify(result.payload),base.id,result.id,result.payload_hash]);await saveRevisionAssetUsages(tx,a.workspaceId,a.memberId,revision,result.payload);
  const updated=(await tx.query('UPDATE contents SET current_revision_id=$2,title=$3,version=version+1,updated_at=now() WHERE id=$1 RETURNING version',[c.id,revision,result.payload.title])).rows[0];await audit(tx,a,'content.apply_generated','content',c.id,{candidate_revision_id:result.id,revision_id:revision,base_revision_id:base.id});return {status:200,data:{content_id:c.id,revision_id:revision,version:updated.version,reused:false}};
 }
}
