import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,uuid,text,version,parse,pagination,page,id} from '../../../packages/domain/src/protocol';
import {loadAIConfig} from '../../../packages/domain/src/ai-gateway';
import {feedbackCategories,feedbackIssues} from '../../../packages/domain/src/feedback';
import {Commands,audit} from './commands';
import {isIP} from 'node:net';
const sourceUrl=z.url().max(2000).refine(value=>{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!isIP(u.hostname)&&/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/i.test(u.hostname)&&!/(?:^|\.)(?:localhost|local|internal|test)$/i.test(u.hostname);},'请提供公开HTTPS来源链接；系统不会读取该链接');
const usage=z.object({public_reply:z.boolean(),topic_reference:z.boolean()}).strict();
const fields={publication_id:uuid.nullable(),source_url:z.string().max(2000).nullable(),source_time:z.iso.datetime({offset:true}).nullable(),text:text(10000),author_alias:z.string().max(200).nullable(),category:z.enum(feedbackCategories),consent_status:z.enum(['unknown','internal_only','approved','revoked']),permitted_usage:usage,reply_draft:z.string().max(10000),status:z.enum(['new','triaged','archived'])};
export class Feedback {
 constructor(readonly db:Database){}
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,fid:string,lock=false){const f=(await q.query('SELECT * FROM feedback WHERE workspace_id=$1 AND id=$2',[a.workspaceId,parse(uuid,fid)])).rows[0];if(!f)throw new AppError(404,'NOT_FOUND','反馈不存在或不可见');await new Commands(this.db).accountScope(q,a,f.account_id,lock);return lock?(await q.query('SELECT * FROM feedback WHERE id=$1 FOR UPDATE',[fid])).rows[0]:f;}
 async validate(tx:Tx,a:Actor,b:any){await new Commands(this.db).accountScope(tx,a,b.account_id,true);if(b.source_url)b.source_url=parse(sourceUrl,b.source_url);if(b.source_time&&Date.parse(b.source_time)>Date.now())throw new AppError(422,'VALIDATION_ERROR','反馈时间不可在未来');if(b.publication_id&&!(await tx.query('SELECT 1 FROM publications WHERE workspace_id=$1 AND account_id=$2 AND id=$3',[a.workspaceId,b.account_id,b.publication_id])).rowCount)throw new AppError(422,'DATA_SCOPE_MISMATCH','关联笔记必须属于当前账号');if(b.consent_status!=='approved'&&(b.permitted_usage.public_reply||b.permitted_usage.topic_reference))throw new AppError(422,'CONSENT_REQUIRED','必须获得明确许可后才能允许公开回复或选题引用');if(feedbackIssues({category:b.category,reply_draft:b.reply_draft,quotes:[],topic_leads:[]},b).length)throw new AppError(422,'CONSENT_REQUIRED','当前许可不允许保存公开回复草案');}
 async create(tx:Tx,a:Actor,input:unknown){const b=parse(z.object({account_id:uuid,...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,['text'].includes(k)?v:v.optional()]))}).strict(),input) as any;const row={publication_id:null,source_url:null,source_time:null,author_alias:null,category:'other',consent_status:'unknown',permitted_usage:{public_reply:false,topic_reference:false},reply_draft:'',status:'new',...b};await this.validate(tx,a,row);const r=(await tx.query('INSERT INTO feedback(workspace_id,account_id,publication_id,source_url,source_time,text,author_alias,category,consent_status,permitted_usage,reply_draft,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[a.workspaceId,row.account_id,row.publication_id,row.source_url,row.source_time,row.text,row.author_alias,row.category,row.consent_status,JSON.stringify(row.permitted_usage),row.reply_draft,row.status,a.memberId])).rows[0];await audit(tx,a,'feedback.create','feedback',r.id,{consent_status:r.consent_status,permitted_usage:r.permitted_usage});return {status:201,data:r};}
 async patch(tx:Tx,a:Actor,fid:string,input:unknown){const b=parse(z.object({...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.optional()])),expected_version:version,reason:text(1000)}).strict(),input) as any;const old=await this.scope(tx,a,fid,true);if(old.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','反馈或许可已更新',{version:old.version});const row={...old,...b};if(row.consent_status!=='approved'){row.permitted_usage={public_reply:false,topic_reference:false};row.reply_draft='';}if(!row.permitted_usage.public_reply)row.reply_draft='';await this.validate(tx,a,row);const r=(await tx.query('UPDATE feedback SET publication_id=$2,source_url=$3,source_time=$4,text=$5,author_alias=$6,category=$7,consent_status=$8,permitted_usage=$9,reply_draft=$10,status=$11,quotes=\'[]\',topic_leads=\'[]\',version=version+1,updated_at=now() WHERE id=$1 RETURNING *',[fid,row.publication_id,row.source_url,row.source_time,row.text,row.author_alias,row.category,row.consent_status,JSON.stringify(row.permitted_usage),row.reply_draft,row.status])).rows[0];await audit(tx,a,'feedback.update','feedback',fid,{reason:b.reason,consent_status:r.consent_status,permitted_usage:r.permitted_usage,status:r.status});return {status:200,data:r};}
 async list(a:Actor,q:Record<string,unknown>){const b=parse(z.object({account_id:uuid,publication_id:uuid.optional(),status:z.enum(['new','triaged','archived']).optional(),limit:z.unknown().optional(),cursor:z.unknown().optional()}).strict(),q);await new Commands(this.db).accountScope(this.db,a,b.account_id);const {limit,cursor}=pagination(q);return page((await this.db.query('SELECT * FROM feedback WHERE workspace_id=$1 AND account_id=$2 AND ($3::uuid IS NULL OR publication_id=$3) AND ($4::text IS NULL OR status=$4) AND ($5::timestamptz IS NULL OR (created_at,id)<($5,$6::uuid)) ORDER BY created_at DESC,id DESC LIMIT $7',[a.workspaceId,b.account_id,b.publication_id??null,b.status??null,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);}
 async organize(tx:Tx,a:Actor,fid:string,input:unknown){const b=parse(z.object({expected_version:version}).strict(),input);const f=await this.scope(tx,a,fid,true);if(f.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','反馈已改变',{version:f.version});if(f.consent_status==='revoked'||f.status==='archived')throw new AppError(409,'FEEDBACK_INACTIVE','撤回许可或归档的反馈不能用于新的AI整理');try{if(!loadAIConfig().enabled)throw new Error();}catch{throw new AppError(503,'AI_DISABLED','AI不可用，仍可人工维护反馈');}if(f.job_id){const job=(await tx.query('SELECT id,state FROM jobs WHERE id=$1',[f.job_id])).rows[0];if(['queued','running'].includes(job?.state))return {status:202,data:{feedback_id:f.id,job_id:job.id,state:job.state,status_url:'/api/v1/jobs/'+job.id}};}
 const account=(await tx.query('SELECT version FROM accounts WHERE id=$1',[f.account_id])).rows[0],workspace=(await tx.query('SELECT version FROM workspaces WHERE id=$1',[a.workspaceId])).rows[0],snapshot={workspace_version:workspace.version,scope_version:'v1.2-s8',id:f.id,version:f.version,account_version:account.version,text:f.text,category:f.category,consent_status:f.consent_status,permitted_usage:f.permitted_usage};const requestId=id(),out=(await tx.query("INSERT INTO outbox(workspace_id,account_id,event_key,event_type,payload) VALUES($1,$2,$3,'feedback.organize',$4) RETURNING id",[a.workspaceId,f.account_id,'feedback:'+id(),JSON.stringify({created_by:a.memberId,pool:'general',request_id:requestId,input:{snapshot}})])).rows[0];const job=(await tx.query("INSERT INTO jobs(workspace_id,account_id,created_by,outbox_id,type,pool,input,request_id) VALUES($1,$2,$3,$4,'feedback.organize','general',$5,$6) RETURNING id,state",[a.workspaceId,f.account_id,a.memberId,out.id,JSON.stringify({snapshot}),requestId])).rows[0];await tx.query('UPDATE feedback SET job_id=$2 WHERE id=$1',[f.id,job.id]);await audit(tx,a,'feedback.organize','feedback',f.id,{version:f.version});return {status:202,data:{feedback_id:f.id,job_id:job.id,state:job.state,status_url:'/api/v1/jobs/'+job.id}};
 }
}
