import {readFileSync} from 'node:fs';
import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,version,text,pagination,page} from '../../../packages/domain/src/protocol';
import {addRows,batchScope,rowMetric,templateFields,metricDefinitions,logicalKey,sameValue} from '../../../packages/domain/src/imports';
import {Commands,audit} from './commands';
export class Imports {
 constructor(readonly db:Database){}
 template(format:unknown){const f=parse(z.enum(['csv','xlsx']),format??'csv');return {field_version:'table-v1',fields:templateFields,metric_definitions:metricDefinitions,format:f,filename:'yoyo-import-v1.'+f,content_base64:readFileSync('docs/templates/yoyo-import-v1.'+f).toString('base64'),example_policy:'is_example=true 的行永久不可入账；实际数据另建行'};}
 async list(a:Actor,q:Record<string,unknown>){const {limit,cursor}=pagination(q);const account=parse(uuid,q.account_id);await new Commands(this.db).accountScope(this.db,a,account);return page((await this.db.query('SELECT * FROM import_batches WHERE workspace_id=$1 AND account_id=$2 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid)) ORDER BY created_at DESC,id DESC LIMIT $5',[a.workspaceId,account,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);}
 async get(a:Actor,id:string){const b=await batchScope(this.db,a,id);const j=(await this.db.query("SELECT id,state,error_code FROM jobs WHERE workspace_id=$1 AND input->>'batch_id'=$2 ORDER BY created_at DESC LIMIT 1",[a.workspaceId,b.id])).rows[0];return {...b,job:j??null};}
 async rows(a:Actor,id:string,q:Record<string,unknown>){await batchScope(this.db,a,id);const {limit,cursor}=pagination(q);const result=page((await this.db.query('SELECT * FROM import_rows WHERE batch_id=$1 AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3::uuid)) ORDER BY created_at DESC,id DESC LIMIT $4',[id,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);for(const r of result.items){if(r.metric&&['valid','conflict'].includes(r.status)){const current=(await this.db.query("SELECT id,metric FROM metric_observations WHERE logical_key=$1 AND validity='confirmed'",[logicalKey(a.workspaceId,r.metric)])).rows[0];if(current&&!sameValue(current.metric,r.metric)){r.status='conflict';r.existing_observation_id=current.id;r.existing_metric=current.metric;}}}return result;}
 async create(tx:Tx,a:Actor,input:unknown){const b=parse(z.object({account_id:uuid,file_ids:z.array(uuid).max(20),source_type:z.enum(['manual','csv','xlsx']),manual_rows:z.array(z.record(z.string(),z.unknown())).max(5000).optional(),field_mapping:z.record(z.string(),z.enum(Object.keys(templateFields) as [string,...string[]])).default({})}).strict(),input);await new Commands(this.db).accountScope(tx,a,b.account_id,true);
 if(new Set(Object.values(b.field_mapping)).size!==Object.values(b.field_mapping).length||new Set(b.file_ids).size!==b.file_ids.length)throw new AppError(422,'IMPORT_MAPPING_INVALID','映射目标和文件不能重复');
 if(b.source_type==='manual'){if(b.file_ids.length||!b.manual_rows?.length)throw new AppError(422,'IMPORT_INPUT_INVALID','手工批次需填写数据且无文件');}else{if(!b.file_ids.length||b.manual_rows)throw new AppError(422,'IMPORT_INPUT_INVALID','表格批次必须选择文件');let size=0;for(const id of b.file_ids){const f=(await tx.query("SELECT * FROM file_objects WHERE id=$1 AND workspace_id=$2 AND account_id=$3 AND purpose='import_table' AND NOT is_preview AND file_status='ready' AND metadata->>'table_parser_version'='table-v1' FOR SHARE",[id,a.workspaceId,b.account_id])).rows[0];if(!f)throw new AppError(422,'IMPORT_FILE_NOT_READY','文件未通过当前安全解析或不属于账号');if(f.metadata.table_truncated)throw new AppError(422,'IMPORT_ROW_LIMIT','每批最多5000数据行，请拆分表格');if(f.metadata.format!==b.source_type.toUpperCase())throw new AppError(422,'IMPORT_FORMAT_MISMATCH','文件与选择类型不一致');size+=Number(f.size_bytes);}if(size>104857600)throw new AppError(422,'IMPORT_SIZE_LIMIT','批次最多100MiB');}
 const batch=(await tx.query('INSERT INTO import_batches(workspace_id,account_id,created_by,source_type,input_file_ids,status,mapping) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[a.workspaceId,b.account_id,a.memberId,b.source_type,b.file_ids,b.source_type==='manual'?'needs_confirmation':'uploaded',JSON.stringify(b.field_mapping)])).rows[0];
 if(b.source_type==='manual')await addRows(tx,batch,b.manual_rows!.map(raw=>({raw})));else await tx.query("INSERT INTO outbox(workspace_id,account_id,event_key,event_type,payload) VALUES($1,$2,$3,'import.parse',$4)",[a.workspaceId,b.account_id,'import.parse:'+batch.id,JSON.stringify({created_by:a.memberId,request_id:a.requestId,input:{batch_id:batch.id},input_version:(await tx.query('SELECT version FROM workspaces WHERE id=$1 FOR SHARE',[a.workspaceId])).rows[0].version})]);await audit(tx,a,'import.create','import_batch',batch.id,{source_type:b.source_type});return {status:202,data:batch};
 }
 async patch(tx:Tx,a:Actor,id:string,input:unknown){const patch=parse(z.object({metric:z.record(z.string(),z.unknown()).optional(),status:z.enum(['valid','excluded']).optional(),reason:text(2000),expected_version:version}).strict(),input);const row=(await tx.query('SELECT * FROM import_rows WHERE workspace_id=$1 AND id=$2',[a.workspaceId,parse(uuid,id)])).rows[0];if(!row)throw new AppError(404,'NOT_FOUND','行不存在或不可见');const b=await batchScope(tx,a,row.batch_id,true);if(['confirmed','reverted'].includes(b.status)||row.status==='confirmed')throw new AppError(409,'IMPORT_IMMUTABLE','已确认行请通过新批次更正');const r=(await tx.query('SELECT * FROM import_rows WHERE id=$1 FOR UPDATE',[id])).rows[0];if(r.version!==patch.expected_version)throw new AppError(409,'VERSION_CONFLICT','行已修改');if(r.is_example)throw new AppError(422,'IMPORT_EXAMPLE','示例行永久不可入账');const m=patch.status==='excluded'&&!patch.metric?r.metric:await rowMetric(tx,b,patch.metric??r.metric??r.raw);const next=(await tx.query("UPDATE import_rows SET metric=$2,status=$3,error=NULL,corrections=corrections||$4::jsonb,version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[id,JSON.stringify(m),patch.status??'valid',JSON.stringify([{actor_id:a.memberId,at:new Date().toISOString(),reason:patch.reason,before:r.metric,after:m}])])).rows[0];await tx.query('UPDATE import_batches SET version=version+1,updated_at=now() WHERE id=$1',[b.id]);await audit(tx,a,'import.row_correct','import_row',id,{reason:patch.reason});return {status:200,data:next};}
 async confirm(tx:Tx,a:Actor,id:string,input:unknown){const b=parse(z.object({row_ids:z.array(uuid).min(1).max(5000),conflict_resolutions:z.array(z.object({row_id:uuid,resolution:z.enum(['keep_existing','replace']),existing_observation_id:uuid}).strict()),reason:text(2000),expected_version:version}).strict(),input);
  if(new Set(b.row_ids).size!==b.row_ids.length||new Set(b.conflict_resolutions.map(r=>r.row_id)).size!==b.conflict_resolutions.length||b.conflict_resolutions.some(r=>!b.row_ids.includes(r.row_id)))throw new AppError(422,'IMPORT_SELECTION_INVALID','行和冲突处理不能重复或越出选择');
  const batch=await batchScope(tx,a,id,true);await new Commands(this.db).accountScope(tx,a,batch.account_id,true);
  if(batch.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','批次已修改，请刷新');if(!['needs_confirmation','partially_confirmed'].includes(batch.status))throw new AppError(409,'IMPORT_STATE_INVALID','批次不可确认');
  const rows=(await tx.query('SELECT * FROM import_rows WHERE batch_id=$1 AND id=ANY($2::uuid[]) ORDER BY row_number FOR UPDATE',[id,b.row_ids])).rows;if(rows.length!==b.row_ids.length)throw new AppError(422,'IMPORT_SELECTION_INVALID','所选行不属于批次');
  for(const r of rows){if(r.is_example||!['valid','conflict'].includes(r.status)||!r.metric)throw new AppError(422,'IMPORT_ROW_INVALID','只可选择合法非示例行');const m=await rowMetric(tx,batch,r.metric),key=logicalKey(a.workspaceId,m);let observation=(await tx.query("SELECT * FROM metric_observations WHERE logical_key=$1 AND validity='confirmed' FOR UPDATE",[key])).rows[0];let supports=true;
   const resolution=b.conflict_resolutions.find(x=>x.row_id===r.id);
   if(observation&&!sameValue(observation.metric,m)){if(!resolution||resolution.existing_observation_id!==observation.id)throw new AppError(409,'METRIC_DUPLICATE','同口径存在不同值，请刷新并显式解决',{row_id:r.id,existing_observation_id:observation.id});if(resolution.resolution==='keep_existing')supports=false;else{const old=observation;await tx.query('SELECT metric_invalidate_reports($1,$2,$3,$4)',[a.workspaceId,[old.id],'指标被显式更正',a.requestId]);await tx.query("UPDATE metric_observations SET validity='superseded' WHERE id=$1",[old.id]);observation=await this.newObservation(tx,a,batch,m,key);await tx.query('INSERT INTO observation_supersessions(workspace_id,old_id,new_id,batch_id,reason) VALUES($1,$2,$3,$4,$5)',[a.workspaceId,old.id,observation.id,id,b.reason]);}}
   else if(resolution)throw new AppError(409,'METRIC_CONFLICT_CHANGED','冲突已变化，请刷新重新确认');
   if(!observation)observation=await this.newObservation(tx,a,batch,m,key);
   await tx.query('INSERT INTO metric_evidence(workspace_id,batch_id,row_id,observation_id,supports_value,confirmed_by) VALUES($1,$2,$3,$4,$5,$6)',[a.workspaceId,id,r.id,observation.id,supports,a.memberId]);await tx.query("UPDATE import_rows SET status='confirmed',confirmed_by=$2,confirmed_at=now(),version=version+1,updated_at=now() WHERE id=$1",[r.id,a.memberId]);
  }
  const pending=(await tx.query("SELECT count(*)::int n FROM import_rows WHERE batch_id=$1 AND NOT is_example AND status<>'confirmed'",[id])).rows[0].n;const next=(await tx.query("UPDATE import_batches SET status=$2,confirmed_by=$3,confirmed_at=now(),version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[id,pending?'partially_confirmed':'confirmed',a.memberId])).rows[0];await audit(tx,a,'import.confirm','import_batch',id,{row_ids:b.row_ids,reason:b.reason});return {status:200,data:next};
 }
 async newObservation(tx:Tx,a:Actor,b:any,m:any,key:string){return (await tx.query("INSERT INTO metric_observations(workspace_id,account_id,publication_id,logical_key,revision,metric,value,validity,created_by) SELECT $1,$2,$3,$4,COALESCE(max(revision),0)+1,$5,$6,'confirmed',$7 FROM metric_observations WHERE logical_key=$4 RETURNING *",[a.workspaceId,b.account_id,m.target.publication_id??null,key,JSON.stringify(m),m.value,a.memberId])).rows[0];}

 async revert(tx:Tx,a:Actor,id:string,input:unknown){const b=parse(z.object({reason:text(2000),expected_version:version}).strict(),input),batch=await batchScope(tx,a,id,true);await new Commands(this.db).accountScope(tx,a,batch.account_id,true);if(batch.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','批次已修改');if(!['confirmed','partially_confirmed'].includes(batch.status))throw new AppError(409,'IMPORT_STATE_INVALID','只能撤销已确认批次');
  const affected=(await tx.query('SELECT DISTINCT o.logical_key,o.id FROM metric_observations o JOIN metric_evidence e ON e.observation_id=o.id WHERE e.batch_id=$1 AND e.active',[id])).rows;
  await tx.query('UPDATE metric_evidence SET active=false WHERE batch_id=$1',[id]);await tx.query('UPDATE observation_supersessions SET active=false WHERE batch_id=$1',[id]);
  for(const key of new Set(affected.map(r=>r.logical_key))){const observations=(await tx.query('SELECT o.*,EXISTS(SELECT 1 FROM metric_evidence e WHERE e.observation_id=o.id AND e.active AND e.supports_value) backed FROM metric_observations o WHERE logical_key=$1 ORDER BY revision DESC FOR UPDATE',[key])).rows;const winner=observations.find(o=>o.backed);const changed=observations.filter(o=>o.validity!==(o.id===winner?.id?'confirmed':o.backed?'superseded':'reverted')).map(o=>o.id);
   await tx.query("UPDATE metric_observations SET validity='reverted' WHERE logical_key=$1",[key]);for(const o of observations){await tx.query('UPDATE metric_observations SET validity=$2 WHERE id=$1',[o.id,o.id===winner?.id?'confirmed':o.backed?'superseded':'reverted']);}
   if(changed.length)await tx.query('SELECT metric_invalidate_reports($1,$2,$3,$4)',[a.workspaceId,changed,'导入批次撤销导致有效数据变化',a.requestId]);
  }
  // A removed source also invalidates reports citing that provenance, even when a shared value survives.
  if(affected.length)await tx.query('SELECT metric_invalidate_reports($1,$2,$3,$4)',[a.workspaceId,affected.map(r=>r.id),'导入来源撤销',a.requestId]);
  await tx.query('INSERT INTO import_reversions(batch_id,workspace_id,actor_id,reason) VALUES($1,$2,$3,$4)',[id,a.workspaceId,a.memberId,b.reason]);const next=(await tx.query("UPDATE import_batches SET status='reverted',version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[id])).rows[0];await audit(tx,a,'import.revert','import_batch',id,{reason:b.reason,observation_ids:affected.map(r=>r.id)});return {status:200,data:next};
 }

}
