import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,pagination,page,sha,canonical} from '../../../packages/domain/src/protocol';
import {metricDefinitions,derivedDefinitions} from '../../../packages/domain/src/imports';
import {computeMetrics,analyzeMetrics} from '../../../packages/domain/src/metrics';
import {Commands} from './commands';
export class Metrics {
 constructor(readonly db:Database){}
 async filters(q:Record<string,unknown>){const b=parse(z.object({account_id:uuid,publication_id:uuid.optional(),media_type:z.enum(['graphic','video']).optional(),traffic_type:z.enum(['organic','paid','mixed','unknown']).optional(),start:z.iso.datetime({offset:true}).optional(),end:z.iso.datetime({offset:true}).optional()}).strict(),Object.fromEntries(Object.entries(q).filter(([k])=>!['limit','cursor'].includes(k))));if((b.start&&!b.end)||(!b.start&&b.end)||b.start&&b.end&&Date.parse(b.start)>=Date.parse(b.end))throw new AppError(422,'METRIC_WINDOW_INVALID','开始和结束需完整且有序');return {...b,start:b.start?new Date(b.start).toISOString():null,end:b.end?new Date(b.end).toISOString():null};}
 async observations(q:Pick<Database,'query'>|Tx,a:Actor,f:any,limit:number,cursor:any=null,includeEnd=false){return q.query(`SELECT o.*,p.title publication_title,p.media_type,p.published_at,CASE WHEN COALESCE((metric->>'window_start')::timestamptz,(metric->>'observed_at')::timestamptz)<p.published_at THEN '笔记统计窗口早于更正后发布时间，待核验' ELSE NULL END analysis_warning FROM metric_observations o LEFT JOIN publications p ON p.id=o.publication_id WHERE o.workspace_id=$1 AND o.account_id=$2 AND o.validity='confirmed' AND ($3::uuid IS NULL OR o.publication_id=$3) AND ($4::text IS NULL OR p.media_type=$4) AND ($5::text IS NULL OR metric->>'traffic_type'=$5) AND ($6::timestamptz IS NULL OR (metric->>'aggregation_kind' <> 'interval' AND (metric->>'observed_at')::timestamptz >= $6 AND ((metric->>'observed_at')::timestamptz < $7 OR ($11 AND (metric->>'observed_at')::timestamptz = $7))) OR (metric->>'aggregation_kind' = 'interval' AND (metric->>'window_start')::timestamptz >= $6 AND (metric->>'window_end')::timestamptz <= $7)) AND ($8::timestamptz IS NULL OR (o.created_at,o.id)<($8,$9::uuid)) ORDER BY o.created_at DESC,o.id DESC LIMIT $10`,[a.workspaceId,f.account_id,f.publication_id??null,f.media_type??null,f.traffic_type??null,f.start,f.end,cursor?.at??null,cursor?.id??null,limit,includeEnd]);}
 async analysis(a:Actor,q:Record<string,unknown>){const f=await this.filters(q);await new Commands(this.db).accountScope(this.db,a,f.account_id);if(f.publication_id)await this.publicationScope(this.db,a,f);const rows=(await this.observations(this.db,a,f,10001)).rows;if(rows.length>10000)throw new AppError(422,'METRIC_WINDOW_LIMIT','分析超过1万条观察，请缩小范围');return {...analyzeMetrics(rows),window:{start:f.start,end:f.end},observations_count:rows.length};}
 async publicationScope(q:Pick<Database,'query'>|Tx,a:Actor,f:any){const p=await q.query('SELECT id FROM publications WHERE workspace_id=$1 AND account_id=$2 AND id=$3',[a.workspaceId,f.account_id,f.publication_id]);if(!p.rowCount)throw new AppError(404,'NOT_FOUND','笔记不存在或不可见');}
 async list(a:Actor,q:Record<string,unknown>){const f=await this.filters(q);await new Commands(this.db).accountScope(this.db,a,f.account_id);if(f.publication_id){const p=await this.db.query('SELECT id FROM publications WHERE workspace_id=$1 AND account_id=$2 AND id=$3',[a.workspaceId,f.account_id,f.publication_id]);if(!p.rowCount)throw new AppError(404,'NOT_FOUND','笔记不存在或不可见');}const {limit,cursor}=pagination(q);return {...page((await this.observations(this.db,a,f,limit+1,cursor)).rows,limit),definitions:[...metricDefinitions,...derivedDefinitions],comparison_note:'快照和累计不跨日求和；平台定义、流量与时间粒度分别比较；只有已确认观察可见'};}
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,id:string,table:'metric_observations'|'calculations'){const r=await q.query(`SELECT * FROM ${table} WHERE workspace_id=$1 AND id=$2`,[a.workspaceId,parse(uuid,id)]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','指标不存在或不可见');await new Commands(this.db).accountScope(q,a,r.rows[0].account_id);return r.rows[0];}
 async sources(a:Actor,id:string){const observation=await this.scope(this.db,a,id,'metric_observations');const evidence=(await this.db.query('SELECT e.*,r.file_id,r.raw,r.corrections,r.row_number,b.source_type,b.status batch_status,b.parser_version FROM metric_evidence e JOIN import_rows r ON r.id=e.row_id JOIN import_batches b ON b.id=e.batch_id WHERE e.observation_id=$1 ORDER BY e.confirmed_at,e.id',[id])).rows;const supersessions=(await this.db.query('SELECT * FROM observation_supersessions WHERE old_id=$1 OR new_id=$1 ORDER BY created_at,id',[id])).rows;return {observation,evidence,supersessions};}
 async calculate(a:Actor,q:Record<string,unknown>){const f=await this.filters(q);return this.db.transaction(async tx=>this.calculateIn(tx,a,f));}
 async calculateIn(tx:Tx,a:Actor,f:any){await new Commands(this.db).accountScope(tx,a,f.account_id,true);if(f.publication_id)await this.publicationScope(tx,a,f);if(!f.start||!f.end)throw new AppError(422,'METRIC_WINDOW_REQUIRED','计算需要实际开始和结束窗口');const obs=(await this.observations(tx,a,f,10001,null,true)).rows;if(obs.length>10000)throw new AppError(422,'METRIC_WINDOW_LIMIT','窗口超过1万条观察，请缩小范围');const evidence=(await tx.query('SELECT id FROM metric_evidence WHERE observation_id=ANY($1::uuid[]) AND active AND supports_value ORDER BY id',[obs.map(o=>o.id)])).rows.map(e=>e.id);const values=computeMetrics(obs,f.start!,f.end!);const items=[];for(const v of values){const fingerprint=sha(canonical([a.workspaceId,f,v,evidence]));let r=(await tx.query("SELECT * FROM calculations WHERE fingerprint=$1 AND validity='current'",[fingerprint])).rows[0];if(!r){r=(await tx.query('INSERT INTO calculations(workspace_id,account_id,publication_id,metric_key,calculation_version,input_observation_ids,window_start,window_end,traffic_type,source_definition,time_precision,rounding_rule,value,missing_reason,is_approximate,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *',[a.workspaceId,f.account_id,v.publication_id,v.metric_key,v.calculation_version,v.input_observation_ids,v.window_start,v.window_end,v.traffic_type,v.source_definition,v.time_precision,v.rounding_rule,v.value,v.missing_reason,v.is_approximate,fingerprint])).rows[0];}items.push(r);}return {items,window:{start:f.start,end:f.end},missing_reason:items.length?null:'窗口内无已确认观察',comparison_note:'各流量/平台定义/时间粒度独立计算；净增不代表新增关注'};}
 async calculation(a:Actor,id:string){const calculation=await this.scope(this.db,a,id,'calculations');const observations=[];for(const oid of calculation.input_observation_ids)observations.push(await this.sources(a,oid));return {calculation,observations};}
}
