import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,version,text,pagination,page} from '../../../packages/domain/src/protocol';
import {Commands,audit} from './commands';
const fields='id,workspace_id,account_id,platform_note_id,url,title,media_type,published_at,recorded_by,traffic_type,lifecycle,version,created_at,updated_at';
const traffic=z.enum(['organic','paid','mixed','unknown']);
export class Publications {
 constructor(readonly db:Database){}
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,pid:string,lock=false){const p=(await q.query(`SELECT ${fields} FROM publications WHERE workspace_id=$1 AND id=$2 ${lock?'FOR UPDATE':''}`,[a.workspaceId,parse(uuid,pid)])).rows[0];if(!p)throw new AppError(404,'NOT_FOUND','笔记不存在或不可见');await new Commands(this.db).accountScope(q,a,p.account_id);return p;}
 async list(a:Actor,q:Record<string,unknown>){const {limit,cursor}=pagination(q),account=q.account_id?parse(uuid,q.account_id):null,media=q.media_type?parse(z.enum(['graphic','video']),q.media_type):null,lifecycle=q.lifecycle?parse(z.enum(['active','deleted']),q.lifecycle):null;if(account)await new Commands(this.db).accountScope(this.db,a,account);const r=await this.db.query(`SELECT ${fields} FROM publications p WHERE workspace_id=$1 AND ($2::boolean OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.account_id=p.account_id AND am.membership_id=$3)) AND ($4::uuid IS NULL OR account_id=$4) AND ($5::text IS NULL OR media_type=$5) AND ($6::text IS NULL OR lifecycle=$6) AND ($7::timestamptz IS NULL OR (created_at,id)<($7,$8::uuid)) ORDER BY created_at DESC,id DESC LIMIT $9`,[a.workspaceId,a.roles.includes('admin'),a.memberId,account,media,lifecycle,cursor?.at??null,cursor?.id??null,limit+1]);return page(r.rows,limit);}
 async register(tx:Tx,a:Actor,input:unknown){
  const b=parse(z.object({account_id:uuid,platform_note_id:text(200),url:z.url().max(2000),title:text(200),media_type:z.enum(['graphic','video']),published_at:z.iso.datetime({offset:true}),traffic_type:traffic}).strict(),input);
  const account=await new Commands(this.db).accountScope(tx,a,b.account_id,true);validateNoteUrl(account.platform,b.platform_note_id,b.url);
  if(Date.parse(b.published_at)>Date.now())throw new AppError(422,'PUBLICATION_TIME_INVALID','实际发布时间不能在未来');
  const p=(await tx.query(`INSERT INTO publications(workspace_id,account_id,platform_note_id,url,title,media_type,published_at,recorded_by,traffic_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING ${fields}`,[a.workspaceId,b.account_id,b.platform_note_id,b.url,b.title,b.media_type,b.published_at,a.memberId,b.traffic_type])).rows[0];await audit(tx,a,'publication.register','publication',p.id);return {status:201,data:p};
 }
 async patch(tx:Tx,a:Actor,pid:string,input:unknown){const b=parse(z.object({title:text(200).optional(),published_at:z.iso.datetime({offset:true}).optional(),traffic_type:traffic.optional(),lifecycle:z.enum(['active','deleted']).optional(),reason:text(10000),expected_version:version}).strict(),input),p=await this.scope(tx,a,pid,true);
  if(p.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','笔记登记已修改',{version:p.version});if(b.published_at&&Date.parse(b.published_at)>Date.now())throw new AppError(422,'PUBLICATION_TIME_INVALID','实际发布时间不能在未来');
  if(b.published_at&&new Date(p.published_at).getTime()!==Date.parse(b.published_at))await tx.query('SELECT metric_invalidate_reports($1,$2,$3,$4)',[a.workspaceId,(await tx.query('SELECT id FROM metric_observations WHERE publication_id=$1',[p.id])).rows.map(r=>r.id),'笔记发布时间更正，请重验分析窗口',a.requestId]);
  const next=(await tx.query(`UPDATE publications SET title=COALESCE($2,title),published_at=COALESCE($3,published_at),traffic_type=COALESCE($4,traffic_type),lifecycle=COALESCE($5,lifecycle),version=version+1,updated_at=now() WHERE id=$1 RETURNING ${fields}`,[p.id,b.title??null,b.published_at??null,b.traffic_type??null,b.lifecycle??null])).rows[0];await audit(tx,a,'publication.correct','publication',p.id,{reason:b.reason,before:p,after:next});return {status:200,data:next};
 }
}
export function validateNoteUrl(platform:string,noteId:string,url:string){const u=new URL(url);const matching=platform==='xiaohongshu'?['www.xiaohongshu.com','xiaohongshu.com'].includes(u.hostname)&&new RegExp('^/(explore|discovery/item)/'+noteId.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'/?$').test(u.pathname):platform==='weibo'&&['weibo.com','www.weibo.com'].includes(u.hostname)&&u.pathname.split('/').filter(Boolean).at(-1)===noteId;if(u.protocol!=='https:'||u.username||u.password||u.port||!matching)throw new AppError(422,'NOTE_ID_URL_MISMATCH','请提供与笔记ID一致的平台HTTPS原帖链接');}
