import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,version,text,id,sha,canonical,pagination,page} from '../../../packages/domain/src/protocol';
import {loadAIConfig,AIFailure} from '../../../packages/domain/src/ai-gateway';
import {reportCurrent} from '../../../packages/domain/src/reports';
import {Metrics} from './metrics';
import {Commands,audit} from './commands';
export class Reports {
 constructor(readonly db:Database){}
 async create(tx:Tx,a:Actor,input:unknown){
  const b=parse(z.object({account_id:uuid,publication_id:uuid.optional(),media_type:z.enum(['graphic','video']).optional(),traffic_type:z.enum(['organic','paid','mixed','unknown']).optional(),start:z.iso.datetime({offset:true}),end:z.iso.datetime({offset:true})}).strict(),input);
  const metrics=new Metrics(this.db),f=await metrics.filters(b);if(Date.parse(f.end!)>Date.now()||Date.parse(f.end!)-Date.parse(f.start!)>31*86400000)throw new AppError(422,'REPORT_WINDOW_INVALID','报告使用过去且不超过31天的实际窗口');
  try{if(!loadAIConfig().enabled)throw new AIFailure('AI_DISABLED');}catch(e){throw new AppError(503,e instanceof AIFailure?e.code:'AI_NOT_CONFIGURED','AI不可用；仍可查看和手工核对指标');}
  const account=await new Commands(this.db).accountScope(tx,a,b.account_id,true);
  const workspace=(await tx.query('SELECT version FROM workspaces WHERE id=$1 FOR SHARE',[a.workspaceId])).rows[0];
  const calculated=await metrics.calculateIn(tx,a,f);if(calculated.items.length>100)throw new AppError(422,'REPORT_INPUT_LIMIT','报告超过100组计算，请按形式、流量或笔记缩小范围');
  const publications=(await tx.query('SELECT id FROM publications WHERE workspace_id=$1 AND account_id=$2 AND published_at>=$3 AND published_at<$4 AND ($5::uuid IS NULL OR id=$5) AND ($6::text IS NULL OR media_type=$6) AND ($7::text IS NULL OR traffic_type=$7)',[a.workspaceId,b.account_id,f.start,f.end,b.publication_id??null,b.media_type??null,b.traffic_type??null])).rows;
  const missing=[...new Set(calculated.items.filter(c=>c.missing_reason).map(c=>c.missing_reason))];if(!calculated.items.length)missing.push('窗口内无已确认观察，不能判断表现');if(publications.some(p=>!calculated.items.some(c=>c.publication_id===p.id)))missing.push('已登记笔记存在数据缺口，请补充后台观察');
  const reportId=id(),requestId=id(),reviewAt=new Date(Date.now()+7*86400000).toISOString();
  const base={scope_version:'v1.2-s8',account:{id:account.id,name:account.name,version:account.version},workspace_version:workspace.version,filters:f,calculations:calculated.items,missing_data:missing,review_at:reviewAt,language:'zh-CN'};
  const snapshot={...base,input_version:sha(canonical(base))};
  await tx.query('INSERT INTO reports(id,workspace_id,account_id,status,created_by,window_start,window_end,snapshot) VALUES($1,$2,$3,\'draft\',$4,$5,$6,$7)',[reportId,a.workspaceId,b.account_id,a.memberId,f.start,f.end,JSON.stringify(snapshot)]);
  for(const calc of calculated.items){await tx.query('INSERT INTO report_calculations VALUES($1,$2,$3)',[a.workspaceId,reportId,calc.id]);for(const oid of calc.input_observation_ids)await tx.query('INSERT INTO report_observations VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[a.workspaceId,reportId,oid]);}
  const out=(await tx.query("INSERT INTO outbox(workspace_id,account_id,event_key,event_type,payload) VALUES($1,$2,$3,'report.generate',$4) RETURNING id",[a.workspaceId,b.account_id,'report:'+reportId,JSON.stringify({created_by:a.memberId,pool:'general',request_id:requestId,input:{report_id:reportId}})])).rows[0];
  const job=(await tx.query("INSERT INTO jobs(workspace_id,account_id,created_by,outbox_id,type,pool,input,request_id) VALUES($1,$2,$3,$4,'report.generate','general',$5,$6) RETURNING id",[a.workspaceId,b.account_id,a.memberId,out.id,JSON.stringify({report_id:reportId}),requestId])).rows[0];
  await audit(tx,a,'report.create','report',reportId,{window:f,calculation_count:calculated.items.length});return {status:202,data:{report_id:reportId,job_id:job.id,state:'queued',status_url:'/api/v1/reports/'+reportId}};
 }
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,reportId:string,lock=false){const r=(await q.query('SELECT * FROM reports WHERE workspace_id=$1 AND id=$2',[a.workspaceId,parse(uuid,reportId)])).rows[0];if(!r)throw new AppError(404,'NOT_FOUND','报告不存在或不可见');await new Commands(this.db).accountScope(q,a,r.account_id,lock);return lock?(await q.query('SELECT * FROM reports WHERE id=$1 FOR UPDATE',[r.id])).rows[0]:r;}
 async list(a:Actor,q:Record<string,unknown>){const b=parse(z.object({account_id:uuid,limit:z.unknown().optional(),cursor:z.unknown().optional()}).strict(),q);await new Commands(this.db).accountScope(this.db,a,b.account_id);const {limit,cursor}=pagination(q);return page((await this.db.query('SELECT id,account_id,status,state,error_code,window_start,window_end,version,created_at,updated_at FROM reports WHERE workspace_id=$1 AND account_id=$2 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid)) ORDER BY created_at DESC,id DESC LIMIT $5',[a.workspaceId,b.account_id,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);}
 async get(a:Actor,id:string){const r=await this.scope(this.db,a,id);return {...r,strategies:(await this.db.query('SELECT * FROM strategy_memories WHERE report_id=$1 ORDER BY action_index',[id])).rows};}
 async accept(tx:Tx,a:Actor,id:string,input:unknown){const b=parse(z.object({action_indexes:z.array(z.number().int().nonnegative()).min(1).max(10),reason:text(1000),expected_version:version}).strict(),input);const r=await this.scope(tx,a,id,true);if(r.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','报告已改变，请刷新',{version:r.version});if(r.state!=='succeeded'||!['partial','final'].includes(r.status)||!(await reportCurrent(tx,r)))throw new AppError(409,'REPORT_STALE','仅可采纳当前已完成报告的实验');if(new Set(b.action_indexes).size!==b.action_indexes.length||b.action_indexes.some(i=>!r.result.actions[i]))throw new AppError(422,'ACTION_INVALID','请选择有效且不重复的行动');
  for(const index of b.action_indexes){const action=r.result.actions[index];await tx.query('INSERT INTO strategy_memories(workspace_id,account_id,report_id,action_index,action,created_by,review_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(report_id,action_index) DO NOTHING',[a.workspaceId,r.account_id,r.id,index,JSON.stringify(action),a.memberId,action.review_at]);}
  await tx.query('UPDATE reports SET version=version+1,updated_at=now() WHERE id=$1',[id]);await audit(tx,a,'report.accept_actions','report',id,{action_indexes:b.action_indexes,reason:b.reason});return {status:200,data:await this.getIn(tx,a,id)};
 }
 async getIn(tx:Tx,a:Actor,id:string){return {...await this.scope(tx,a,id),strategies:(await tx.query('SELECT * FROM strategy_memories WHERE report_id=$1 ORDER BY action_index',[id])).rows};}
 async strategies(a:Actor,q:Record<string,unknown>){const b=parse(z.object({account_id:uuid,limit:z.unknown().optional(),cursor:z.unknown().optional()}).strict(),q);await new Commands(this.db).accountScope(this.db,a,b.account_id);const {limit,cursor}=pagination(q);return page((await this.db.query('SELECT * FROM strategy_memories WHERE workspace_id=$1 AND account_id=$2 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid)) ORDER BY created_at DESC,id DESC LIMIT $5',[a.workspaceId,b.account_id,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);}
 async strategy(tx:Tx,a:Actor,sid:string,input:unknown,activate:boolean){const b=parse(z.object({reason:text(1000),expected_version:version}).strict(),input);const s=(await tx.query('SELECT * FROM strategy_memories WHERE workspace_id=$1 AND id=$2',[a.workspaceId,parse(uuid,sid)])).rows[0];if(!s)throw new AppError(404,'NOT_FOUND','策略不存在或不可见');const r=await this.scope(tx,a,s.report_id,true);const current=(await tx.query('SELECT * FROM strategy_memories WHERE id=$1 FOR UPDATE',[sid])).rows[0];if(current.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','策略已更新',{version:current.version});if(activate){if(current.status!=='proposed'||r.state!=='succeeded'||!['partial','final'].includes(r.status)||!(await reportCurrent(tx,r))||new Date(current.review_at).getTime()<=Date.now())throw new AppError(409,'STRATEGY_NOT_CURRENT','策略或依据已过期，请重新复盘');const refs=current.action.evidence_calculation_ids;if(!refs.length||!refs.some((id:string)=>r.snapshot.calculations.some((c:any)=>c.id===id&&c.value!==null)))throw new AppError(422,'STRATEGY_EVIDENCE_REQUIRED','策略激活需至少一个当前非空计算依据');}
  const updated=(await tx.query("UPDATE strategy_memories SET status=$2,activated_by=CASE WHEN $3 THEN $4 ELSE activated_by END,activated_at=CASE WHEN $3 THEN now() ELSE activated_at END,retired_reason=CASE WHEN $3 THEN NULL ELSE $5 END,version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[sid,activate?'active':'retired',activate,a.memberId,b.reason])).rows[0];await audit(tx,a,activate?'strategy.activate':'strategy.retire','strategy_memory',sid,{reason:b.reason});return {status:200,data:updated};
 }
}
