import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,id,text,version,pagination,page} from '../../../packages/domain/src/protocol';
import {loadAIConfig} from '../../../packages/domain/src/ai-gateway';
import {sourceOrganizationCurrent} from '../../../packages/domain/src/source-organization';
import {Commands,audit} from './commands';
export class SourceOrganizations {
 constructor(readonly db:Database){}
 async scope(q:Pick<Database,'query'>|Tx,a:Actor,oid:string,lock=false){const r=(await q.query('SELECT * FROM source_organizations WHERE workspace_id=$1 AND id=$2',[a.workspaceId,parse(uuid,oid)])).rows[0];if(!r)throw new AppError(404,'NOT_FOUND','来源整理不存在或不可见');await new Commands(this.db).accountScope(q,a,r.account_id,lock);return lock?(await q.query('SELECT * FROM source_organizations WHERE id=$1 FOR UPDATE',[oid])).rows[0]:r;}
 async get(a:Actor,oid:string){const r=await this.scope(this.db,a,oid);return {...r,current:await sourceOrganizationCurrent(this.db,r)};}
 async list(a:Actor,q:Record<string,unknown>){const b=parse(z.object({account_id:uuid,limit:z.unknown().optional(),cursor:z.unknown().optional()}).strict(),q);await new Commands(this.db).accountScope(this.db,a,b.account_id);const {limit,cursor}=pagination(q);return page((await this.db.query('SELECT id,account_id,state,error_code,version,reviewed_at,created_at,updated_at FROM source_organizations WHERE workspace_id=$1 AND account_id=$2 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid)) ORDER BY created_at DESC,id DESC LIMIT $5',[a.workspaceId,b.account_id,cursor?.at??null,cursor?.id??null,limit+1])).rows,limit);}
 async create(tx:Tx,a:Actor,input:unknown){const b=parse(z.object({account_id:uuid,source_item_ids:z.array(uuid).max(20).refine(ids=>new Set(ids).size===ids.length)}).strict(),input);const account=await new Commands(this.db).accountScope(tx,a,b.account_id,true),workspace=(await tx.query('SELECT version FROM workspaces WHERE id=$1 FOR SHARE',[a.workspaceId])).rows[0];try{if(!loadAIConfig().enabled)throw new Error();}catch{throw new AppError(503,'AI_DISABLED','AI不可用，来源原文仍可人工整理');}const sources=(await tx.query('SELECT i.id,i.version,i.content_hash,i.title,i.summary,i.actual_source_type,i.published_at,i.captured_at,i.canonical_url,c.source_type FROM source_items i JOIN source_connections c ON c.id=i.connection_id WHERE i.workspace_id=$1 AND i.id=ANY($2::uuid[]) ORDER BY i.id FOR SHARE OF i',[a.workspaceId,b.source_item_ids])).rows;if(sources.length!==b.source_item_ids.length)throw new AppError(404,'NOT_FOUND','部分来源不存在或不可见');const snapshot={scope_version:'v1.2-s8',account:{id:account.id,name:account.name,version:account.version},workspace_version:workspace.version,sources},oid=id(),requestId=id();await tx.query('INSERT INTO source_organizations(id,workspace_id,account_id,created_by,snapshot) VALUES($1,$2,$3,$4,$5)',[oid,a.workspaceId,account.id,a.memberId,JSON.stringify(snapshot)]);const out=(await tx.query("INSERT INTO outbox(workspace_id,account_id,event_key,event_type,payload) VALUES($1,$2,$3,'source.organize',$4) RETURNING id",[a.workspaceId,account.id,'sources.organize:'+oid,JSON.stringify({created_by:a.memberId,pool:'general',request_id:requestId,input:{organization_id:oid}})])).rows[0],job=(await tx.query("INSERT INTO jobs(workspace_id,account_id,created_by,outbox_id,type,pool,input,request_id) VALUES($1,$2,$3,$4,'source.organize','general',$5,$6) RETURNING id",[a.workspaceId,account.id,a.memberId,out.id,JSON.stringify({organization_id:oid}),requestId])).rows[0];await audit(tx,a,'source.organization.create','source_organization',oid,{source_item_ids:b.source_item_ids});return {status:202,data:{organization_id:oid,job_id:job.id,state:'queued',status_url:'/api/v1/source-organizations/'+oid}};}
 async accept(tx:Tx,a:Actor,oid:string,input:unknown){const b=parse(z.object({group_indexes:z.array(z.number().int().nonnegative()).min(1).max(10),reason:text(1000),expected_version:version}).strict(),input);const r=await this.scope(tx,a,oid,true);if(r.version!==b.expected_version)throw new AppError(409,'VERSION_CONFLICT','整理记录已改变',{version:r.version});if(r.state!=='succeeded'||!(await sourceOrganizationCurrent(tx,r)))throw new AppError(409,'STALE_INPUT','来源已改变，请重新整理');if(new Set(b.group_indexes).size!==b.group_indexes.length||b.group_indexes.some(i=>!r.result.task_payload.groups[i]))throw new AppError(422,'GROUP_INVALID','请选择有效的整理主题');const updated=(await tx.query('UPDATE source_organizations SET accepted_group_indexes=$2,reviewed_by=$3,reviewed_at=now(),version=version+1,updated_at=now() WHERE id=$1 RETURNING *',[oid,b.group_indexes,a.memberId])).rows[0];await audit(tx,a,'source.organization.accept','source_organization',oid,{group_indexes:b.group_indexes,reason:b.reason});return {status:200,data:{...updated,current:true}};}
}
