import {z} from 'zod';
import {Database,Tx} from '../../../packages/db/src/db';
import {Actor,AppError,parse,uuid,version,text,pagination,page,id} from '../../../packages/domain/src/protocol';
import {Commands,audit} from './commands';
export class Topics {
 constructor(readonly db:Database){}
 async scope(query:Pick<Database,'query'>|Tx,a:Actor,topicId:string,lock=false){parse(uuid,topicId);const r=await query.query(`SELECT * FROM topics WHERE workspace_id=$1 AND id=$2 ${lock?'FOR UPDATE':''}`,[a.workspaceId,topicId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','选题不存在或不可见');await new Commands(this.db).accountScope(query,a,r.rows[0].account_id);return safeTopic(r.rows[0]);}
 async list(a:Actor,q:Record<string,unknown>){
  const {limit,cursor}=pagination(q);const account=q.account_id?parse(uuid,q.account_id):null;if(account)await new Commands(this.db).accountScope(this.db,a,account);
  const status=q.status?parse(z.enum(['proposed','accepted','rejected','expired']),q.status):null,media=q.media_type?parse(z.enum(['graphic','video']),q.media_type):null,fresh=q.freshness?parse(z.enum(['all','fresh','expired']),q.freshness):'all';
  const r=await this.db.query(`SELECT t.*,CASE WHEN t.status='proposed' AND t.expires_at<=now() THEN 'expired' ELSE t.status END effective_status,COALESCE(t.expires_at<=now(),false) expired FROM topics t WHERE t.workspace_id=$1 AND ($2::boolean OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.account_id=t.account_id AND am.membership_id=$3)) AND ($4::uuid IS NULL OR t.account_id=$4) AND ($5::text IS NULL OR CASE WHEN t.status='proposed' AND t.expires_at<=now() THEN 'expired' ELSE t.status END=$5) AND ($6::text IS NULL OR t.candidate->>'media_type'=$6) AND ($7='all' OR ($7='expired' AND t.expires_at<=now()) OR ($7='fresh' AND (t.expires_at IS NULL OR t.expires_at>now()))) AND ($8::timestamptz IS NULL OR (t.created_at,t.id)<($8,$9::uuid)) ORDER BY t.created_at DESC,t.id DESC LIMIT $10`,[a.workspaceId,a.roles.includes('admin'),a.memberId,account,status,media,fresh,cursor?.at??null,cursor?.id??null,limit+1]);return page(r.rows.map(safeTopic),limit);
 }
 async detail(a:Actor,topicId:string){const t=await this.scope(this.db,a,topicId);const evidence=(await this.db.query(`SELECT e.*,COALESCE(o.payload->>'title',s.title) title,COALESCE(o.payload->>'canonical_url',s.canonical_url) canonical_url,o.captured_at,o.payload observation FROM topic_evidence e LEFT JOIN source_items s ON s.id=e.source_item_id LEFT JOIN source_observations o ON o.id=e.observation_id WHERE e.topic_id=$1 ORDER BY e.created_at,e.id`,[t.id])).rows;const decisions=(await this.db.query('SELECT * FROM topic_decisions WHERE topic_id=$1 ORDER BY decided_at,id',[t.id])).rows;const owner_options=(await this.db.query("SELECT m.id,u.display_name FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=$1 AND m.active AND (m.roles && ARRAY['admin','editor','operator']::text[]) AND ($2::boolean OR m.id=$3) AND ('admin'=ANY(m.roles) OR EXISTS(SELECT 1 FROM account_memberships am WHERE am.membership_id=m.id AND am.account_id=$4)) ORDER BY u.display_name,m.id",[a.workspaceId,a.roles.some(r=>['admin','operator'].includes(r)),a.memberId,t.account_id])).rows;return {...t,owner_options,effective_status:t.status==='proposed'&&t.expires_at&&new Date(t.expires_at).getTime()<=Date.now()?'expired':t.status,expired:!!t.expires_at&&new Date(t.expires_at).getTime()<=Date.now(),evidence,decisions};}
 async reject(tx:Tx,a:Actor,topicId:string,input:unknown){const b=parse(z.object({reason:text(1000),expected_version:version}).strict(),input),t=await this.scope(tx,a,topicId,true);if(!a.roles.some(r=>['admin','operator'].includes(r))&&t.created_by!==a.memberId)throw new AppError(403,'OWNER_FORBIDDEN','编辑只能驳回本人生成的选题');this.mutable(t,b.expected_version);await tx.query("UPDATE topics SET status='rejected',version=version+1,updated_at=now() WHERE id=$1",[t.id]);await this.decision(tx,a,t,'rejected',b.reason);return {status:200,data:await this.scope(tx,a,t.id)};}
 private mutable(t:any,expected:number){if(t.version!==expected)throw new AppError(409,'VERSION_CONFLICT','选题已修改',{version:t.version});if(t.status!=='proposed')throw new AppError(409,'TOPIC_STATE_INVALID','只能处理待采纳选题');if(t.expires_at&&new Date(t.expires_at).getTime()<=Date.now())throw new AppError(409,'TOPIC_EXPIRED','选题已过期，请重新生成或明确创建变体');}
 private async decision(tx:Tx,a:Actor,t:any,decision:string,reason:string,owner:string|null=null){const r=await tx.query('INSERT INTO topic_decisions(workspace_id,topic_id,actor_id,decision,reason,owner_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[a.workspaceId,t.id,a.memberId,decision,reason,owner]);await audit(tx,a,'topic.'+decision,'topic',t.id,{owner_id:owner,reason});return r.rows[0].id;}
 async accept(tx:Tx,a:Actor,topicId:string,input:unknown){
  const b=parse(z.object({owner_id:uuid.optional(),expected_version:version}).strict(),input),t=await this.scope(tx,a,topicId,true),owner=b.owner_id??a.memberId;
  if(!a.roles.includes('admin')&&!a.roles.includes('operator')&&owner!==a.memberId)throw new AppError(403,'OWNER_FORBIDDEN','编辑只能采纳为本人事项');
  if(t.status==='accepted'){if(t.accepted_owner_id!==owner)throw new AppError(409,'TOPIC_ALREADY_ACCEPTED','选题已由其他负责人采纳');const d=(await tx.query("SELECT id FROM topic_decisions WHERE topic_id=$1 AND decision='accepted'",[t.id])).rows[0];return {status:200,data:{decision_id:d.id,topic_id:t.id,status:'accepted',version:t.version}};}
  this.mutable(t,b.expected_version);
  const member=(await tx.query('SELECT roles FROM memberships WHERE workspace_id=$1 AND id=$2 AND active FOR SHARE',[a.workspaceId,owner])).rows[0];if(!member||!member.roles.some((r:string)=>['admin','operator','editor'].includes(r)))throw new AppError(422,'OWNER_INVALID','负责人必须为有效成员');
  if(!member.roles.includes('admin')&&!(await tx.query('SELECT 1 FROM account_memberships WHERE account_id=$1 AND membership_id=$2',[t.account_id,owner])).rowCount)throw new AppError(422,'OWNER_INVALID','负责人无此账号访问权限');
  await tx.query("UPDATE topics SET status='accepted',accepted_owner_id=$2,version=version+1,updated_at=now() WHERE id=$1",[t.id,owner]);const decisionId=await this.decision(tx,a,t,'accepted','人工采纳选题，来源和假设仍需核验',owner);
  return {status:200,data:{decision_id:decisionId,topic_id:t.id,status:'accepted',version:t.version+1}};
 }
 async variant(tx:Tx,a:Actor,topicId:string,input:unknown){const b=parse(z.object({goal:text(10000),media_type:z.enum(['graphic','video'])}).strict(),input),parent=await this.scope(tx,a,topicId);const v=id(),candidate={...parent.candidate,original_angle:b.goal,media_type:b.media_type,assumptions:[...parent.candidate.assumptions,'人工明确创建的变体：'+b.goal]};
  // Each explicit variant has its own generation batch position, so original adoption remains unique.
  await tx.query('SELECT id FROM ai_requests WHERE id=$1 FOR UPDATE',[parent.generation_request_id]);const next=(await tx.query('SELECT COALESCE(max(candidate_position),0)+1 next FROM topics WHERE generation_request_id=$1',[parent.generation_request_id])).rows[0].next;
  await tx.query('INSERT INTO topics(id,workspace_id,account_id,created_by,generation_request_id,candidate_position,parent_topic_id,candidate,score,missing_inputs,warnings) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[v,a.workspaceId,parent.account_id,a.memberId,parent.generation_request_id,next,parent.id,JSON.stringify(candidate),parent.score,parent.missing_inputs,[...parent.warnings,'变体需要重新核验来源时效与事实']]);
  await tx.query('INSERT INTO topic_evidence(workspace_id,topic_id,source_item_id,observation_id,claim,evidence_kind) SELECT workspace_id,$2,source_item_id,observation_id,claim,evidence_kind FROM topic_evidence WHERE topic_id=$1',[parent.id,v]);await this.decision(tx,a,parent,'variant',b.goal);return {status:201,data:await this.scope(tx,a,v)};
 }
}

function safeTopic(t:any){const {required_asset_ids,...candidate}=t.candidate;return {...t,candidate,missing_inputs:t.missing_inputs.filter((s:string)=>!/素材|品牌规范|生效规范/.test(s))};}
