/** Real provider and real uploaded reference PNG, explicitly synthetic business scenario. */
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {Client,initialize,server} from '../tests/helpers';
import {uploadBytes} from '../tests/s2-helpers';
import {loadAIConfig} from '../packages/domain/src/ai-gateway';
import {AITasks} from '../packages/domain/src/ai-tasks';
import {Storage} from '../packages/domain/src/storage';
import {mediaHandler} from '../packages/domain/src/media';
import {Jobs} from '../packages/domain/src/jobs';
import {saveTopics} from '../packages/domain/src/topics';
import {scoreCriteria} from '../packages/domain/src/ai-workflows';
async function main(){const c=loadAIConfig(),dir=mkdtempSync(tmpdir()+'/yoyo-brief-live-'),previous=process.env.AI_CONFIG_FILE;writeFileSync(dir+'/config.json',JSON.stringify({...c,enabled:true,timeout_seconds:90,max_output_tokens:8192}),{mode:0o600});process.env.AI_CONFIG_FILE=dir+'/config.json';
 const env=await server(),storage=new Storage();await storage.init();const report:any={started_at:new Date().toISOString(),environment:'isolated *_test database',actual_model:true,model:c.model,input_kind:'explicit_synthetic_topics_with_real_provided_reference_PNG',asset_source:'docs/yoyo-workbench-v1.0/references/brand/page-17.png',quality_review:'not_performed',cases:[]};
 try{const client=new Client(env.url),me=await initialize(client),account=(await client.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'synthetic-live-brief',name:'明确合成制作单验收'})).data;
 const file=await uploadBytes(client,env.url,readFileSync(report.asset_source),'真实提供的参考页.png');const mediaJobs=new Jobs(env.db,{'media.preview':mediaHandler(env.db,storage)});await mediaJobs.dispatch();const media=await mediaJobs.claim('media');if(!media)throw new Error('MEDIA_JOB_MISSING');await mediaJobs.process(media);const created=await client.call('/assets','POST',{owner_id:me.membership.id,name:'真实参考页，仅制作单测试',category:'2d',ip_identity:'YOYO',source_file_id:file.id,source:'用户提供参考文档，不代表正式发布授权'});if(created.status!==201)throw new Error('ASSET_CREATE_FAILED');const asset=(await client.call('/assets/'+created.data.id+'/confirm','POST',{expected_version:created.data.version,usage_scope:'仅内部技术验收',checklist:['真实原件与测试范围']})).data;
 for(const kind of ['graphic','video']){const snapshot={account:{id:account.id,name:account.name,version:account.version},workspace_version:me.workspace.version,rule_set:null,rules:[],sources:[],assets:[{asset_version_id:asset.current_version_id,asset_id:asset.id,name:asset.name,asset_version:asset.version,business_status:asset.business_status,usage_scope:'仅内部技术验收'}]};const request=(await env.db.query("INSERT INTO ai_requests(workspace_id,account_id,created_by,kind,input_version,snapshot,state) VALUES($1,$2,$3,'topics',$4,$5,'succeeded') RETURNING *",[me.workspace.id,account.id,me.membership.id,randomUUID(),JSON.stringify(snapshot)])).rows[0];
 const candidate={title:'合成验收：观察品牌参考页',audience:'关注角色视觉表达的人',need:'学习观察视觉细节',scene:'内部技术验收',column:'观察',emotion:'好奇',media_type:kind,follow_reason:'持续观察不同视觉细节',evidence_refs:[],original_angle:'以参考页为观察材料，不作事实宣传',score_breakdown:scoreCriteria.map(criterion=>({criterion,score:4,reason:'合成验收评分'})),required_asset_ids:[asset.id],estimated_hours:1,expires_at:null,assumptions:['合成选题非运营事实']};await env.db.transaction(tx=>saveTopics(tx,request,{schema_version:'ai-v1',input_version:request.input_version,summary:'合成',evidence_refs:[],assumptions:[],missing_inputs:[],warnings:[],task_payload:{candidates:[candidate]}}));const topic=(await env.db.query('SELECT id FROM topics WHERE generation_request_id=$1',[request.id])).rows[0];const accepted=await client.call('/topics/'+topic.id+'/accept','POST',{expected_version:1,media_type:kind});if(accepted.status!==201)throw new Error('ADOPT_FAILED');const current=(await client.call('/contents/'+accepted.data.content_id)).data;
 const jobs=new Jobs(env.db,{'ai.generate':new AITasks(env.db).handler});await jobs.dispatch();const job=await jobs.claim('general');if(!job||job.type!=='ai.generate')throw new Error('BRIEF_JOB_MISSING');await jobs.process(job);const data=(await client.call('/contents/'+current.id)).data,r=data.generation_requests[0],generated=data.revisions.find((v:any)=>v.origin==='ai_candidate');const record:any={kind,request:r,unchanged_before_apply:data.current_revision_id===current.current_revision_id,candidate:generated?{id:generated.id,frozen:generated.frozen,payload:generated.payload}:null};report.cases.push(record);
 if(r.state!=='succeeded'||!generated||!record.unchanged_before_apply)throw new Error('BRIEF_GENERATION_FAILED');const applied=await client.call('/contents/'+current.id+'/apply-generated','POST',{result_revision_id:generated.id,expected_version:1});record.applied={status:applied.status,data:applied.data,error_code:applied.error?.code};record.attempts=(await env.db.query('SELECT a.attempt,a.state,a.usage,a.estimated_cost,a.cost_basis,a.duration_ms FROM ai_attempts a JOIN ai_requests r ON r.ai_run_id=a.run_id WHERE r.id=$1 ORDER BY a.attempt',[r.id])).rows;if(applied.status!==200)throw new Error('BRIEF_APPLY_FAILED');
 }
 report.asset_usages=(await client.call('/assets/'+asset.id+'/usages')).data.items.map((u:any)=>({revision_id:u.revision_id,usage_role:u.usage_role,asset_version_id:u.asset_version_id}));
 }finally{report.finished_at=new Date().toISOString();writeFileSync('docs/evidence/s3/brief-worker-live-probe.json',JSON.stringify(report,null,2)+'\n');await env.close();storage.destroy();if(previous===undefined)delete process.env.AI_CONFIG_FILE;else process.env.AI_CONFIG_FILE=previous;rmSync(dir,{recursive:true});}}
main().catch(()=>{console.error('BRIEF_LIVE_PROBE_FAILED');process.exitCode=1;});
