/** Adopt a real model-generated candidate from the immediately preceding isolated-DB probe; no new AI call. */
import {readFileSync,writeFileSync} from 'node:fs';
import {database,Client,adminInput} from '../tests/helpers';
import {createApp} from '../apps/api/src/main';
import {AddressInfo} from 'node:net';
async function main(){const prior=JSON.parse(readFileSync(process.env.TOPIC_SOURCE_REPORT??'docs/evidence/s3/topic-worker-live-probe.json','utf8'));if(prior.request.state!=='succeeded'||!prior.actual_model)throw new Error('PRIOR_PROBE_NOT_SUCCESSFUL');const db=await database(),app=await createApp(db),report:any={started_at:new Date().toISOString(),input_kind:'real_model_output_on_explicit_synthetic_business_input',environment:'isolated *_test database',source_report:process.env.TOPIC_SOURCE_REPORT??'docs/evidence/s3/topic-worker-live-probe.json',no_new_model_calls:true};
 try{await app.listen(0,'127.0.0.1');const client=new Client('http://127.0.0.1:'+(app.getHttpServer().address() as AddressInfo).port);await client.login(adminInput.email);const t=(await db.query('SELECT * FROM topics WHERE generation_request_id=$1 ORDER BY candidate_position LIMIT 1',[prior.request.id])).rows[0];if(!t||t.status!=='proposed')throw new Error('PRIOR_CANDIDATE_UNAVAILABLE');
 const input={expected_version:t.version,media_type:t.candidate.media_type},responses=await Promise.all([client.call('/topics/'+t.id+'/accept','POST',input),client.call('/topics/'+t.id+'/accept','POST',input)]);report.topic_id=t.id;report.responses=responses.map(r=>({status:r.status,data:r.data,error_code:r.error?.code}));report.content_count=(await db.query('SELECT count(*)::int n FROM contents WHERE topic_id=$1',[t.id])).rows[0].n;report.revision_count=(await db.query('SELECT count(*)::int n FROM content_revisions WHERE content_id=$1',[responses[0]!.data?.content_id])).rows[0].n;report.content=(await db.query('SELECT business_status,owner_id,media_type,current_revision_id FROM contents WHERE topic_id=$1',[t.id])).rows[0];report.job=(await db.query('SELECT id,type,state FROM jobs WHERE id=$1',[responses[0]!.data?.brief_job_id])).rows[0];
 if(responses.some(r=>r.status!==201)||responses[0]!.data.content_id!==responses[1]!.data.content_id||report.content_count!==1||report.revision_count!==1||report.content.business_status!=='draft'||report.job.state!=='queued')process.exitCode=1;
 }finally{report.finished_at=new Date().toISOString();writeFileSync(process.env.TOPIC_ADOPTION_REPORT??'docs/evidence/s3/topic-adoption-live-probe.json',JSON.stringify(report,null,2)+'\n');await app.close();await db.close();}}
main().catch(()=>{console.error('TOPIC_ADOPTION_PROBE_FAILED');process.exitCode=1;});
