/** Actual authorized model; synthetic imported values in a separate disposable evaluation database. */
import {writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {server,Client,initialize} from '../../tests/helpers';
import {AIGateway,loadAIConfig} from '../../packages/domain/src/ai-gateway';
import {ReportTasks,reportSpec} from '../../packages/domain/src/reports';
import {Jobs} from '../../packages/domain/src/jobs';
import {sha,canonical} from '../../packages/domain/src/protocol';
async function main(){if(new URL(process.env.TEST_DATABASE_URL!).pathname!=='/yoyo_s8_ai_test')throw new Error('Dedicated S8 AI evaluation database required');const env=await server(),client=new Client(env.url),config={...loadAIConfig(),enabled:true,timeout_seconds:90,max_output_tokens:16000};const report:any={date:'2026-10-10',environment:'yoyo_s8_ai_test',input_kind:'explicit_synthetic_confirmed_metrics_not_platform_backend',actual_provider:true,model:config.model,cases:[]};mkdirSync('.local/s8-ai-evaluation',{recursive:true,mode:0o700});writeFileSync('.local/s8-ai-evaluation/config.json',JSON.stringify(config),{mode:0o600});process.env.AI_CONFIG_FILE='.local/s8-ai-evaluation/config.json';const save=()=>writeFileSync('docs/evidence/s8/live-reports.json',JSON.stringify(report,null,2)+'\n');
 try{const me=await initialize(client),account=(await client.call('/accounts','POST',{platform:'xiaohongshu',platform_user_id:'s8-live-synthetic',name:'明确合成的实际模型复盘输入'})).data;const body={account_id:account.id,start:'2026-09-01T00:00:00.000Z',end:'2026-09-08T00:00:00.000Z'};const tasks=new ReportTasks(env.db,()=>new AIGateway(env.db,config)),jobs=new Jobs(env.db,{'report.generate':tasks.handler});
 async function run(id:string){const accepted=await client.call('/reports','POST',body);assert.equal(accepted.status,202,JSON.stringify(accepted.error));const row=(await client.call('/reports/'+accepted.data.report_id)).data,spec=reportSpec(row.snapshot);const record:any={id,input_hash:row.snapshot.input_version,prompt_version:spec.promptVersion,schema_version:spec.schemaVersion,report_id:row.id,job_id:row.job_id,input:row.snapshot,started_at:new Date().toISOString()};report.cases.push(record);save();await jobs.dispatch();const job=(await jobs.claim('general'))!;assert.equal(job.id,row.job_id);await jobs.process(job);const final=(await client.call('/reports/'+row.id)).data;record.state=final.state;record.status=final.status;record.error_code=final.error_code;record.provider_output=(await env.db.query('SELECT result FROM ai_runs WHERE job_id=$1 ORDER BY started_at DESC LIMIT 1',[job.id])).rows[0].result;record.provider_output_hash=sha(canonical(record.provider_output));record.output=final.result;record.output_hash=sha(canonical(final.result));record.attempts=(await env.db.query('SELECT state,usage,cost_basis,estimated_cost,duration_ms FROM ai_attempts WHERE run_id IN (SELECT id FROM ai_runs WHERE job_id=$1) ORDER BY started_at',[job.id])).rows;record.finished_at=new Date().toISOString();save();assert.equal(final.state,'succeeded',JSON.stringify({error:final.error_code}));return final;}
 const empty=await run('REPORT-EMPTY');assert.equal(empty.status,'partial');assert.deepEqual(empty.result.facts,[]);
 for(const [time,value] of [[body.start,'600'],[body.end,'631']]){const batch=(await client.call('/imports','POST',{account_id:account.id,file_ids:[],source_type:'manual',manual_rows:[{target:{account_id:account.id,publication_id:null},metric_key:'followers',definition_version:'1',aggregation_kind:'snapshot',observed_at:time,value,unit:'人',source_definition:'明确合成同平台口径',traffic_type:'organic',time_precision:'day'}]})).data;const rows=(await client.call('/imports/'+batch.id+'/rows')).data.items;const confirmed=await client.call('/imports/'+batch.id+'/confirm','POST',{row_ids:rows.map((r:any)=>r.id),conflict_resolutions:[],expected_version:batch.version,reason:'合成实际模型评估确认'});assert.equal(confirmed.status,200);}
 const complete=await run('REPORT-NET');assert.equal(complete.status,'final');assert.equal(complete.result.facts[0].value,'31.000000');assert.equal(complete.result.facts[0].input_observation_ids.length,2);assert.equal((await client.call('/reports/'+empty.id)).data.status,'stale');assert.equal((await env.db.query('SELECT count(*)::int n FROM strategy_memories')).rows[0].n,0);report.result='passed';report.quality_review='pending';save();console.log(JSON.stringify({result:'passed',cases:report.cases.length}));
 }finally{report.finished_at=new Date().toISOString();save();await env.close();}}
main().catch(e=>{console.error('S8_REPORT_EVALUATION_FAILED',e instanceof assert.AssertionError?e.message:'execution failed');process.exitCode=1;});
