import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {server,Client,initialize} from '../../tests/helpers';
import {AIGateway,loadAIConfig} from '../../packages/domain/src/ai-gateway';
import {FeedbackTasks,feedbackSpec} from '../../packages/domain/src/feedback';
import {Jobs} from '../../packages/domain/src/jobs';
import {sha,canonical} from '../../packages/domain/src/protocol';
async function main(){assert.equal(new URL(process.env.TEST_DATABASE_URL!).pathname,'/yoyo_s8_ai_test');process.env.AI_CONFIG_FILE='.local/s8-ai-evaluation/config.json';const config=loadAIConfig(),env=await server(),c=new Client(env.url),report:any={date:'2026-10-10',input_kind:'explicit_synthetic_feedback_not_real_person',actual_provider:true,model:config.model,cases:[]};const save=()=>writeFileSync('docs/evidence/s8/live-feedback.json',JSON.stringify(report,null,2)+'\n');try{await initialize(c);const a=(await c.call('/accounts','POST',{name:'明确合成反馈评估',platform:'xiaohongshu',platform_user_id:'feedback-live-synthetic'})).data;for(const consent_status of ['unknown','approved']){const f=(await c.call('/feedback','POST',{account_id:a.id,text:'我最近开始用散步记录附近的声音，但不太会组织文字。想了解怎样从熟悉的小场景找到表达角度。',consent_status,permitted_usage:{public_reply:consent_status==='approved',topic_reference:consent_status==='approved'}})).data;const queued=await c.call('/feedback/'+f.id+'/organize','POST',{expected_version:f.version});assert.equal(queued.status,202);const jobs=new Jobs(env.db,{'feedback.organize':new FeedbackTasks(env.db,()=>new AIGateway(env.db,config)).handler});await jobs.dispatch();const job=(await jobs.claim('general'))!,spec=feedbackSpec(job.input.snapshot),record:any={id:'FEEDBACK-'+consent_status.toUpperCase(),input:job.input.snapshot,input_hash:spec.inputVersion,prompt_version:spec.promptVersion,schema_version:spec.schemaVersion,started_at:new Date().toISOString()};report.cases.push(record);save();await jobs.process(job);const final=(await c.call('/feedback/'+f.id)).data,j=(await c.call('/jobs/'+job.id)).data;record.state=j.state;record.error_code=j.error_code;record.output=(await env.db.query('SELECT result FROM ai_runs WHERE job_id=$1 ORDER BY started_at DESC LIMIT 1',[job.id])).rows[0]?.result;record.output_hash=sha(canonical(record.output));record.persisted={reply_draft:final.reply_draft,quotes:final.quotes,topic_leads:final.topic_leads,category:final.category};record.attempts=(await env.db.query('SELECT state,usage,cost_basis,estimated_cost,duration_ms FROM ai_attempts WHERE run_id IN (SELECT id FROM ai_runs WHERE job_id=$1) ORDER BY started_at',[job.id])).rows;save();assert.equal(j.state,'succeeded',j.error_code);if(consent_status==='unknown'){assert.equal(final.reply_draft,'');assert.deepEqual(final.topic_leads,[]);}else{assert.ok(final.reply_draft);assert.ok(final.topic_leads.length);const revoked=await c.call('/feedback/'+f.id,'PATCH',{consent_status:'revoked',reason:'合成撤回许可',expected_version:final.version});assert.equal(revoked.status,200);assert.equal(revoked.data.reply_draft,'');assert.deepEqual(revoked.data.topic_leads,[]);record.revocation='cleared_reply_quotes_leads';save();}}report.result='passed';report.quality_review='pending';save();console.log(JSON.stringify({result:'passed',cases:report.cases.length}));}finally{report.finished_at=new Date().toISOString();save();await env.close();}}
main().catch(e=>{console.error('S8_FEEDBACK_EVALUATION_FAILED',e instanceof assert.AssertionError?e.message:'execution failed');process.exitCode=1;});
