import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {canonical,sha} from '../../packages/domain/src/protocol';
import {whitelistIssues} from '../../packages/domain/src/ai-gateway';
import {reportSpec} from '../../packages/domain/src/reports';
import {feedbackSpec} from '../../packages/domain/src/feedback';
import {sourceOrganizationSpec} from '../../packages/domain/src/source-organization';
import {evaluationCases} from '../s3/evaluation-fixtures';
import {checkEvaluation} from '../s3/evaluation-checks';
const read=(name:string)=>JSON.parse(readFileSync('docs/evidence/s8/'+name,'utf8'));
const rows:any[]=[];
function quality(r:any,q:any,spec:any){const output=r.provider_output??r.output;assert.equal(r.state,'succeeded',r.id);assert.equal(r.input_hash,spec.inputVersion,r.id);assert.equal(r.prompt_version,spec.promptVersion,r.id);assert.equal(r.schema_version,spec.schemaVersion,r.id);assert.equal(output.input_version,spec.inputVersion);assert.equal(output.schema_version,spec.schemaVersion);assert.ok(spec.schema.safeParse(output).success);assert.deepEqual(spec.validate?.(output)??[],[],r.id);assert.deepEqual(whitelistIssues(output,spec.allowedIds),[]);if(r.provider_output)assert.equal(r.provider_output_hash,sha(canonical(output)));const hash=sha(canonical(r.output));assert.equal(q.output_hash,hash,r.id);if(r.output_hash)assert.equal(r.output_hash,hash);const scores=Object.values(q.scores) as number[];assert.equal(scores.length,5);assert.ok(scores.every(s=>Number.isInteger(s)&&s>=3&&s<=5));assert.equal(q.total,scores.reduce((a,b)=>a+b,0));assert.ok(q.total>=20);const attempts=r.attempts;assert.ok(attempts.length);rows.push({id:r.id,workflow:spec.workflow,prompt_version:spec.promptVersion,schema_version:spec.schemaVersion,input_hash:r.input_hash,output_hash:hash,quality_total:q.total,requests:attempts.length,total_tokens:attempts.reduce((n:number,a:any)=>n+(a.usage?.total_tokens??0),0)});}
const topics=read('ai-topics-live.json'),review=read('ai-topics-review.json');assert.equal(topics.cases.length,20);for(const c of evaluationCases){const r=topics.cases.find((r:any)=>r.id===c.definition.id),q=review.cases.find((r:any)=>r.id===c.definition.id);assert.deepEqual(checkEvaluation(c,r.output).hard_errors,[]);assert.deepEqual(q.hard_semantic_errors,[]);quality(r,q,c.spec);}
for(const [file,spec,count] of [['live-reports.json',reportSpec,2],['live-feedback.json',feedbackSpec,2],['live-sources.json',sourceOrganizationSpec,3]] as const){const report=read(file);assert.equal(report.result,'passed');assert.equal(report.actual_provider,true);assert.equal(report.cases.length,count);for(const r of report.cases)quality(r,r.quality??report.quality.find((q:any)=>q.case_id===r.id),spec(r.input));}
assert.equal(new Set(rows.map(r=>r.id)).size,27);const result={date:'2026-10-10',result:'passed',actual_provider:true,synthetic_inputs:true,review:'internal_technical_not_business_user_acceptance',cases:27,workflows:4,requests:rows.reduce((n,r)=>n+r.requests,0),total_tokens:rows.reduce((n,r)=>n+r.total_tokens,0),cost_basis:'unknown',checks:['current prompt/schema/input hashes','actual output hashes','schema/ID/numeric/quote/consent validators','each five scores >=3, total >=20','all 20 topic hard-semantic gates'],case_details:rows};writeFileSync('docs/evidence/s8/ai-quality-validation.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,case_details:undefined}));
